### ISSUE TITLE
a question about the code of universal transformer

### ISSUE THREAD

**Issue by cyvius96** [tensorflow/tensor2tensor#1004]
https://github.com/tensorflow/tensor2tensor/blob/2f8423a7daf39c549fa4f87d369d3ff95e719e6c/tensor2tensor/models/research/universal_transformer_util.py#L1207

Is this supposed to be "(previous_state * (1 - update_weights))" instead of "(previous_state * 1 - update_weights)"?

Thanks.

**Comment by akikaaa** [comment]
It makes sense to be  `new_state = transformed_state * update_weights +previous_state` given that update_weights is just p_t (in some sense) and previous_state is just the sum of previous p_t*s_t
