### ISSUE TITLE
Missing requirement in dev mode : matplotlib 

### ISSUE THREAD

**Issue by tlatkowski** [tensorflow/tensor2tensor#1020]
### Description
When I try to install T2T in dev mode (pip install -e .) and run some data generation command, like:
t2t-datagen \
  --t2t_usr_dir=$USR_DIR \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --problem=$PROBLEM
 
i get an error:

/tensor2tensor/tensor2tensor/data_generators/image_utils.py", line 24, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

After installing matplotlib manually the error is gone.
...

### Environment information

```
OS: Ubuntu 18.04

$ pip freeze | grep tensor
-e git+https://github.com/tlatkowski/tensor2tensor.git@408625068db7f930a4434a1ce079f1503c531483#egg=tensor2tensor
tensorboard==1.10.0
tensorflow==1.10.0


$ python -V
Python 3.6.5
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:

1. Pull the latest code from T2T repo.
2. Install T2T in dev mode
3. Run data gen script:
t2t-datagen \
  --t2t_usr_dir=$USR_DIR \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --problem=$PROBLEM
```

```
# Error logs:

/tensor2tensor/tensor2tensor/data_generators/image_utils.py", line 24, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'


```

**Comment by afrozenator** [comment]
Thanks for reporting @tlatkowski  -- will fix soon.

**Comment by afrozenator** [comment]
Fixed matplotlib in https://github.com/tensorflow/tensor2tensor/commit/d1946d4c258eeea9f8f89ec9e5814e6429432259

@rsepassi fixed the __init__.py in https://github.com/tensorflow/tensor2tensor/commit/5874f6623f12455ade2680ef02d77a8658af6ea8
