### ISSUE TITLE
Results of Transformer model for single GPU - not promising (as shown below)

### ISSUE THREAD

**Issue by WeibiaoHuang** [tensorflow/tensor2tensor#103]
zukommt parution etzworld       Hello world
Good    Goodbye world
zukommt parution etzworld       Hello world
Good    Goodbye world
zukommt parution etzworld       Hello world
Good    Goodbye world

**Comment by lukaszkaiser** [comment]
This looks like a vocabulary issue that was corrected in 1.0.11. please give it a try. I'm closing for now, but please reopen if you still see the issue -- and add more details about your training setup (how many gpus, which model / data-set, how many training steps, what does eval show / screenshot).
