### ISSUE TITLE
Is GPU requirement a requirement?

### ISSUE THREAD

**Issue by skeydan** [tensorflow/tensor2tensor#11]
Hi,

I'd very much like to try this, but I don't have an nvidia gpu... Is the dependency on tensorflow-gpu a hard requirement?

Thanks a lot
Sigrid

**Comment by odunboye** [comment]
will also like to know

**Comment by lukaszkaiser** [comment]
It shouldn't be, I can run tensor2tensor on CPU only. Does the pip package require GPU? If so, we should change it. I think you should be able to pip install tensorflow (no gpu) and then pip install tensor2tensor, does that work?

**Comment by skeydan** [comment]
Hi, thanks!
Yes, you have the requirement in setup.py... I already have cpu-only tensorflow installed, but when I run pip install tensor2tensor it doesn't want that one and crashes with the libaCUDA... thing...

**Comment by stefan-it** [comment]
I can also confirm that `tensor2tensor` is working on a CPU-only computer. 

@skeydan Could you try running the `pip` installation with `--no-dependencies`? So it hopefully won't install the gpu version of *TensorFlow* :)

**Comment by rsepassi** [comment]
1.0.5 does not require tensorflow-gpu.

You can install tensorflow (cpu or gpu versions) separately or have it with tensor2tensor:

```
pip install tensor2tensor # assumes tensorflow already installed
pip install tensor2tensor[tensorflow] # will install cpu version
pip install tensor2tensor[tensorflow_gpu] # will install gpu version
```
