### ISSUE TITLE
Why decode_from_file writes both input and output sentences?

### ISSUE THREAD

**Issue by skyw** [tensorflow/tensor2tensor#112]
It makes it harder to compute bleu or  other type of scores against target file.

**Comment by lukaszkaiser** [comment]
True, it somehow looked like a good idea, but no real reason. We welcome a PR that changes that, feel free to send it along!

**Comment by stefan-it** [comment]
I'm going to look into this issue :)

**Comment by lukaszkaiser** [comment]
Merged Stefan's PR, so closing this issue. Thanks!
