### ISSUE TITLE
Error when adding own components

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensor2tensor#114]
I strictly follow this example:
https://github.com/tensorflow/tensor2tensor#adding-your-own-components

When I run `t2t-trainer --t2t_usr_dir=~/usr/t2t_usr --registry_help` I get an `importlib` error saying `no module named `my_registrations`.

When running  `t2t-trainer --t2t_usr_dir=~/usr/t2t_usr/my_registrations --registry_help` it works. But I can only import a single file with this approach.

I tested it on Windows 10 and Fedora 24.

**Comment by rsepassi** [comment]
Does your `t2t_usr` directory have an `__init__.py` file that has the line `import my_registrations`? And does the `t2t_usr` directory also have a file named `my_registrations.py`?

**Comment by EndingCredits** [comment]
I had the same issue. Seems like the problem is that `__init__.py` is importing relative to your current directory, and not its directory. `import usr.t2t_usr.my_registrations` should be a quick hack to get this working.

**Comment by rsepassi** [comment]
Ok, relative import functionality changed in Python 3, so in `__init__.py`, instead of `import my_registrations`, use `from . import my_registrations`. That will work in Py2 and 3. I'll update the README shortly. Thanks for reporting!
