### ISSUE TITLE
mesh-tensorflow imports broken if pip installing from latest mesh-tensorflow

### ISSUE THREAD

**Issue by rllin-fathom** [tensorflow/tensor2tensor#1148]
### Description
unit tests in master such as https://github.com/tensorflow/tensor2tensor/blob/3f43417310101859f95b74587ffc3686714cc58a/tensor2tensor/models/mtf_image_transformer_test.py#L62
require `mesh-tensorflow`.

However, installing via pip https://github.com/tensorflow/mesh/issues/5 is broken.

Thought I'd crosspost this here for visibility and perhaps mtf tests can be skipped in https://github.com/tensorflow/tensor2tensor/blob/3f43417310101859f95b74587ffc3686714cc58a/tensor2tensor/models/mtf_image_transformer_test.py#L62 for now?  Unclear to me if that is sufficient due to it being imported in other places.

**Comment by dustinvtran** [comment]
Apologies for that. It looks like MTF needs a new PyPI release. I am bumping the version number. After it's submitted (soon), I'll release it.

**Comment by rllin-fathom** [comment]
@dustinvtran thanks for the quick turnaround!

**Comment by guotong1988** [comment]
thanks
