### ISSUE TITLE
wmt_ende_tokens_32k downloads all datasets

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensor2tensor#115]
When running t2t-datagen with `wmt_ende_tokens_32k` it will download all datasets instead of only downloading ende. Is this intended?

The problem is that `ende_wordpiece_token_generator` does not specify the `data_sources` to download from.

https://github.com/tensorflow/tensor2tensor/blob/de38b168a7e53f7352048b87c276d5a484111f64/tensor2tensor/data_generators/wmt.py#L228

**Comment by lukaszkaiser** [comment]
This is intended, because we build one multi-lingual vocabulary. We could add an option to change that, but is it worth it?
