### ISSUE TITLE
Training (translation) with new lines / line breaks.

### ISSUE THREAD

**Issue by nadavb** [tensorflow/tensor2tensor#1150]
I would like to train the t2t for translation, but to preserve newlines/line breaks.
The problem is that, from what I see, the before/after files supplied to the t2t (for example translate_ende.py) are defined as one training example per line, so if I add a new line it will be treated as two examples/instances.

What is the right way to solve it?

Is there an option to define some kind of special token, and then convert newline into special-token during training, and then during inference do the same thing, plus, reverse conversion of special-token to newline? If this is the right way to solve it, then the special token should either be a very-rarely-used UTF-8 character, otherwise there is a risk that it will genuinely appear in some real text?

Another option is do some URLencoding for the texts, so newlines will be encoded to some no-newline string.

What do you think is the right approach that will not confuse the training quality of the t2t?

**Comment by afrozenator** [comment]
maybe use unprintable ascii characters? or encode them as \n in the data and have "\\n" as a reserved token in a problem? that might work.

See `additional_reserved_tokens` in `QuestionAndContext2TextProblem` in `text_problems.py`

unprintable ascii characters should definitely work though, just replace \n when you read the file in data_generator from \0 to \31 or something?

Hope this helps?

**Comment by nadavb** [comment]
I think it's a great idea.
