### ISSUE TITLE
Adding static inputs to sequence problems

### ISSUE THREAD

**Issue by mikeymezher** [tensorflow/tensor2tensor#1155]
I'm interested in adding static inputs to sequence problems (transformer model). Specifically, I'd like to add a multihot vector to every FFN layer in the decoder stack. My current attempt has been to create the multihot vector during data generation and propagate it through along with the example's inputs/targets as an additional feature, then add that additional feature to the example_reading_spec. Since the format is already a tf.constant, there should be no need to apply a modality to it (I believe the identity modality is applied regardless). However it appears this additional feature is being lost somewhere en route to the decoder. 

Has anyone tried something similar to this? Or does anyone know any reasons the feature may be getting lost? More generally, is there a standard way to add raw inputs to different layers in the transformer? I've tried finding this within existing documentation, but had no luck.

TF 1.9
T2T 1.9

**Comment by mikeymezher** [comment]
Found my issue. maybe_pack_example causes yields only 'inputs','targets' and associated segmentation and positions. Need to create a custom packer for this purpose.

**Comment by afrozenator** [comment]
Hi Michael -- I didn't read this carefully, but we are going to remove
packing soon, there will be no need to pack sequences in the coming future.
Thanks

**Comment by mikeymezher** [comment]
Interesting, thanks for the heads up
