### ISSUE TITLE
How to use the t2t-decoder?

### ISSUE THREAD

**Issue by Runingtime** [tensorflow/tensor2tensor#1157]
I am trying to use t2t for text summarization. However, I didn't find any documents that describe how to set the hyper-parameters.  For example, how to limit the decoding length? 
So, could someone tell me if there are related descriptions or tutorials? Thanks!

**Comment by mehmedes** [comment]
[decoding.py](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/decoding.py) will provide you with the possibilities:

https://github.com/tensorflow/tensor2tensor/blob/a4f958a887f4f4466644dd0602bdd33985d61dd7/tensor2tensor/utils/decoding.py#L44-L74

You may change these values by adding the flag ```-decode_hparams="beam_size=1,alpha=0, etc."``` when running  ```t2t-decoder```. I think ```extra_length``` defines the decode_length.

**Comment by afrozenator** [comment]
Thanks for responding @mehmedes ! I hope this answers your question @Runingtime !
