### ISSUE TITLE
ImportError: cannot import name 'control_flow_util'

### ISSUE THREAD

**Issue by wcollins-ebsco** [tensorflow/tensor2tensor#1167]
### Description
ImportError: cannot import name 'control_flow_util'

### Environment information

```
OS: Windows 10

$ pip freeze | grep tensor
tensor2tensor==1.9.0
tensorflow==1.4.0
tensorflow-tensorboard==0.4.0rc3

$ python -V
# your output here
Python 3.6.3

### For bugs: reproduction and error logs

```
# Steps to reproduce:

from tensor2tensor import problems
```

```
# Error logs:
Skipped importing 61 data_generators modules.
From module tensor2tensor.data_generators.algorithmic
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-672210f24633> in <module>()
----> 1 from tensor2tensor import problems

c:\ml\env\lib\site-packages\tensor2tensor\problems.py in <module>()
     30 
     31 
---> 32 all_problems.import_modules(all_problems.ALL_MODULES)

c:\ml\env\lib\site-packages\tensor2tensor\data_generators\all_problems.py in import_modules(modules)
    119     except ImportError as error:
    120       errors.append((module, error))
--> 121   _handle_errors(errors)

c:\ml\env\lib\site-packages\tensor2tensor\data_generators\all_problems.py in _handle_errors(errors)
    107     if not _is_import_err_msg(err_str, module):
    108       print("From module %s" % module)
--> 109       raise err
    110     if log_all:
    111       print("Did not import module: %s; Cause: %s" % (module, err_str))

c:\ml\env\lib\site-packages\tensor2tensor\data_generators\all_problems.py in import_modules(modules)
    116   for module in modules:
    117     try:
--> 118       importlib.import_module(module)
    119     except ImportError as error:
    120       errors.append((module, error))

c:\ml\env\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

c:\ml\env\lib\site-packages\tensor2tensor\data_generators\algorithmic.py in <module>()
     23 from six.moves import range  # pylint: disable=redefined-builtin
     24 from tensor2tensor.data_generators import generator_utils as utils
---> 25 from tensor2tensor.data_generators import problem
     26 from tensor2tensor.data_generators import text_encoder
     27 from tensor2tensor.utils import metrics

c:\ml\env\lib\site-packages\tensor2tensor\data_generators\problem.py in <module>()
     27 from tensor2tensor.data_generators import text_encoder
     28 from tensor2tensor.utils import data_reader
---> 29 from tensor2tensor.utils import metrics
     30 import tensorflow as tf
     31 from tensorflow.contrib.tpu.python.tpu import tpu_config

c:\ml\env\lib\site-packages\tensor2tensor\utils\metrics.py in <module>()
     22 import six
     23 
---> 24 from tensor2tensor.layers import common_layers
     25 from tensor2tensor.utils import bleu_hook
     26 from tensor2tensor.utils import registry

c:\ml\env\lib\site-packages\tensor2tensor\layers\common_layers.py in <module>()
     32 from tensorflow.python.framework import function
     33 from tensorflow.python.framework import ops
---> 34 from tensorflow.python.ops import control_flow_util
     35 from tensorflow.python.ops import inplace_ops
     36 

ImportError: cannot import name 'control_flow_util'
```

**Comment by afrozenator** [comment]
Hi @wcollins-ebsco -- You TF is too old, we only work for the last 2 versions of TF (in this case they happen to be 1.10 and 1.11)

Please upgrade your Tensorflow package.
