### ISSUE TITLE
Issues with padding in language modeling problems. 

### ISSUE THREAD

**Issue by mikeymezher** [tensorflow/tensor2tensor#1176]
Related to [#1013](https://github.com/tensorflow/tensor2tensor/issues/1013) 
Default 0 padding does not take into account order of vocab. If <pad> is not located at the 0th index of the .token vocab file, a random term will be "padding" sequences (whatever term exists at this location). Rather than require the user to generate the vocab in a specific order, it may be best to replace 0 padding with [token_encoder.PAD_ID]*pad_length in areas that padding occurs.

**Comment by afrozenator** [comment]
so the vocab file was not generated by t2t? if it was pad should always be 0.

if not it is probably best to have 0/1 as pad and eos -- too many places in the code make this assumption, so maybe infeasible to change it.

**Comment by mikeymezher** [comment]
Correct - this works perfectly fine and would not be difficult to adapt to ensure pad and eos are 0/1 respectively. 
However, this is not really mentioned anywhere in the documentation and results in strange decoding results if a custom vocab is generated that doesn't have the proper format. If it's left as is I think it should be stated explicitly in [vocabulary specification](https://tensorflow.github.io/tensor2tensor/new_problem.html) mentioning that if the subword text encoder or character encoder is not used/the user chooses to generate their own  vocab, <pad> and <eos> should be the first and second term in the .token file respectively.

**Comment by afrozenator** [comment]
Thanks, let me try to either document or put asserts in the code to that
effect
