### ISSUE TITLE
where to add the position signal in universal transformer when add_sru=False, add_position_timing_signal = True

### ISSUE THREAD

**Issue by dqqcasia** [tensorflow/tensor2tensor#1187]
When add_position_timing_signal = True，add_sru=False，where the position_timing_signal is added?

**Comment by MostafaDehghani** [comment]
In the universal transformer, when you set add_position_timing_signal  to True, [positional embedding will be added the input of "each" step](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/research/universal_transformer_util.py#L1814), unlike the normal transformer which adds the positional embedding just once, to the original input. 
This is actually independent of the "add_sru", but as there will be the notion of the order somehow encoded with an SRU, when "hparams.add_sru=True" you might wanna set  "hparams.add_position_timing_signal=False" and "hparams.pos = None"
I neve tried this though!
