### ISSUE TITLE
Unable to utilize 8 gpus on a high performance cluster

### ISSUE THREAD

**Issue by zx1301** [tensorflow/tensor2tensor#1188]
### Description
I'm an undergraduate student fairly new to natural language processing and machine translation and I want to train the transformer model on 8 gpus. I tried to follow the solution for Issue #124 but the GPU's are still unresponsive.
...

### Environment information
tensor2tensor==1.9.0
tensorboard==1.11.0
tensorflow==1.11.0

OS: CentOS

$ python -V
Python 3.6.0

I tried to train using this:
PROBLEM=translate_ende_wmt32k
MODEL=transformer
HPARAMS=transformer_base

DATA_DIR=$HOME/t2t_data
TMP_DIR=/tmp/t2t_datagen
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --problem=$PROBLEM

t2t-trainer \
  --data_dir=$DATA_DIR \
  --problem=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --hparams='batch_size=2048' \
  --worker_gpu=8

###GPU information:
![image](https://user-images.githubusercontent.com/35082619/47806543-66e06f80-dd10-11e8-8122-9a76835081c6.png)

Training Step 26 minutes into training:
![training log](https://user-images.githubusercontent.com/35082619/47807117-aeb3c680-dd11-11e8-8285-73f6f05fe256.PNG)

I tried cancelling and rerunning the training jobs and right now model is on its first step, but I've seen it move onto the next step. When it did move on, it took about 700 seconds and the 8 GPU's were not being utilized (no running processes found and no memory being used). I may be missing something obvious and any help would be greatly appreciated.

**Comment by echan00** [comment]
did you run this?

`export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7`

**Comment by echan00** [comment]
It looks like this is your problem. You need to uninstall T2T and reinstall T2T and T2T GPU Only

**Comment by zx1301** [comment]
I tried "export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7" and i tried uninstalling T2T and reinstalling T2T and T2T with Tensorflow-GPU requirements and now i get "ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory." I had to use the "--user" tag when installing.

**Comment by echan00** [comment]
Probably a good idea to install via virtualenv

**Comment by zx1301** [comment]
i just tried using "pip install tensor2tensor[tensorflow_gpu]" in my virtual environment to install it and it gives me the same import error.
