### ISSUE TITLE
t2t_datagen / translate_enzh_wmt32k - How long does it take? (attached log)

### ISSUE THREAD

**Issue by echan00** [tensorflow/tensor2tensor#1199]
How long is this supposed to take?  It's been 8 hours now..

Attached [log.txt](https://github.com/tensorflow/tensor2tensor/files/2545010/log.txt)

**Comment by lowblung** [comment]
How many GPUs are you using?

**Comment by echan00** [comment]
I am using 8 GPUs, i ended up also taking 10-13 hours

**Comment by Sc-TuDou** [comment]
How much memory did you use for t2t-datagen?

**Comment by Sc-TuDou** [comment]
My mem is 68G, but it doesn't enough for the data of translate_enzh_wmt32k.
