### ISSUE TITLE
Exporting Trained Models with SavedModel API

### ISSUE THREAD

**Issue by belph** [tensorflow/tensor2tensor#120]
Currently, as far as I can tell, `t2t-trainer` only saves model checkpoints. It would be useful if there was a flag which also indicated that a `SavedModel` should be produced (perhaps by just adding a simple [`ExportStrategy`](https://www.tensorflow.org/api_docs/python/tf/contrib/learn/ExportStrategy) to the `Experiment` which is created). This would allow models trained with tensor2tensor to be loaded by things like the TensorFlow Java API bindings. Would this make sense to add?

(Apologies if I'm just misunderstanding something and there's already a way to do this)

**Comment by lukaszkaiser** [comment]
Yes! I think we just forgot about SavedModel, it would be very good to add. A PR is more than welcome!

**Comment by ariwaranosai** [comment]
It seems that model export has already implemented.

**Comment by lukaszkaiser** [comment]
Yes, done, thanks!

**Comment by alsora** [comment]
Hi @lukaszkaiser, @belph.

I have exported a frozen graph of the Transformer network.
Now I would like to use it through the Java API.

My problem is that I do not know how to specify the name of the input and output layers here:
```
Tensor<Double> output = session
		        .runner()
		        .feed("input", input)
		        .fetch("output")
		        .run()
		        .get(0)
```
