### ISSUE TITLE
tf.contrib.learn.Experiment

### ISSUE THREAD

**Issue by justatest248** [tensorflow/tensor2tensor#122]
Hi,
I'm wondering why using `tf.contrib.learn.Experiment` instead of `tf.Session()`, which makes it even harder to debug or print variables in `t2t`.

I know it might be a tensorflow issue, but I'm just curious how the t2t team debug, (print variable values) in the `tf.contrib.learn.Experiment` scheme. Because I think other will meet such problems, too

**Comment by cshanbo** [comment]
I had the same trouble, too. I'm planning to decoupling the structure to make it easier to debug, but it seems to be a trivial work.

**Comment by lukaszkaiser** [comment]
I'm curious, why is this a problem? I always print things with `tf.Print`, fetching them back from a session looks like a lot of work. Less than `tf.contrib.Experiment`, I admit it's annoying at times (and I'm ok if you have a PR restructuring it), but I don't see how it helps debugging.

**Comment by rsepassi** [comment]
We've also added support for the [TF Debugger](https://www.tensorflow.org/programmers_guide/debugger) in latest release. Between that and `tf.Print` hopefully you can debug your models effectively.

**Comment by rsepassi** [comment]
Oh, sorry, to use the debugger add the `--tfdbg` flag to `t2t-trainer`.
