### ISSUE TITLE
Something about your paper

### ISSUE THREAD

**Issue by mfxss** [tensorflow/tensor2tensor#1236]
Hi,
If using this model to do seq2seq tasks, such as translation. What's the output embedding in figure 1? Such that we can't input the whole sentence to the decoder like what encoder do. Is it just like lstm that we get the first translated word and input it to the decoder as output embedding? And the output embedding matrix become larger and larger?
Thanks!

**Comment by lukaszkaiser** [comment]
You are correct, the output embedding is the same as input embedding, it's just features["targets"] in our code. Please reserve these issues though for code and related stuff, not general questions.
