### ISSUE TITLE
How can i set gpu device like gpu:2?

### ISSUE THREAD

**Issue by zepen** [tensorflow/tensor2tensor#1237]
### Description
i have four gpu, but i only use singe. So i must set device but i can't find this params for set gpu devices, just set gpu numbers. Seem hparams='datashard_devices="gpu:2"' is not working.
And what should i do?
...

**Comment by mehmedes** [comment]
You can specify the gpu you'd like to use by setting ```UDA_VISIBLE_DEVICES``` before calling ```t2t-trainer```
By running ```CUDA_VISIBLE_DEVICES=2 t2t-trainer``` you'd exclusively train on your third gpu.

**Comment by zepen** [comment]
i do this on the jupyter and seem it's not work.
![image](https://user-images.githubusercontent.com/18568380/48754916-6cf1bc80-ecce-11e8-8740-945273bd440d.png)
![image](https://user-images.githubusercontent.com/18568380/48754938-84c94080-ecce-11e8-9bb9-6ea631db2fa1.png)

![image](https://user-images.githubusercontent.com/18568380/48754951-914d9900-ecce-11e8-9c44-39c19212b1da.png)

![image](https://user-images.githubusercontent.com/18568380/48754963-9c082e00-ecce-11e8-8da4-475f58907bb3.png)

And it's show gpu:0 is used, what' s wrong? My gpu is Tesla K80.

**Comment by mehmedes** [comment]
I think Tensorflows automatically defines the gpu names starting with 0. So, even though you're actually using your third gpu, Tensorflow names it gpu:0.
To check which gpu is being used, run ```nvidia-smi```. This will show the current status of your gpus.

**Comment by zepen** [comment]
You're right. When I run nvidia-smi and check the gpu is used, my program actually running using third gpu. Thanks for your help!
