### ISSUE TITLE
The training data "commoncrawl.de-en" does't seem right

### ISSUE THREAD

**Issue by kngxscn** [tensorflow/tensor2tensor#1238]
The text in two red boxes have no relationship.
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/4049156/48811164-8266f500-ed67-11e8-8d41-c029b4a15d8a.png">

**Comment by martinpopel** [comment]
Yes, this is an example of "noisy training data". All the reported en-de results with T2T Transformer (including Attention Is All You Need) train on this data without any filtering and the NMT results are quite OK. So you can close this issue and don't worry about it.

Of course, a proper filtering of noisy training data may result in even better results. In this case a simple language identification would filter these three English sentences from the German data.
However, there are many more strange sentence pairs in CommonCrawl (and ParaCrawl). There are many parallel-data filtering techniques, e.g. [Dual Conditional Cross-Entropy Filtering](http://www.statmt.org/wmt18/pdf/WMT106.pdf), which is the winner of the [WMT 2018 Shared Task on Parallel Corpus Filtering](http://www.statmt.org/wmt18/pdf/WMT081.pdf).

**Comment by kngxscn** [comment]
Thank you so much for your answer. I learned a lot.
