### ISSUE TITLE
Normalizing dates, numbers using t2t

### ISSUE THREAD

**Issue by aleksas** [tensorflow/tensor2tensor#1243]
### Question
I want to train text normalizer (date, abreviation, number - to expanded text representation) to use in speach synthesis for lithuanian language.
Should it be possible to use transformer to normalize numbers (digit to word representation)?
Would default subword text tokenizer deal with numbers by default?
Or is this a wrong path altogether?

**Comment by afrozenator** [comment]
This should be doable. Subword tokenizer should work.

Something similar was done in an assignment in this course - https://www.coursera.org/learn/nlp-sequence-models

Closing this for now.
