### ISSUE TITLE
Identical branches in trainer_utils.py?

### ISSUE THREAD

**Issue by vthorsteinsson** [tensorflow/tensor2tensor#126]
Is it just me or are the two branches of this `if` statement in `trainer_utils.py` (around line 600) effectively identical? Both seem to enumerate through `result_iter`, they just decode the elements in two slightly different ways with the same result. If the first branch is intended to be an endless loop, a `while True:` needs to be added.

```
    if FLAGS.decode_endless:
      tf.logging.info("Warning: Decoding endlessly")
      for j, result in enumerate(result_iter):
        inputs, targets, outputs = (result["inputs"], result["targets"],
                                    result["outputs"])
        if FLAGS.decode_return_beams:
          output_beams = np.split(outputs, FLAGS.decode_beam_size, axis=0)
          for k, beam in enumerate(output_beams):
            tf.logging.info("BEAM %d:" % k)
            log_fn(inputs, targets, beam, problem, j)
        else:
          log_fn(inputs, targets, outputs, problem, j)
    else:
      for j, (inputs, targets, outputs) in enumerate(
          zip(result_iter["inputs"], result_iter["targets"], result_iter[
              "outputs"])):
        if FLAGS.decode_return_beams:
          output_beams = np.split(outputs, FLAGS.decode_beam_size, axis=0)
          for k, beam in enumerate(output_beams):
            tf.logging.info("BEAM %d:" % k)
            log_fn(inputs, targets, beam, problem, j)
        else:
          log_fn(inputs, targets, outputs, problem, j)

```

**Comment by rsepassi** [comment]
overall i think the decode code is overly complicated, but i think what's happening here is that the result_iter in the decode_endless branch is a bit different (look above when the result_iter is created) such that it yields an endless stream of results whereas in the other branch, result_iter is not actually an iterator but a set of results. please edit/comment liberally in the code if you'd like.

**Comment by lukaszkaiser** [comment]
As a more general comment: I believe we should split `trainer_utils` into `training_utils` and `decoding_utils` and have a separate `t2t_decoder`. It's just that we haven't gotten to do that yet.
