### ISSUE TITLE
Question about batch_size in SpeechRecognitionProblem

### ISSUE THREAD

**Issue by stefan-falk** [tensorflow/tensor2tensor#1260]
I am kind of confused what `batch_size` means for the `SpeechRecognitionProblem`.

Looking at different hparam settings, `batch_size` ranges from 16 (`transformer_librispeech_v2`) to 6000000 (`transformer_librispeech_v1`).

Now, obviously there are several other parameters which determine the final size of a batch, but in any case I do not see how a size of 6000000 works out.

At this point, I am not even sure how large _one sample_ actually is. I know we're using MFCC features [80, 3, length]

In `problem.py`I can see that `max_input_seq_length` determines the maximum length of the input which means that [80, 3, 1650] of float32 gives 1.51 MB _per sample_.

```python
# problem.py
def preprocess_example_common(example, hparams, mode):
  """Preprocessing steps common to all models."""
  if hparams.max_input_seq_length > 0:
    example["inputs"] = example["inputs"][:hparams.max_input_seq_length]
  # ..
```

Now, a `batch_size` of 6000000, as in `transformer_librispeech_v1` would result in ~8851 GB for a single batch which is obviously very unlikely to be correct.

This does confuse me a little bit and I was hoping somebody could show me how the actual size of one batch can be calculated.

**Comment by vergilus** [comment]
batch_size only involves frames (seq_len).
In ASR, the MCFF results are equivalent to the embedding tensor for text problems, thus the batch_scheme takes only the total amount of examples seq_len (src+trg+ and so on) as the maximum token count.

**Comment by stefan-falk** [comment]
@vergilus Hi!

Thanks for the answer. So what the network sees are 25 ms frames? I think you mean MFCC (not MCFF), right?

I don't see that there are actually MFCC features calculated. As far as I can see the network gets the filtered spectrum of the signal, but not the Mel coefficients ([see here](https://github.com/tensorflow/tensor2tensor/blob/v1.11.0/tensor2tensor/data_generators/speech_recognition.py#L99)).

But that's still not working out for me:

16000 * 0.025 = 400 ... length of a frame
80*3*400*4 = 96000*4 
=> 375 kb for one frame (sample)

6000000*375/(1024^2) = 2145 GB

which is still way too much. 

What am I seeing wrong here?

**Comment by stefan-falk** [comment]
Okay, I think I got it now. So.. it's actually 

6000000 / 1650 = 3636 ... batch_size/max_sequence_length -> the maximum number of "samples"

3636 * 80 * 3 * 4b * 1650 = 5.36 GB


So 6000000 batch_size can be interpreted as "number of 25ms frames" which is basically "one token" of that sequence.

I think that should be it?

**Comment by vergilus** [comment]
@stefan-falk exactly.

**Comment by stefan-falk** [comment]
@vergilus Awesome. Thanks again for your help. I'm closing this issue :)
