### ISSUE TITLE
How to create new problem for speech recognition

### ISSUE THREAD

**Issue by manuel3265** [tensorflow/tensor2tensor#1279]
### Description
how do I create a new problem to train my own model, but that is for speech recognition, according to how they do it in this link: https://tensorflow.github.io/tensor2tensor/new_problem.html
...

### Environment information

```
OS: <your answer here>

$ pip freeze | grep tensor
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
```

**Comment by afrozenator** [comment]
Can you take a look here -- https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/librispeech.py

Closing this for now, feel free to reopen if that doesn't provide a well enough guide
