### ISSUE TITLE
Model decodes different sentences identically

### ISSUE THREAD

**Issue by jackperkins98** [tensorflow/tensor2tensor#130]
I am attempting to create a part-of-speech/prepositional super-sense tagger using the readme walk through. I created my own data generator/problem and let training run for about 6500 steps on transformer_base. I put a few sentences in the decode file and run the walk through decode lines. Each sentence is decoded into the same set of tags.

INFO:tensorflow:Restoring parameters from /root/t2t_train/sequence_tagger/transformer-transformer_base/model.ckpt-6721
INFO:tensorflow:Inference results INPUT: Michael Jordan played basketball for the Chicago Bulls.
INFO:tensorflow:Inference results OUTPUT: O O-GROUP O-Function O-social O O-GROUP B-COMMUNICATION Ī O-Co-Agent O O-PERSON O-Possessor O O-GROUP O
INFO:tensorflow:Inference results INPUT: I killed Godzilla with a laser beam.
INFO:tensorflow:Inference results OUTPUT: O O-GROUP O-Function O-social O O-GROUP B-COMMUNICATION Ī O-Co-Agent O O-PERSON O-Possessor O O-GROUP O
INFO:tensorflow:Inference results INPUT: Bob ate pizza in the park.
INFO:tensorflow:Inference results OUTPUT: O O-GROUP O-Function O-social O O-GROUP B-COMMUNICATION Ī O-Co-Agent O O-PERSON O-Possessor O O-GROUP O
INFO:tensorflow:Writing decodes into /root/t2t_data/decode_this.txt.transformer.transformer_base.beam8.alpha2.0.decodes

The decoded line doesn't match up with any of the inputs. The model was getting a checkpoint accuracy of around 80% which makes me think there's just something going wonky with the decoder. If I re-run the decode line, it outputs a different decoded sentence (still doesn't match up with any inputs). A similar issue was posted and closed stating that T2T 1.0.11 fixed this but it did not in my case. 

Thanks in advance!

**Comment by ZhenYangIACAS** [comment]
@jackperkins98  my decoding also have some problem. T2T.1.0.9.  The total loss is 2.1 but BLEU reaches only at 12.42 which is too low. I find that the ratio is 2.002, which is too high.
BLEU = 12.42, 29.1/15.3/9.2/5.8 (BP=1.000, ratio=2.002, hyp_len=126937, ref_len=63412)

**Comment by lukaszkaiser** [comment]
It's very hard to reproduce your issue if you're using a private data-set or an older version of T2T. Can you see the issue with a new version of T2T, or add your data-set? Also, I believe 6500 steps is simply not enough to train, esp. with `warmup_steps` set to a high number. Could you try at least 20-30k steps? I'm closing this for now as unreproducible, but please reopen if there's a way for us to reproduce.

**Comment by benjamincohen1** [comment]
Hey - have you had any luck with this?  I've got a transformer model doing the same thing after ~27,000 iterations

**Comment by jackperkins98** [comment]
It was just the amount of steps. After 30k it worked fine. Depending on how
bug your data set is, you probably just need more steps.
