### ISSUE TITLE
problem about translateEnZhWmt8k , i exported trained model and deploy it on tensorflow model server , the effiency is very bad ;  my client is same as t2t-query . who can help me ? thanks very much !!

### ISSUE THREAD

**Issue by alchemistlee** [tensorflow/tensor2tensor#1384]
### Description

problem about translateEnZhWmt8k , i exported trained model and deploy it on tensorflow model server , the effiency is very bad ;  my client is same as t2t-query . who can help me ? thanks very much !!

### Environment information

```
OS: <your answer here>

$ pip freeze | grep tensor
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
```

**Comment by Mr-wang2016** [comment]
Hi,do you mean the decoding speed?are you on cpu or gpu?when i use tensorflow model server and t2t-query-server on a cpu,the decode speed is unstable and not fast. and i am not very satisfied with the speed of gpu decoding too.
I don't know where the problem is···

**Comment by alchemistlee** [comment]
> Hi,do you mean the decoding speed?are you on cpu or gpu?when i use tensorflow model server and t2t-query-server on a cpu,the decode speed is unstable and not fast. and i am not very satisfied with the speed of gpu decoding too.
> I don't know where the problem is···
 i find that the most slowly part is calculate on tf model server , and i just deploy my model on one machine

**Comment by lkluo** [comment]
You said that the decoding is not sufficient, can you provide more information, e.g., how long it takes to decode one sentence (of average length)? 

You may also compare the decoding speed between with tf-server and without, and see if there is significant difference.

**Comment by lkluo** [comment]
> @lkluo Hi，when i decode a sentence which has 50 words, tf-server(compile with avx2 and fma) takes 6 sec(average time), and t2t-decoder.py only take 2 sec(average time).they all run on a cpu machine.
> when i use tf-server,i use t2t-query-server as a client,i found the code 'response = stub.Predict(request, timeout_secs)' in function 'make_grpc_request_fn()' runs very slow and take almost all the time.so may grpc in my machine have a problem?
> Any Suggestions or attempts will be appreciated.thank you!!

Sorry, I don't know much about grpc. According to your description, it might be related. Also check on your tensorFlow and tf-serving versions, which are better to be the same.

**Comment by lukaszkaiser** [comment]
Is that resolved now? Does updating TF help? I'll close for now, but please reopen if problems persist!

**Comment by XiangZhu0718** [comment]
> @lkluo Hi，when i decode a sentence which has 50 words, tf-server(compile with avx2 and fma) takes 6 sec(average time), and t2t-decoder.py only take 2 sec(average time).they all run on a cpu machine.
> when i use tf-server,i use t2t-query-server as a client,i found the code 'response = stub.Predict(request, timeout_secs)' in function 'make_grpc_request_fn()' runs very slow and take almost all the time.so may grpc in my machine have a problem?
> Any Suggestions or attempts will be appreciated.thank you!!



> @lkluo Hi，when i decode a sentence which has 50 words, tf-server(compile with avx2 and fma) takes 6 sec(average time), and t2t-decoder.py only take 2 sec(average time).they all run on a cpu machine.
> when i use tf-server,i use t2t-query-server as a client,i found the code 'response = stub.Predict(request, timeout_secs)' in function 'make_grpc_request_fn()' runs very slow and take almost all the time.so may grpc in my machine have a problem?
> Any Suggestions or attempts will be appreciated.thank you!!

Hi,have you find the reason for low effiency ?
