### ISSUE TITLE
Propose to contribute documentation on use and design of MultiProblem

### ISSUE THREAD

**Issue by cwbeitel** [tensorflow/tensor2tensor#1394]
The new MultiProblem class and instances are really cool!!

I'm interested in writing some documentation on MultiProblem both regarding use and design. In my case towards understanding how to extend it to support multiple input modalities (audio and video).

Checking whether this isn't something the authors would prefer to do themselves.

/cc @rsepassi @lukaszkaiser

**Comment by afrozenator** [comment]
Hi Christopher - Please give it a shot!

Regards
