### ISSUE TITLE
unicode error when using python 3

### ISSUE THREAD

**Issue by yelkurdi** [tensorflow/tensor2tensor#142]
Encountered an error related to using 'unicode' in python 3. My environment uses python 3 anaconda with tensorflow installed using virtualenv.
 
  File "...tensorflow-gpu/lib/python3.6/site-packages/tensor2tensor/data_generators/text_encoder.py", line 476, in _escape_token
    assert isinstance(token, unicode)
NameError: name 'unicode' is not defined

Seems to be fixed by replacing the line with:
      if PY2 :
          assert isinstance(token, unicode)
      else :
          assert isinstance(token, str)

**Comment by lukaszkaiser** [comment]
This is hopefully corrected in 1.0.14, thanks for reporting! (And of course please reopen if you see it again.)
