### ISSUE TITLE
output the n-best translation  

### ISSUE THREAD

**Issue by shiny1022** [tensorflow/tensor2tensor#1427]
### Description
I use the universal transformer to train the EN-DE translation system. Now I want to output the n-best translation result.  How should I set the decoding parameters?

**Comment by xiaoqiangkx** [comment]
```
python ${T2T_BIN_ROOT}/t2t-decoder \
  --data_dir=$DATA_DIR \
  --problem=$PROBLEM \
  --model=transformer \
  --hparams_set=transformer_base \
  --output_dir=$OUTPUT_DIR \
  --decode_hparams="beam_size=$BEAM_SIZE,alpha=$ALPHA,return_beams=True" \
  --decode_from_file=$DECODE_FILE \
  --decode_to_file=translation.en
```

use **return_beams=True**

**Comment by shiny1022** [comment]
@xiaoqiangkx thanks for your reply . It's useful and I got the 5-best lists. But I encounter some problems.The output translation are written into one file. It's difficult to spilt it  into 5 candidate translations. Could you give me some help?

**Comment by shiny1022** [comment]
@xiaoqiangkx I have found a way to solve this problem.Thank you so much!

**Comment by sugiyamath** [comment]
@shiny1022 Could you please describe your solution of splitting them?

**Comment by sugiyamath** [comment]
It seems that the n-best output is separated as tab splitter. It is easy to separate them.
