### ISSUE TITLE
NotFoundError parsing_train.text

### ISSUE THREAD

**Issue by lapolonio** [tensorflow/tensor2tensor#143]
When running the similar example to README I get an error that parsing_train.text is missing. How is it generated or is it downloaded? It's not clear in the code.

```
Traceback (most recent call last):
  File "/usr/local/bin/t2t-datagen", line 375, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-datagen", line 359, in main
    FLAGS.data_dir, FLAGS.num_shards, FLAGS.max_cases)
  File "projects/git/tensor2tensor/tensor2tensor/data_generators/generator_utils.py", line 113, in generate_files
    for case in generator:
  File "projects/git/tensor2tensor/tensor2tensor/data_generators/wmt.py", line 58, in character_generator
    source, target = source_file.readline(), target_file.readline()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 176, in readline
    self._preread_check()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/t2t_datagen/parsing_train.text
```

```
PROBLEM=wmt_parsing_tokens_8k
MODEL=transformer
HPARAMS=transformer_base

DATA_DIR=$HOME/t2t_data
TMP_DIR=/tmp/t2t_datagen
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

# Generate data
t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --num_shards=100 \
  --problem=$PROBLEM
```

**Comment by lukaszkaiser** [comment]
To generate parsing data, you need to get the Penn Treebank from LDC: https://catalog.ldc.upenn.edu/ldc99t42

Then please use the newest version of tensor2tensor: it requires the .trees file (in LDC tree format, like (S (NP (PRP he) ...)) or such) to be in your tmp directory in a path specified by `--parsing_path`.

**Comment by lapolonio** [comment]
I just tried the download again and it worked. I didn't use PTB-3

**Comment by lukaszkaiser** [comment]
Thanks!

**Comment by agemagician** [comment]
@lapolonio which dataset did you use ?
Could you please share the download link if possible?

**Comment by lapolonio** [comment]
I just cleaned the downloaded file and executed the download again.

**Comment by agemagician** [comment]
@lapolonio   Thanks for your reply. I was asking for a download link for the Penn tree bank you used. I will be grateful if you can share it.

**Comment by lapolonio** [comment]
@agemagician Inside the ptb.py generator you will find the link: `PTB_URL = "http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgz"`
from https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/ptb.py#L35

**Comment by agemagician** [comment]
@lapolonio  Thanks a lot :)

**Comment by martinpopel** [comment]
Unfortunately, [PennTB](https://catalog.ldc.upenn.edu/ldc99t42) is not free, so no one can legally provide a download link publicly here.
If you are affiliated with any LDC member (most universities), contact them.

> Inside the ptb.py generator you will find the link: PTB_URL = "http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgz"

This contains only the plain text of PTB, not part-of-speech tags and the constituency parse trees (in format like `(S (NP (PRP he) ...))`).

There are many dependency treebanks available for free, most notably [Universal Dependencies](http://universaldependencies.org/) with 70 treebanks for 50 languages.
It would be nice to add a support for dependency parsing to Tensor2Tensor, e.g. following the [CoNLL2017 winner parser](http://universaldependencies.org/conll17/proceedings/pdf/K17-3002.pdf).
I plan to look at it.

**Comment by lukaszkaiser** [comment]
It would be wonderful to have Universal Dependencies as a data-set in T2T! Please make a PR :).
