### ISSUE TITLE
Tensor2tensor transformer division by zero error

### ISSUE THREAD

**Issue by Erra-Ernesto** [tensorflow/tensor2tensor#1437]
I'm very new to Tensor2Tensor and am trying to use Transformer model to decode a english text in italian text. For now i have training the model on Google Colab. Now i want translate a file in my local machine (with Windows 7) with checkpoints that i have obtained on Colab e I have download in local machine. I have execute on cmd prompt the follow code

C:\Users\My-name>python /Users/My-name/TranslatorApp/t2t_app/tensor2tensor/bin/t
2t-decoder --t2t_usr_dir=/Users/My-name/TranslatorApp/t2t_app/usrdir --data_dir=
/Users/My-name/TranslatorApp/t2t_data_enit32k --problem=translate_enit_wmt32k --
model=transformer --hparams_set=transformer_base_single_gpu --output_dir=/Users/
My-name/TranslatorApp/checkpoint/model_checkpoint --decode_hparams="beam_size=4,
alpha=0.6" --decode_from_file=/Users/My-name/da_tradurre.en --decode_to_file=/Us
ers/My-name/tradotto.it

And I have how response an error of division by zero, as shown below:

INFO:tensorflow:Importing user module usrdir from path C:\Users\My-name\Translat
orApp\t2t_app
WARNING:tensorflow:From C:\Users\My-name\Anaconda3\lib\site-packages\tensor2tens
or\utils\trainer_lib.py:198: RunConfig.__init__ (from tensorflow.contrib.learn.p
ython.learn.estimators.run_config) is deprecated and will be removed in a future
 version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
INFO:tensorflow:schedule=continuous_train_and_eval
INFO:tensorflow:worker_gpu=1
INFO:tensorflow:sync=False
WARNING:tensorflow:Schedule=continuous_train_and_eval. Assuming that training is
 running on a single machine.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:ps_devices: ['gpu:0']
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec
': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000000001D3E5B
A8>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environm
ent': 'local', '_is_chief': True, '_evaluation_master': '', '_train_distribute':
 None, '_eval_distribute': None, '_device_fn': None, '_tf_config': gpu_options {

  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs':
 None, '_log_step_count_steps': 100, '_protocol': None, '_session_config': gpu_o
ptions {
  per_process_gpu_memory_fraction: 0.95
}
allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
, '_save_checkpoints_steps': 1000, '_keep_checkpoint_max': 20, '_keep_checkpoint
_every_n_hours': 10000, '_model_dir': '/Users/My-name/TranslatorApp/checkpoint/m
odel_checkpoint', 'use_tpu': False, 't2t_device_info': {'num_async_replicas': 1}
, 'data_parallelism': <tensor2tensor.utils.expert_utils.Parallelism object at 0x
000000001D3E5C18>}
WARNING:tensorflow:Estimator's model_fn (<function T2TModel.make_estimator_model
_fn.<locals>.wrapping_model_fn at 0x00000000190E6840>) includes params argument,
 but params are not passed to Estimator.
INFO:tensorflow:decode_hp.batch_size not specified; default=32
INFO:tensorflow:Performing decoding from a file.
INFO:tensorflow:Getting sorted inputs
INFO:tensorflow: batch 0
INFO:tensorflow:Elapsed Time: 0.06900
Traceback (most recent call last):
  File "/Users/My-name/TranslatorApp/t2t_app/tensor2tensor/bin/t2t-decoder", lin
e 17, in <module>
    tf.app.run()
  File "C:\Users\My-name\Anaconda3\lib\site-packages\tensorflow\python\platform\
app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/My-name/TranslatorApp/t2t_app/tensor2tensor/bin/t2t-decoder", lin
e 12, in main
    t2t_decoder.main(argv)
  File "C:\Users\My-name\Anaconda3\lib\site-packages\tensor2tensor\bin\t2t_decod
er.py", line 190, in main
    decode(estimator, hp, decode_hp)
  File "C:\Users\My-name\Anaconda3\lib\site-packages\tensor2tensor\bin\t2t_decod
er.py", line 90, in decode
    checkpoint_path=FLAGS.checkpoint_path)
  File "C:\Users\My-name\Anaconda3\lib\site-packages\tensor2tensor\utils\decodin
g.py", line 412, in decode_from_file
    (total_time_per_step / total_cnt))
ZeroDivisionError: division by zero

Please can you help me to solve this error?

**Comment by mirr-digiters** [comment]
Hi @Erra-Ernesto. Did you manage to solve the issue. I'm having the same ZeroDivisionError.
