### ISSUE TITLE
Attention visualization

### ISSUE THREAD

**Issue by stefan-it** [tensorflow/tensor2tensor#147]
Hi,

in the appendix of [Attention Is All You Need](https://arxiv.org/pdf/1706.03762.pdf) some very nice visualizations of the attention mechanism can be seen.

How can I create those visualizations for my own dataset/language pair? 

Would be great if the authors can give some hints :)

**Comment by lukaszkaiser** [comment]
LLion, who wrote the scripts to do the visualizations, is on vacation this week. I'll leave this open and ping when he's back.

**Comment by stefan-it** [comment]
@lukaszkaiser That would be great :)

**Comment by vishalnus** [comment]
@lukaszkaiser I too will wait for this. Thanks very much for the guidance

**Comment by rsepassi** [comment]
It seems that `dot_product_attention` (which is used in `multihead_attention` which is used in the `Transformer`) calls `attention_image_summary` which adds an image summary op, which should be written out to TensorBoard during training. Have you checked the image summaries tab in TensorBoard during training?

**Comment by rsepassi** [comment]
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/layers/common_attention.py#L285

**Comment by stefan-it** [comment]
I meant these kind of visualizations:

![visu](https://user-images.githubusercontent.com/20651387/29170314-3f7faa8e-7dd8-11e7-9fb1-eea3bc0534d8.png)

:)

**Comment by lukaszkaiser** [comment]
An iPython notebook with our viz code is included in the new release 1.2.0, give it a try!
