### ISSUE TITLE
code for "Model-Based Reinforcement Learning for Atari"

### ISSUE THREAD

**Issue by daiwk** [tensorflow/tensor2tensor#1483]
where can i find the code for "Model-Based Reinforcement Learning for Atari" https://arxiv.org/pdf/1903.00374.pdf
which said the code is in https://github.com/tensorflow/tensor2tensor/tree/master/tensor2tensor/rl

**Comment by afrozenator** [comment]
Can you see if this helps - https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/rl/README.md
