### ISSUE TITLE
Tensorboard Support?

### ISSUE THREAD

**Issue by jsawruk** [tensorflow/tensor2tensor#15]
Does the trainer currently write out logs for Tensorboard? I looked through the code in utils/trainer_utils.py, and while I see calls to `tf.summary.scalar`, I don't see a call to `tf.summary.FileWriter`.

If it does support Tensorboard, how do I configure it?
If not, I'll start working on a pull request tomorrow to implement this.

**Comment by lukaszkaiser** [comment]
Yes, the trainer writes to $TRAIN_DIR. Run tensorboard like this:
tensorboard --logdir $TRAIN_DIR --host localhost --port 2222

Then, I see an overview of the training process:
![readme_train_tensorboard](https://user-images.githubusercontent.com/684901/27415724-6ebf8d4c-56bd-11e7-925a-766923ceea26.png)

**Comment by jsawruk** [comment]
Thanks!

**Comment by liesun1994** [comment]
wooooooooow , nice features !

**Comment by chuanmingliu** [comment]
Thanks!
