### ISSUE TITLE
May I ask a simple question: what is the difference/relation between neg_log_perplexity and perplexity?

### ISSUE THREAD

**Issue by guotong1988** [tensorflow/tensor2tensor#1502]
Thank you very much.

**Comment by guotong1988** [comment]
It seems `perplexity = e^loss`

**Comment by nmoenning** [comment]
@guotong1988 Yes you are correct. The reason most implementations actually report log (or ln) perplexity is that computationally it can very quickly cause an overflow if something goes wrong. It would return with an Inf or NaN at some point in your the code. This can be difficult to track. Especially in tensorflow where it would usually return the NaN or Inf at runtime, not while you construct the computation graph.
