### ISSUE TITLE
Could not find a version that satisfies the requirement jaxlib.

### ISSUE THREAD

**Issue by KeqiH** [tensorflow/tensor2tensor#1507]
### Description
I tried to install tensor2tensor using "pip install tensor2tensor", but there is a problem that :"Could not find a version that satisfies the requirement jaxlib."
...

### Environment information
win10
python3.6.8 64bit
tensorflow-gpu-1.4.0
CUDA 8.0
cudnn 6.0
```
OS: <your answer here>

$ pip freeze | grep tensor
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
Collecting jaxlib (from tensor2tensor)
  Could not find a version that satisfies the requirement jaxlib (from tensor2tensor) (from versions: )
No matching distribution found for jaxlib (from tensor2tensor)
```

**Comment by dlfelps** [comment]
Hi, I just wanted to add that I am having the same bug. It seems that T2T was updated 29 days ago to require jax (and jaxlib) see [commit](https://github.com/tensorflow/tensor2tensor/commit/616421a12d842ae2d689d248249d2b5db0f2e0d3#diff-2eeaed663bd0d25b7e608891384b7298)

It also appears that Jax is not supported on Windows [see issue](https://github.com/google/jax/issues/438)

So it looks like we Windows users are out of luck.

**Comment by cyborg527** [comment]
@dlfelps well couldn't you just use the version from before 29 days ago? It's out of date yeah but at least it would work on Windows

**Comment by KeqiH** [comment]
@cyborg527  Thank you. I just want to know how the Transformer works, so the last version is pretty enough.

**Comment by afrozenator** [comment]
Sorry, will fix this shortly. But till that time maybe you can install from source by modifying the setup.py by commenting out those lines?

**Comment by afrozenator** [comment]
Can you try now with the latest version on pip 1.13.2? I'll close this for now, please feel free to re-open. Thanks!
