### ISSUE TITLE
Documentation Mismatch for `get_input_fn`

### ISSUE THREAD

**Issue by belph** [tensorflow/tensor2tensor#152]
In `trainer_utils.py`, [this docstring][get_input_fn_doc] says that callers can pass `None` for `data_file_pattern` in order to get placeholders back, but doing so causes [this line][err_line] to raise an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pblair/t2t-stuff/venv-t2t-py3/lib/python3.4/site-packages/tensor2tensor/utils/trainer_utils.py", line 1035, in input_fn
    problem_count, batches = len(data_file_patterns), []
TypeError: object of type 'NoneType' has no len()
```

[get_input_fn_doc]: https://github.com/tensorflow/tensor2tensor/blob/006ecb50f6b63a18e0665d7d97869f95a3003dc1/tensor2tensor/utils/trainer_utils.py#L983-L984
[err_line]: https://github.com/tensorflow/tensor2tensor/blob/006ecb50f6b63a18e0665d7d97869f95a3003dc1/tensor2tensor/utils/trainer_utils.py#L1020

**Comment by rsepassi** [comment]
Thanks for reporting this! Fix should go out in the next release. Please do let us know if you run into any other issues.

**Comment by rsepassi** [comment]
Believe this has been fixed. Please do reopen if you run into problems.
