### ISSUE TITLE
Is there a good example tutorial on how to use Tensor2Tensor?

### ISSUE THREAD

**Issue by zqs01** [tensorflow/tensor2tensor#1530]
Is there a good example tutorial on how to use Tensor2Tensor?

**Comment by afrozenator** [comment]
Can you see if https://colab.sandbox.google.com/github/tensorflow/tensor2tensor/blob/master/tensor2tensor/notebooks/hello_t2t.ipynb works for you?

Or maybe the other notebooks here which can be accessed the same way:

https://github.com/tensorflow/tensor2tensor/tree/master/tensor2tensor/notebooks
