### ISSUE TITLE
tf.session 

### ISSUE THREAD

**Issue by manuel3265** [tensorflow/tensor2tensor#1533]
### Description
I would like to know, if you could tell me, in what part of the code, the session is created in the training part. that is, when executing:

```
t2t-trainer --model=transformer  --hparams_set=transformer_librispeech_tpu \
  --problem=librispeech_train_full_test_clean \
```

, where the session (tf.session) is created. I need to do a test to change from:

```with tf.Session() as sess: ``` to  ``` sess = tf.Session() ```
...

I would thank you a lot.

**Comment by Mr-wang2016** [comment]
t2t use Estimator api in tensorflow, so session is created in tensorflow code, not in t2t.
