### ISSUE TITLE
How to train from self-generated problem data

### ISSUE THREAD

**Issue by aviczhl2** [tensorflow/tensor2tensor#157]
When I followed the generation step to get a new problem (length) data generator, and successfully generated some data, I always find it error when I try to train it using the same code as the example wmt-case training code but just modified the problem name. Is there a guidance about how to train new problems?

**Comment by aviczhl2** [comment]
It seems that I shall choose a proper hyper parameter set from PROBLEM_HPARAMS_MAP, is there any guidance here?

**Comment by rsepassi** [comment]
Please try adding a problem with the new method (subclassing `Problem` and registering it with `@registry.register_problem`). See wmt.py or algorithmic.py for examples.

**Comment by rsepassi** [comment]
Closing for now. Please do reopen if you run into issues.
