### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'sox': 'sox'

### ISSUE THREAD

**Issue by Victor-Almeida** [tensorflow/tensor2tensor#1571]
### Description

When I try to run the librispeech problem on Google Colab I get the following error : 
```
FileNotFoundError                         Traceback (most recent call last)

<ipython-input-26-445f84cca4ca> in <module>()
      1 t2t_problem = problems.problem(PROBLEM)
----> 2 t2t_problem.generate_data(DATA_DIR, TMP_DIR)

6 frames

/usr/lib/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1342                         if errno_num == errno.ENOENT:
   1343                             err_msg += ': ' + repr(err_filename)
-> 1344                     raise child_exception_type(errno_num, err_msg, err_filename)
   1345                 raise child_exception_type(err_msg)
   1346 

FileNotFoundError: [Errno 2] No such file or directory: 'sox': 'sox'
```

Here's the code : 
```
from tensor2tensor.utils import registry
from tensor2tensor import models
from tensor2tensor import problems

from google.colab import drive
drive.mount('/content/gdrive')

PROBLEM = 'librispeech_clean'
TMP_DIR = '/content/gdrive/My Drive/T2T tests/tmp_dir/' # Where data files from internet stored
DATA_DIR = '/content/gdrive/My Drive/T2T tests/data_dir/' # Where pre-prcessed data is stored
t2t_problem = problems.problem(PROBLEM)
t2t_problem.generate_data(DATA_DIR, TMP_DIR) 
```

The error message is the same for both Python 2 and Python 3.

**Comment by Victor-Almeida** [comment]
Solved. Just had to download the _sox_ library with `!apt -qq install -y sox`.

**Comment by Alaaaldein** [comment]
When I try to load my dataset and do some peprocessing on Google Colab I get the following error:

FileNotFoundError                         Traceback (most recent call last)

<ipython-input-27-4ac5737bcd0a> in <module>()
      6 
      7 for i in listing:
----> 8   im = Image.open(path1 + '\\' + i)
      9   img = im.resize((img_rows,img_cols))
     10   gray = img.convert('L')

/usr/local/lib/python3.6/dist-packages/PIL/Image.py in open(fp, mode)
   2807 
   2808     if filename:
-> 2809         fp = builtins.open(filename, "rb")
   2810         exclusive_fp = True
   2811 

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/Zakria/input_data1\\scratches_2.jpg'




Here's the code :

path1 = '/content/drive/My Drive/Zakria/input_data1'    #path of folder of images
path2 = '/content/drive/My Drive/Zakria/input_data_resized'  #path of folder to save images

listing = os.listdir(path1)
num_samples=size(listing)
print (num_samples)

img_rows, img_cols = 200, 200

for i in listing:
  im = Image.open(path1 + '\\' + i)
  img = im.resize((img_rows,img_cols))
  gray = img.convert('L')
  gray.save(path2 +'\\' +  i, "JPEG")

imlist = os.listdir(path2)

**Comment by TatProg** [comment]
@Alaaaldein Better late than never ^_^

As you see, all paths in Google Colab uses only **'/'**
```
path1 = '/content/drive/My Drive/Zakria/input_data1' #path of folder of images
path2 = '/content/drive/My Drive/Zakria/input_data_resized' #path of folder to save images
```
But in your code, you add '\\' to your new created path. Just change on your 8th line **'\\' to '/'**. That's all.
```
6
7 for i in listing:
----> 8 im = Image.open(path1 + '\' + i)
9 img = im.resize((img_rows,img_cols))
10 gray = img.convert('L')
```
P.S. copy-paste code from Windows-working python scripts to Linux-working python scripts requires some attention, good luck;)
