### ISSUE TITLE
Error running decoder | pos=None,self_attention_type=dot_product_relative

### ISSUE THREAD

**Issue by mehmedes** [tensorflow/tensor2tensor#1584]
When running decoder with a model trained with ``` hparams.pos = None, 
hparams.self_attention_type = "dot_product_relative" ``` , the following error occurs:

```ValueError: Cannot use 'transformer/while/body/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/dot_product_attention_relative/attention' as input to 'Merge/MergeSummary' because 'transformer/while/body/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/dot_product_attention_relative/attention' is in a while loop.```

tensor2tensor==1.13.4
tensorflow-estimator==1.13.0
tensorflow-gpu==1.13.1

Python 2.7.15rc1

**Comment by mehmedes** [comment]
Using ```dot_product_relative_v2``` will work!

**Comment by phamthuonghai** [comment]
This quick fix will help if someone still wants to user v1 https://github.com/tensorflow/tensor2tensor/pull/1618/files

**Comment by Mr-wang2016** [comment]
Hi, i know dot_product_relative is based on the paper 'https://arxiv.org/pdf/1803.02155.pdf'.
And any papers on dot_product_relative_v2? or what is the difference between dot_product_relative and  dot_product_relative_v2?
thanks a lot!
