### ISSUE TITLE
Lack of LSTM(RNN)-CNN classification problem

### ISSUE THREAD

**Issue by yynil** [tensorflow/tensor2tensor#16]
For current problems, we have NMT problems and Image Classification problems. 
But it's lack of the LSTM-CNN's classification problems.
I've implemented a toy data set which will generate random sequences to represent people names.
Some are boys' names while others are girls.
If all names in the sequence are boys' names, it's classified as 1.
If all names in the sequence are girls' names, it's classified as 2.
Otherwise, it's classified as 3.
Now I'm training my toy dataset using the default Transformer model. 
Do you guys think it's good to pull this problem to the master?

**Comment by lukaszkaiser** [comment]
Sure, this sounds like a very nice algorithmic problem, to test the performance on exist/all kind of classification tasks. Would you like to make a PR in the data_generators/algorithmic.py?

**Comment by yynil** [comment]
No problem. Since my box(Tegra TX2) is still running the trainer, I'll make a PR after the training is done and verified well.

**Comment by lukaszkaiser** [comment]
Thanks! Closing this and waiting for your PR :).
