### ISSUE TITLE
Training MultiModel Algorithm for a new problem

### ISSUE THREAD

**Issue by agemagician** [tensorflow/tensor2tensor#161]
Hello,

This is not an issue, but a question.

Can we train the multi-model algorithm with a new problem rather than the 8 problems.
For example, text name entity recognition ?

If yes, then how and can we emerge it with the current 8 models?
If no, then why ? 

Best Regards,
Ahmed Elnaggar

**Comment by rsepassi** [comment]
You should be able to set `--problems=$PROB1-$PROB2-$PROB3` etc. (a dash-separated list of problem names).

**Comment by agemagician** [comment]
Thanks for your reply.

I understand how to train the multi-model algorithm with more than one problem, but this is not my question.

My question is can I train the multi-model with a new problem out of the predefined 8 problems.
Like train it with text name entity recognition or something else.

**Comment by dilipkk** [comment]
The models are defined independent of problems in tensor2tensor library, so you should  be able to use multimodel with new problems too.

**Comment by agemagician** [comment]
Thanks for your reply.

Did you tried that ?
Which model did you used ?
Which new problem did you train it with ?
What was the result ?

**Comment by rsepassi** [comment]
You can see all available problem names by running `t2t-datagen`. You should be able to mix any of those for the multimodel.

**Comment by rsepassi** [comment]
Closing. Please open a new issue if you find something off.
