### ISSUE TITLE
Framework error when attempting mixed precision training

### ISSUE THREAD

**Issue by ekuznetsov139** [tensorflow/tensor2tensor#1625]
I am attempting to use mixed precision (float16) training with transformer as described in #1362 using tensor2tensor 1.13.4. The problem is observed with tensorflow 1.13.1 and 1.14.0. Debian host with a Tesla V100 GPU.

Mixed precision is enabled by passing either  --hparams_set=transformer_fairseq_fp16_activation_big or explicitly --hparams weight_dtype=bfloat16,optimizer=Adafactor. 

In either case, I get a wall of warnings:
```

<...> common_layers.py:3494] Cast for training/gradients/AddN_77:0 may induce copy from '/device:GPU:0' to ''
<...>  common_layers.py:3494] Cast for training/gradients/AddN_78:0 may induce copy from '/device:GPU:0' to ''
<...>  common_layers.py:3494] Cast for training/gradients/AddN_79:0 may induce copy from '/device:GPU:0' to ''
<...>  common_layers.py:3494] Cast for training/gradients/AddN_80:0 may induce copy from '/device:GPU:0' to ''
<...>  common_layers.py:3494] Cast for training/gradients/AddN_81:0 may induce copy from '/device:GPU:0' to ''
<...>  common_layers.py:3494] Cast for training/gradients/AddN_82:0 may induce copy from '/device:GPU:0' to ''
<...>  common_layers.py:3494] Cast for training/gradients/AddN_83:0 may induce copy from '/device:GPU:0' to ''
```

The call trace for these goes to compute_gradients() in optimize.py
, which attempts to cast e.g.
`
Tensor("training/gradients/AddN_77:0", shape=(2048, 512), dtype=float32, device=/device:GPU:0) `

to type 
`
tf.Variable 'transformer/symbol_modality_32755_512/shared/weights_0:0' shape=(2048, 512) dtype=bfloat16`

I'm unclear as to whether this signifies a genuine problem or just a warning that some tensors are going to be sent onto the CPU to be cast to float16.

However, a bit later, I get this:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Multiple OpKernel registrations match NodeDef 'node transformer/parallel_0_5/transformer/transformer/body/encoder/attention_bias_to_padding/Less (defined at /home/aidev/.local/lib/python2.7/site-packages/tensor2tensor/layers/common_attention.py:965) ': 'op: "Less" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_BFLOAT16 } } }' and 'op: "Less" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_BFLOAT16 } } }'
	 [[node transformer/parallel_0_5/transformer/transformer/body/encoder/attention_bias_to_padding/Less (defined at /home/aidev/.local/lib/python2.7/site-packages/tensor2tensor/layers/common_attention.py:965) ]]
Caused by op u'transformer/parallel_0_5/transformer/transformer/body/encoder/attention_bias_to_padding/Less', defined at:
(snip)
 File "/home/aidev/.local/lib/python2.7/site-packages/tensor2tensor/utils/expert_utils.py", line 60, in decorated
    return f(*args, **kwargs)
  File "/home/aidev/.local/lib/python2.7/site-packages/tensor2tensor/layers/common_attention.py", line 965, in attention_bias_to_padding
    return tf.squeeze(cast_fn(tf.less(attention_bias, -1)), axis=[1, 2])
  File "/home/aidev/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4622, in less
    "Less", x=x, y=y, name=name)
  File "/home/aidev/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/aidev/.local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/aidev/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/aidev/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Multiple OpKernel registrations match NodeDef 'node transformer/parallel_0_5/transformer/transformer/body/encoder/attention_bias_to_padding/Less (defined at /home/aidev/.local/lib/python2.7/site-packages/tensor2tensor/layers/common_attention.py:965) ': 'op: "Less" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_BFLOAT16 } } }' and 'op: "Less" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_BFLOAT16 } } }'
	 [[node transformer/parallel_0_5/transformer/transformer/body/encoder/attention_bias_to_padding/Less (defined at /home/aidev/.local/lib/python2.7/site-packages/tensor2tensor/layers/common_attention.py:965) ]]

This was with tensorflow 1.13.1. With 1.14.0, the error is less verbose, though equally fatal:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Multiple OpKernel registrations match NodeDef 'node transformer/parallel_0_5/transformer/transformer/body/encoder/attention_bias_to_padding/Less (defined at usr/local/lib/python2.7/dist-packages/tensor2tensor/layers/common_attention.py:965) ': 'op: "Less" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_BFLOAT16 } } }' and 'op: "Less" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_BFLOAT16 } } }'
         [[transformer/parallel_0_5/transformer/transformer/body/encoder/attention_bias_to_padding/Less]]

Errors may have originated from an input operation.
Input Source operations connected to node transformer/parallel_0_5/transformer/transformer/body/encoder/attention_bias_to_padding/Less:
 transformer/parallel_0_5/transformer/transformer/body/Cast (defined at usr/local/lib/python2.7/dist-packages/tensor2tensor/layers/common_layers.py:3486)

**Comment by ekuznetsov139** [comment]
I've tracked it down to a bug in TensorFlow. I'll open an issue report there.

**Comment by ekuznetsov139** [comment]
Looks like one of the reasons is that tensorflow does not implement several GPU ops for bfloat16, starting with multiplication.

**Comment by etragas-fathom** [comment]
Hey @ekuznetsov139, unfortunately the code written in #1362 has only been tested on v100s with the activation_dtype set to `float16` as seen here: https://github.com/tensorflow/tensor2tensor/pull/1362/files#diff-2afdeb32501f7525a17f09ded21120afR2163

**Comment by etragas-fathom** [comment]
I think that bfloats are only supported on tpus and cpu at the moment, which might explain the copy that you're seeing

**Comment by ekuznetsov139** [comment]
Yes, I somehow misread #1362 to mean activation_dtype=bfloat16.

**Comment by lkluo** [comment]
My training with `transformer_fairseq_fp16_activation_big` is smooth without any errors. However, the loss starts to increase after several thousand of steps, and stops to decrease afterwards. I am using V100. Any suggestion?
