### ISSUE TITLE
Most straight forward way to train summarization on new data with simpler format than CNN/DM datasets? Make a new data_generator ?

### ISSUE THREAD

**Issue by Santosh-Gupta** [tensorflow/tensor2tensor#1631]
### Description

I would like to train a summarizer on my own data, and I am wondering what's the most straightforward way to do this. The CNN/DailyMail datasets have a bit of an odd format which seems tricky to convert regular summarization datasets (CSVs with 1 column for source, 1 column for summary) into. 

So from my analysis of the code, the easiest to for Tensor2Tensor to accept new summarization datasets is to develop new data_generators such that it will be able to training on any data formatted in CSV, one column being the source, the other column being the summary. 

My plan is to use the data_generators/cnn_dailymail.py code as the base with the following alterations:

First, replace the CNN/DailyMail google drive links with my own, here

https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/cnn_dailymail.py#L37

Then, I need to alter `def example_generator` in https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/cnn_dailymail.py#L137

In such a way that it'll take my custom data and put the source and summary in one line, seperated by story_summary_split_token ,( unless there's no sum_token )

Is this it? Or is there anything else I need to take into consideration?

**Comment by Santosh-Gupta** [comment]
From furthering reviewing the code, this is pretty much what I need to do.

**Comment by darsh10** [comment]
Hi Santosh,

Would it be possible for you to share the code for doing this?
