### ISSUE TITLE
How to finetune a model with a different vocab?

### ISSUE THREAD

**Issue by SiriusKY** [tensorflow/tensor2tensor#1636]
### Description

I have trained a universal translation model with t2t, if I get new corpus in a specific field, can I modify the vocab file and train a model based on the model I have now? Thanks!!

**Comment by bharat-patidar** [comment]
Hi @SiriusKY ,
Did you find answer for your question? I am also looking out for the same.

**Comment by SiriusKY** [comment]
> Hi @SiriusKY ,
> Did you find answer for your question? I am also looking out for the same.

Hi @bharat-patidar 

I just simply substitute the vocab file & .lang file in the train folder and then train a few more steps, sort of "lie" to the machine so that it "thinks" nothing changed and kept training : )

I'm not sure if there is a better and elegant way, at least by this way fine-tune was done correctly. Hope this helps!

**Comment by martinpopel** [comment]
FYI: There is a research on the various ways of transfer learning with T2T, possibly with substituting the vocabulary in a clever way (keep the same subwords on the same positions, substituting the rest according to frequency), see https://arxiv.org/pdf/1909.10955.pdf (or a whole PhD thesis https://arxiv.org/pdf/2001.01622.pdf).
