### ISSUE TITLE
tf serving RESTful  API  request format

### ISSUE THREAD

**Issue by Roshanson** [tensorflow/tensor2tensor#1658]
### Description

I trained a model with my own data. Then use export.py to convert the .ckpt model to saved_model.Then I started a tf serving.  The interface  in grpc format is ok.  But I need a RSETful type of interface.  I did a lot of trials and still didn't succeed...

Has anyone tried to build a tf serving service with a RESTful-style interface? I can't find the correct request format

when i send a post request
curl -d '{"instances": [{"input": {"b64": "Ijg1MyI="}}]}' -X POST http://10.25.59.196:8501/v1/models/translate:predict

i get:

       {
        "error": "Requested more than 0 entries, but params is empty.  Params shape: 
         [1,4,1,1,0]\n\t 
         [[{{node transformer/while/GatherNd_1}}]]"
         }

here is the metadata:

        {
	"model_spec": {
		"name": "translate",
		"signature_name": "",
		"version": "1565597475"
	},
	"metadata": {
		"signature_def": {
			"signature_def": {
				"serving_default": {
					"inputs": {
						"input": {
							"dtype": "DT_STRING",
							"tensor_shape": {
								"dim": [{
									"size": "-1",
									"name": ""
								}],
								"unknown_rank": false
							},
							"name": "serialized_example:0"
						}
					},
					"outputs": {
						"scores": {
							"dtype": "DT_FLOAT",
							"tensor_shape": {
								"dim": [{
									"size": "-1",
									"name": ""
								}],
								"unknown_rank": false
							},
							"name": "transformer/strided_slice_11:0"
						},
						"batch_prediction_key": {
							"dtype": "DT_INT32",
							"tensor_shape": {
								"dim": [{
										"size": "-1",
										"name": ""
									},
									{
										"size": "1",
										"name": ""
									}
								],
								"unknown_rank": false
							},
							"name": "DatasetToSingleElement:0"
						},
						"outputs": {
							"dtype": "DT_INT32",
							"tensor_shape": {
								"dim": [{
										"size": "-1",
										"name": ""
									},
									{
										"size": "-1",
										"name": ""
									}
								],
								"unknown_rank": false
							},
							"name": "transformer/strided_slice_10:0"
						}
					},
					"method_name": "tensorflow/serving/predict"
			 	}
		 	}
	 	}
	 }
     }

**Comment by Roshanson** [comment]
I  got it

Just make  a serialize_example as input 

    inputs_list = ["上海 南京 杭州 武汉 北京 哈尔滨  纽约"]
    input_ids_list = [
        _encode(inputs, input_encoder, add_eos=problem.has_inputs)
        for inputs in inputs_list
    ]
    examples = [_make_example(input_ids, problem)
                for input_ids in input_ids_list]
    serialize_example_input_0 = [ex.SerializeToString() for ex in examples]

**Comment by qpzhao** [comment]
Hi Roshanson,
    What's the final curl command after making a serialize_example?
    According to your serializing demo,I successfully make a serialize_example as input. But I don't know how to use it to send a post request.
  This is my code for serialize_example:
`def main():
  problem = registry.problem("translate_enzh_wmt32k")
  hparams = hparam.HParams(data_dir="/home/xyz/t2t/data")
  problem.get_hparams(hparams)
  fname = "inputs" if problem.has_inputs else "targets"
  inputs_list = ["I am a Chinese."]

  input_encoder = problem.feature_info[fname].encoder
  input_ids_list = [_encode(inputs, input_encoder, add_eos=problem.has_inputs) for inputs in inputs_list]
  examples = [_make_example(input_ids, problem) for input_ids in input_ids_list]
  serialize_example_input_0 = [ex.SerializeToString() for ex in examples]

  print(serialize_example_input_0)`
  
  Then I got  [b'\n\x1a\n\x18\n\x06inputs\x12\x0e\x1a\x0c\n\n\x81\x8e\x01\xb3\n\xa7\x02\xcb\x1c\x01'].
  I use the following two curl command but they both are not work.
  (1)curl -d '{"instances": [{"input": {"serialized_example": "[b'\n\x19\n\x17\n\x06inputs\x12\r\x1a\x0b\n\t\x84\x01\xcb\x0c\t\xbe\x01\x04\x01']"}}]}' -X POST http://localhost:8501/v1/models/enzh:predict
    Then error is:
   `{
    "error": "Failed to process element: 0 key: input of 'instances' list. Error: Invalid argument: JSON Value: {\n     \"serialized_example\": \"[bnx19nx17nx06inputsx12rx1ax0bntx84x01xcbx0ctxbex01x04x01]\"\n} not formatted correctly for base64 data"
}`
  (2)curl -d '{"instances": [b'\n\x1a\n\x18\n\x06inputs\x12\x0e\x1a\x0c\n\n\x81\x8e\x01\xb3\n\xa7\x02\xcb\x1c\x01']}' -X POST http://localhost:8501/v1/models/enzh:predict
  Then error is:
  `{
    "error": "JSON Parse error: Invalid value. at offset: 15"
  }`

  This is signature_def. 
  `  signature_def {
    key: "serving_default"
    value {
      inputs {
        key: "input"
        value {
          name: "serialized_example:0"
          dtype: DT_STRING
          tensor_shape {
            dim {
              size: -1
            }
          }
        }
      }
      outputs {
        key: "batch_prediction_key"
        value {
          name: "DatasetToSingleElement:0"
          dtype: DT_INT32
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: 1
            }
          }
        }
      }
      outputs {
        key: "outputs"
        value {
          name: "transformer/strided_slice_12:0"
          dtype: DT_INT32
          tensor_shape {
            dim {
              size: -1
            }
            dim {
              size: -1
            }
          }
        }
      }
      outputs {
        key: "scores"
        value {
          name: "transformer/strided_slice_13:0"
          dtype: DT_FLOAT
          tensor_shape {
            dim {
              size: -1
            }
          }
        }
      }
      method_name: "tensorflow/serving/predict"
    }
  }`

  Thanks.
