### ISSUE TITLE
Checkpoint specification flag during evaluation ?

### ISSUE THREAD

**Issue by ragnarlbrok** [tensorflow/tensor2tensor#1673]
What flag should be used to evaluate a model on user specified checkpoint rather than latest checkpoint ?

**Comment by martinpopel** [comment]
`t2t-decoder --checkpoint-path=xy` and then `t2t-bleu ...` (BTW: `t2t-decoder -h` shows all options including `--checkpoint-path`).

See also `t2t-translate-all`, which can translate a given test set with all checkpoints in a given directory and `t2t-bleu` can evaluate all the translation automatically (and continuously whenever new checkpoint is added to the directory).

**Comment by ragnarlbrok** [comment]
ok, thanks
