### ISSUE TITLE
Bad results in the inference of speech recognition

### ISSUE THREAD

**Issue by manuel3265** [tensorflow/tensor2tensor#1676]
### Description
I did the voice recognition model training with my own data. I have trained with different numbers of steps: 10000, 30000, 50000, 150000 and 270000. The problem is that when putting the model into production with the flow model server tensor, we get somewhat strange results.
The results obtained are exactly the same as those of the training transcripts, for example:

**TRAINING TRANSCRIPTS**
I can not
I'm not
no, not today
Yes I can do it
Yes i am available
...

**INFERENCE**
1)
- **Audio content**: no

- **result**: no, not today

2)
- **Audio content**: Yes

- **result**: Yes i am available
...

### Environment information

```
OS: Debian 9 

$ pip freeze | grep tensor
mesh-tensorflow==0.0.5
tensor2tensorM==2.0.4
tensorboard==1.14.0
tensorflow==1.13.1
tensorflow-datasets==1.0.2
tensorflow-estimator==1.13.0
tensorflow-hub==0.4.0
tensorflow-metadata==0.13.0
tensorflow-probability==0.6.0
tensorflow-serving-api==1.12.0

$ python -V
Python 3.5.3
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
```

**Comment by stefan-falk** [comment]
@manuel3265 This is probably not a bug but just something the model does. It was trained to convert one sequence of audio to one sequence of text it tries to do so no matter what.

I am facing this issue myself and I am looking for ways to account for situations where there is actually no speech present in the audio.

If you have any suggestions by now I'd be happy to discuss them.
