### ISSUE TITLE
can't get access to length of k,v and q?

### ISSUE THREAD

**Issue by ad26kt** [tensorflow/tensor2tensor#168]
I want to directly modify the dot_product_attention, and multihead_attention function but not to use those module to make a bigger module.

However, due to the input structure with quite complicated batch-making procedure, I can't figure out how to get the shape of those k,v and q

There are two problems that i am dealing with:
1. ```q.get_shape()``` or ```q.get_shape().as_list()``` or ```q.shape```  yields ```[None, 8, None, 64]``` which corresponds to ```[batch_size, heads, length, depth]```, that I can't use the ```length=None``` to reshape q
2. ```tf.shape(q)``` yields a tensor indicating a shape of q which i can use to reshape q, however, i can't ```tf.unstack``` reshaped_q 

From tensorboard I find out that i can get the length of q,k and v (length matched to each bucketed batch), but I don't know how.

**Comment by lukaszkaiser** [comment]
You can do `s = tf.shape(q)` and then `batch_size, head, length, depth =  s[0], s[1], s[2], s[3]`. Later, in rehape, just use these tensors-scalars, reshape works with tensors.

Does that solve your problem? I'll close for now, but please reopen if you still have the problem!

**Comment by ad26kt** [comment]
@lukaszkaiser 
I mentioned the issue with related to tf.shape and tensor.get_shape() above.
1. if i use q.get_shape() , it returns [None, 8, None, 64], the length of which is None(may because of bucketing function) so that i can't reshape with these values
e.g.
```
q_shape = q.get_shape()
# [batch * heads, length, depth]
reshaped_q = tf.reshape(q_set, [-1, q_shape[2], q_shape[3]) # here is the error
    
# length_q list of tensors with shape [batch*heads, depth_q]
 q_list = tf.unstack(reshaped_q, axis = 1) # here is the error
```

2. I can reshape q with tf.shape(q). however, I can't unstack the reshaped tensor.
e.g.
```
q_shape = tf.shape(q)
# [batch * heads, length, depth]
reshaped_q = tf.reshape(q_set, [-1, q_shape[2], q_shape[3])
    
# length_q list of tensors with shape [batch*heads, depth_q]
 q_list = tf.unstack(reshaped_q, axis = 1) # here is the error
```

and I think these two problem make users can not implement their own components which is not modulating high-level module which tensor2tensor provides but low-level combination of those value like k,q and v.

**Comment by lukaszkaiser** [comment]
As for (1), it returns the static shape (known before the graph runs). Since length isn't static, it cannot know it, it's just `None` and you cannot use it to reshape, that's expected (still, you should use `q.get_shape().as_list()` if you want to access elements).

The same applied to your problem in (2). You can only unstack if you statically know that dimension. But the length changes from batch to batch, it's by design. So you cannot statically unstack it, that's simply impossible. You could try to do it in some ways like in pytorch, but then the whole computation would be so slow that it would be basically useless. So indeed: there are problems with handling variable-shape tensors, but doing this is a key point that adds speed to our models!

**Comment by ad26kt** [comment]
I fully understand that those kind of variable length bucketing is a core mechanism for efficient computation. Then What I want to ask is: Is there any method that I can use to get exact size of those lengths and make new operation with those values. As I think, The transformer code now cannon't be extended to further modification of 'attention' , I mean the code is only for dot-product attention and it has so many restriction that it can't be modified to other new attention mechanism.

**Comment by lukaszkaiser** [comment]
We have multiple versions of attention already and the code can be easily modified to add new ones. You just have to learn to operate with variable-sized tensors in TensorFlow. You get the exact length by calling `tf.shape(q)[2]` and you can use it in many ops - just not in `tf.unstack`. To learn about general variable-size operations in TensorFlow take a look at the functional ops: https://www.tensorflow.org/api_guides/python/functional_ops

**Comment by ad26kt** [comment]
I may try to use other functions to substitute my original implementation. Thanks for suggestion.

**Comment by ad26kt** [comment]
Then can you give me a suggestion if I want to implement bahdanau attention instead of dot-product attention? @lukaszkaiser
