### ISSUE TITLE
AssertionError FLAGS.output_dir in t2t-decoder (despite defining output_dir flag)

### ISSUE THREAD

**Issue by katelynrwalker** [tensorflow/tensor2tensor#1685]
### Description
When I run t2t-decoder, it fails based on an Assertion error that there is no FLAGS.output_dir or FLAGS.checkpoint_path. However, I defined the output_dir flag when I ran the command. 

Going into the t2t_trainer.py and t2t_decoder.py code and placing a few print statements showed that the FLAGS.output_dir is indeed blank.
...

### Environment information

```              
tensor2tensor            1.12.0                            
tensorflow               1.12.0               
python 3.7.4
```
Also got same error with:   
```
tensor2tensor            1.14.0     
tensorflow               1.14.0    
```

### Steps to reproduce:
```
/home/ubuntu/anaconda3/envs/t2t/bin/t2t-decoder \
  --data_dir=/data/20190816/cu/single \
  --t2t_usr_dir=/home/ubuntu/code/ref-element-extract/trainer \
  --problem=cutag \
  --model=transformer \
  --hparams_set=transformer_big \
  --output_dir=/data/models/trained_model_with_types_20190816 \
  --decode_hparams="batch_size=64,beam_size=0,extra_length=0,force_decode_length=True" \
  --decode_from_file=/data/20190816/eval/input.txt \
  --decode_to_file=/data/20190816/eval/predictions.txt
```
### Error logs:
```
INFO:tensorflow:Importing user module trainer from path /home/ubuntu/code/ref-element-extract
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/t2t/bin/t2t-decoder", line 17, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/t2t/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/anaconda3/envs/t2t/bin/t2t-decoder", line 12, in main
    t2t_decoder.main(argv)
  File "/home/ubuntu/anaconda3/envs/t2t/lib/python3.6/site-packages/tensor2tensor/bin/t2t_decoder.py", line 188, in main
    t2t_trainer.create_run_config(hp),
  File "/home/ubuntu/anaconda3/envs/t2t/lib/python3.6/site-packages/tensor2tensor/bin/t2t_trainer.py", line 215, in create_run_config
    assert FLAGS.output_dir or FLAGS.checkpoint_path
AssertionError
```

**Comment by katelynrwalker** [comment]
Adding the checkpoint_path flag resolved this.
```--checkpoint_path=/data/models/trained_model_with_types_20190816/model.ckpt-7000```

**Comment by martinpopel** [comment]
It should work with the `--output_dir` as well. A common cause of an empty flag or other bugs is that you forget to end one of the previous lines with a backslash (\) or that you add extra space after the equal sign (`--output_dir= /data/models...`). I don't see any of these bugs in your sample, but maybe your command was different from what you pasted here.

Of course, if `--checkpoint_path` works for you as expected, you can continue using it instead of `--output_dir` (and have a better control over which checkpoint is used).

**Comment by katelynrwalker** [comment]
No, that is the exact command I was running at that time. I also felt like it must be some sort of typo, but I couldn't see anything. In trying to figure out what was going on, I even added some print statements of FLAGS.output_dir and FLAGS.checkpoint_path in problem.py (the version in my t2t_usr_dir). FLAGS.output_path prints nothing, FLAGS.checkpoint_path prints the directory I gave it.

The command again (I changed a few file paths since I first posted this):
```
/home/ubuntu/anaconda3/envs/t2t/bin/t2t-decoder \
  --data_dir=/data/data/20190816/cu/single \
  --t2t_usr_dir=/home/ubuntu/code/ref-element-extract-with-types/trainer \
  --problem=cutag \
  --model=transformer \
  --hparams_set=transformer_big \
  --output_dir=/data/models/trained_model_with_types_20190816/ \
  --decode_hparams="batch_size=64,beam_size=0,extra_length=0,force_decode_length=True" \
  --decode_from_file=/data/data/20190816/eval/input.txt \
  --decode_to_file=/data/data/20190816/eval/predictions.txt \
  --checkpoint_path=/data/models/trained_model_with_types_20190816/model.ckpt-7000
```
This runs fine, but editing out the last line causes the AssertionError.

At the beginning of /home/ubuntu/code/ref-element-extract/trainer/problem.py:
```
FLAGS = tf.flags.FLAGS
print("OUTPUT FLAG HERE")
print(FLAGS.output_dir)
print("CHECKPOINT FLAG HERE")
print(FLAGS.checkpoint_path)
```

The relevant section of the output:
```
INFO:tensorflow:Importing user module trainer from path /home/ubuntu/code/ref-element-extract-with-types
OUTPUT FLAG HERE

CHECKPOINT FLAG HERE
/data/models/trained_model_with_types_20190816/model.ckpt-7000
```
