### ISSUE TITLE
No need to generate inputs in PTB

### ISSUE THREAD

**Issue by ricky820422** [tensorflow/tensor2tensor#169]
For PTB, we have inputs and targets
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/ptb.py#L130
But for lm1b, we just always leave input as [0], and have
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/lm1b.py#L161
Since we actually don't use the "imputs" field in both attention_lm and attention_lm_moe modules, maybe in PTB, we don't need to generate this field and save it in the data_dir?

**Comment by pltrdy** [comment]
Hi, I wrote this thing, and it has been merged too early (imo). See the referenced issue where I discuss it. 

Contribution are welcome.

**Comment by lukaszkaiser** [comment]
It is corrected in 1.1.3: the PTBProblem correctly sets "has_inputs" to False, but still generates a dummy input for compatibility (just in case). Should be all fine now, feel free to reopen if you see a problem again.
