### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by cshanbo** [tensorflow/tensor2tensor#17]
Hi all, 
I tested the training example in [readme](https://github.com/tensorflow/tensor2tensor/blob/master/README.md).
I found that the `volatile GPU-util` of almost all GPUs are `0%` except the first one but took all GPU memories. I'm not sure whether it's a `tensorflow` or `tensor2tensor` error.

Thank you

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M40 24GB      Off  | 0000:04:00.0     Off |                    0 |
| N/A   56C    P0   187W / 250W |  21871MiB / 22939MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M40 24GB      Off  | 0000:05:00.0     Off |                    0 |
| N/A   28C    P0    56W / 250W |  21806MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla M40 24GB      Off  | 0000:08:00.0     Off |                    0 |
| N/A   28C    P0    55W / 250W |  21804MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla M40 24GB      Off  | 0000:09:00.0     Off |                    0 |
| N/A   29C    P0    55W / 250W |  21804MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla M40 24GB      Off  | 0000:86:00.0     Off |                    0 |
| N/A   29C    P0    56W / 250W |  21808MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla M40 24GB      Off  | 0000:87:00.0     Off |                    0 |
| N/A   27C    P0    57W / 250W |  21806MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla M40 24GB      Off  | 0000:8A:00.0     Off |                    0 |
| N/A   30C    P0    57W / 250W |  21804MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla M40 24GB      Off  | 0000:8B:00.0     Off |                    0 |
| N/A   27C    P0    56W / 250W |  21804MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

```

**Comment by lukaszkaiser** [comment]
Tensorflow will by default allocate all memory and manage it internally, so I'd say that's fine (you can set TF to change that). But why aren't the GPUs used? Could you attach your output? How many steps/s are happening? Did you try running with just 1 GPU, how many steps happen then? (Note that in multi-gpu setting, you're getting larger batches, which means fewer steps/s but every step is larger; you might want to lower batch_size to compensate.)

**Comment by cshanbo** [comment]
Thank you for helping. I'm not quite sure what the `steps` means. Does it mean the number of batches?
The simplified output is like:
```
  
INFO:tensorflow:Creating experiment, storing model files in /search/odin/public/experiments/tensor2tensor/exp/wmt_ende_tokens_32k/transformer-transformer_base
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Using config: {'_model_dir': '/search/odin/public/experiments/tensor2tensor/exp/wmt_ende_tokens_32k/transformer-transformer_base', '_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_max': 20, '_tf_random_seed': None, '_task_type': None, '_environment': 'local', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f6d61c790d0>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_num_worker_replicas': 0, '_task_id': 0, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_session_config': allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
}
INFO:tensorflow:Performing local training.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Doing model_fn_body took 2.520 sec.
INFO:tensorflow:This model_fn took 2.705 sec.
...
...
...
2017-06-22 11:23:32.909123: I tensorflow/core/common_runtime/gpu/gpu_device.cc:798] Peer access not supported between device ordinals 6 and 2
2017-06-22 11:23:32.909130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:798] Peer access not supported between device ordinals 6 and 3
2017-06-22 11:23:32.910197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:798] Peer access not supported between device ordinals 7 and 0
2017-06-22 11:23:32.910210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:798] Peer access not supported between device ordinals 7 and 1
2017-06-22 11:23:32.910219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:798] Peer access not supported between device ordinals 7 and 2
2017-06-22 11:23:32.910226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:798] Peer access not supported between device ordinals 7 and 3
2017-06-22 11:23:32.910482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:927] DMA: 0 1 2 3 4 5 6 7 
2017-06-22 11:23:32.910490: I tensorflow/core/common_runtime/gpu/gpu_device.cc:937] 0:   Y Y Y Y N N N N 
2017-06-22 11:23:32.910495: I tensorflow/core/common_runtime/gpu/gpu_device.cc:937] 1:   Y Y Y Y N N N N 
2017-06-22 11:23:32.910500: I tensorflow/core/common_runtime/gpu/gpu_device.cc:937] 2:   Y Y Y Y N N N N 
2017-06-22 11:23:32.910504: I tensorflow/core/common_runtime/gpu/gpu_device.cc:937] 3:   Y Y Y Y N N N N 
2017-06-22 11:23:32.910509: I tensorflow/core/common_runtime/gpu/gpu_device.cc:937] 4:   N N N N Y Y Y Y 
2017-06-22 11:23:32.910513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:937] 5:   N N N N Y Y Y Y 
2017-06-22 11:23:32.910518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:937] 6:   N N N N Y Y Y Y 
2017-06-22 11:23:32.910522: I tensorflow/core/common_runtime/gpu/gpu_device.cc:937] 7:   N N N N Y Y Y Y 
2017-06-22 11:23:32.910540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla M40 24GB, pci bus id: 0000:04:00.0)
2017-06-22 11:23:32.910547: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla M40 24GB, pci bus id: 0000:05:00.0)
2017-06-22 11:23:32.910552: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:2) -> (device: 2, name: Tesla M40 24GB, pci bus id: 0000:08:00.0)
2017-06-22 11:23:32.910561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:3) -> (device: 3, name: Tesla M40 24GB, pci bus id: 0000:09:00.0)
2017-06-22 11:23:32.910567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:4) -> (device: 4, name: Tesla M40 24GB, pci bus id: 0000:86:00.0)
2017-06-22 11:23:32.910571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:5) -> (device: 5, name: Tesla M40 24GB, pci bus id: 0000:87:00.0)
2017-06-22 11:23:32.910575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:6) -> (device: 6, name: Tesla M40 24GB, pci bus id: 0000:8a:00.0)
2017-06-22 11:23:32.910580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:7) -> (device: 7, name: Tesla M40 24GB, pci bus id: 0000:8b:00.0)
INFO:tensorflow:Restoring parameters from /search/odin/public/experiments/tensor2tensor/exp/wmt_ende_tokens_32k/transformer-transformer_base/model.ckpt-1
2017-06-22 11:23:39.538703: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 1266 get requests, put_count=1200 evicted_count=1000 eviction_rate=0.833333 and unsatisfied allocation rate=0.921011
2017-06-22 11:23:39.538793: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
INFO:tensorflow:Saving checkpoints for 2 into /search/odin/public/experiments/tensor2tensor/exp/wmt_ende_tokens_32k/transformer-transformer_base/model.ckpt.
INFO:tensorflow:loss = 10.8679, step = 2
2017-06-22 11:24:14.259121: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 4707 get requests, put_count=4632 evicted_count=1000 eviction_rate=0.215889 and unsatisfied allocation rate=0.23327
2017-06-22 11:24:14.259201: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 256 to 281
INFO:tensorflow:global_step/sec: 0.912305
INFO:tensorflow:loss = 8.77143, step = 102 (109.614 sec)
INFO:tensorflow:global_step/sec: 0.912966
INFO:tensorflow:loss = 7.66324, step = 202 (109.533 sec)

```

Notice that the last line, step = 102 (109.614sec), so I'd say it's about 1 step/sec? I'll try to use one GPU instead to see if the speed decreases.

**Comment by lukaszkaiser** [comment]
Yes! (I mean the line below: global_step/sec: 0.912966, as you say). That looks reasonable, it's more or less what I'd expect on an M40. 

T2T trainer does synchronous training by default. So a single "step" in your case processes 8x more examples (training sentence pairs) than a single "step" on a 1-GPU setup. So if normally a batch is around 100 sentences (you can see it if you start tensorboard with --log_dir $TRAIN_DIR), then you're actually processing about 800 sentences in each step, so about 15K tokens / second. Should be quite good :).

No idea why your cards are showing 0% usage though, maybe run it a few times? With such a large setup you might also not be using all GPUs to max capacity, try training a larger network, e.g., --hparams_set=transformer_big.

Closing this for now, feel free to reopen if you see other problems.

**Comment by lukaszkaiser** [comment]
No, sorry, changed my mind, re-opening. Why is your "datashard_devices: ['gpu:0']"? That looks wrong, it should show all GPUs! I think you might need to set --worker_gpus=8 when calling t2t-trainer. Could you try this? Thanks!

**Comment by cshanbo** [comment]
It's strange. I set the --worker_gpus, the problem remains. My script is basically the one in `readme.md`, with tiny modifications:
```
t2t-trainer --registry_help

PROBLEM=wmt_ende_tokens_32k
MODEL=transformer
HPARAMS=transformer_base
HOME_DIR=`pwd`
DATA_DIR=$HOME_DIR/t2t_data
TMP_DIR=$HOME_DIR/zip
TRAIN_DIR=$HOME_DIR/exp/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

# Generate data
# t2t-datagen \
#   --data_dir=$DATA_DIR \
#   --tmp_dir=$TMP_DIR \
#   --num_shards=100 \
#   --problem=$PROBLEM
# 
# mv $TMP_DIR/tokens.vocab.32768 $DATA_DIR

# Train
# *  If you run out of memory, add --hparams='batch_size=2048' or even 1024.

t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --worker_gpus=8 \
  --log_dir logs 

```

**Comment by lukaszkaiser** [comment]
What does it print out as datashard_devices? Are there 8 of them?

**Comment by lukaszkaiser** [comment]
Oh, its --worker_gpu not --worker_gpus, I think. See this line: https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/trainer_utils.py#L1255

**Comment by cshanbo** [comment]
Oh, that's it! It finally get the right `datashard_devices`, and the GPU usage is normal. Thank you for your help.

**Comment by tobyyouup** [comment]
@lukaszkaiser   I also work normally on multi-GPUs following your settings. Thanks

**Comment by cshanbo** [comment]
Currently closing it. But I'm still curious that why the speed, `global_step/sec=0.762162`, is even slower than the one in the `single node` scenario, which is ` global_step/sec: 0.912966`.
```
INFO:tensorflow:loss = 2.20414, step = 6201 (131.302 sec)
INFO:tensorflow:global_step/sec: 0.762162
INFO:tensorflow:loss = 2.09709, step = 6301 (131.206 sec)
INFO:tensorflow:Saving checkpoints for 6323 into /search/odin/public/experiments/tensor2tensor/exp/8cards/wmt_ende_tokens_32k/transformer-transformer_base/model.ckpt.
INFO:tensorflow:global_step/sec: 0.715319
INFO:tensorflow:loss = 2.28911, step = 6401 (139.798 sec)
INFO:tensorflow:global_step/sec: 0.762425
INFO:tensorflow:loss = 2.32786, step = 6501 (131.161 sec)
```

I followed the settings of [readme.md](https://github.com/tensorflow/tensor2tensor/blob/master/README.md). I looked into the code and to see that the batch size is 4096 (see [here](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py#L268)).  So if I didn't misunderstand, the speed is about `0.762162 * 4096 = 3121.8` sentences/sec?

**Comment by lukaszkaiser** [comment]
A single `step` runs 1 batch on each GPU. So it's always slower with more GPUs: in addition to running it on every GPU, you need them all to sync. But you're running 8x more examples effectively.

Our `batch_size` might be a bit misleading: it's calculated (1) per-token and (2) per-gpu. To understand (1), assume you're first processing a batch of sentences of 15 words each, and then another, of sentences of 40 words each. If you keep the same batch size, your memory use in the second case (40 words) will be over 2x more than in the first case (15 words), as all hidden activations have a length dimension. So either you set a low `batch_size` and under-utilize your GPU in the 15-words case, or you try to set a high one, and possibly get an `OOM` in the 40-words case. That's why we have a per-token batch size: it's variable depending on token length. If `batch_size=4096` then if the sentence has 15 words, we'll actually get a batch of `4096 // 15 = 273` sentences. But if the length is 40, we'll take a batch of `4096 // 40 = 102` sentences. But, coming to (2), this is per-gpu. If you have another GPU, you can easily process another batch of the same size there. We want to avoid changing batch sizes when we use more GPUs, because we sometimes test a model on 1 or 2 GPUs and then run it on more. It's helpful to not have to change the hyperparameters each time when running on different hardware. That's why a `batch_size = 4096` actually means you're running 4096 tokens (not sentences) on each GPU you have. So `0.912966 * 1 * 4096  = 3740` tokens / s in 1-GPU case, and `0.762162 * 8 * 4096 = 24975` tokens / s on 8 GPUs.

Hope that helps to understand it!

**Comment by cshanbo** [comment]
Hi @lukaszkaiser 
I have another question about the `step` that might need your help, please:
> If batch_size=4096 then if the sentence has 15 words, we'll actually get a batch of 4096 // 15 = 273 sentences.

What exactly does the `sentence length` mean? Does it mean the length of source sentence in a translation task? 
Thank you

**Comment by lukaszkaiser** [comment]
It's the maximum of the number of tokens in the source sentence and target sentence.
(See https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/data_reader.py#L257)

**Comment by yuimo** [comment]
@lukaszkaiser hi, "batch_size=4096 then if the sentence has 15 words, we'll actually get a batch of 4096 // 15 = 273 sentences."
this mean a batch contains 273 sentences, right?
does this mean 273 source sentences and 273 target sentences in a batch
or 136 source and 136 target sentences?
thanks

**Comment by martinpopel** [comment]
@yuimo: if all source sentences in your data have 15 **sub**words and all target sentences have 15 or less subwords, then with batch_size 4096 each batch will contain 273 sentence pairs (source, target).
In practice, each sentence has different length, sometimes the source sentence has more subwords than the target sentence, sometimes it is the other way round, also sentence-length bucketing of batches is applied so it is difficult to predict how many sentences are in each batch.
I think, this discussion is not related to the topic of this issue (GPU usage), but rather to #415 (which is still opened unlike this issue).

**Comment by EthannyDing** [comment]
I have the same problem that my sole gpu usage is close to 0 and cpu usage is high while training for tensor2tensor model. I'm using the following installations:
tensor2tensor==1.7.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
tensorflow-gpu==1.13.1
tensorflow-tensorboard==1.5.1
I tried to uninstall tensorflow and kept tensorflow-gpu and it reported an error that ModuleNotFoundError: No module named 'tensorflow.python'
Is anyone know what is going wrong in the training??
