### ISSUE TITLE
Why not reuse history in beam search?

### ISSUE THREAD

**Issue by danliu2** [tensorflow/tensor2tensor#170]
Hi, the implementation of beam search for t2t_model is repeatedly calculate encoder outputs and decode history, why not calculate encoder output first and reuse decoder history?

**Comment by lukaszkaiser** [comment]
Yes, we should do that. We just didn't find the time to implement it, contributions are welcome!

**Comment by rsepassi** [comment]
FYI, the Transformer model now implements fast decoding.
