### ISSUE TITLE
How to parallelize datagen manually on Text2TextProblems?

### ISSUE THREAD

**Issue by abnf** [tensorflow/tensor2tensor#1719]
### Description

Is it possible to parallelize datagen manually when doing text2text problems? Because even though the data files can be concatenated, it seems likely that the vocab files (eg vocab.phrase_generator_problem.65536.subwords) cannot be concatted because the vocab files are different when running datagen on different subsets of data.

Quote from @martinpopel in #914 
> You can use `t2t-datagen` for generating the training data. I think recently it got support for multi-thread processing (but I am not sure, maybe you need to switch it on with some option - I'm busy now to check). You can even parallelize datagen manually (e.g. on different machines) and then just concat the TFRecords files (they have no header), or just rename the files. What is tricky is your idea of starting training before all the data is ready. You can resume training (i.e. stop and start again from the last checkpoint but with a new dataset), but does not seem user-friendly to me. I usually run `t2t-datagen` on CPU-only machines and `t2t-trainer` on GPU machines.

...

### Environment information

```
OS: 
Version: tf-cpu.1-14.m34
Based on: Debian GNU/Linux 9.9 (stretch) (GNU/Linux 4.9.0-9-amd64 x86_64\n)
Linux cpu1-vm 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64

$ pip freeze | grep tensor
# your output here
jupyter-tensorboard==0.1.10
mesh-tensorflow==0.0.5
tensor2tensor==1.13.4
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-datasets==1.2.0
tensorflow-estimator==1.14.0
tensorflow-hub==0.5.0
tensorflow-metadata==0.14.0
tensorflow-probability==0.7.0rc0
tensorflow-serving-api==1.13.0rc1
tensorflow-transform==0.14.0

$ python -V
# your output here
Python 2.7.13
```

**Comment by abnf** [comment]
I manually tested concatenating the datagen outputs manually and it did not raise any errors during training, but does concatenating the vocabulary files result in meaningful training? I assumed the vocabulary files would not maintain their proper meaning if concatenated.

**Comment by abnf** [comment]
Nevermind, I found out how to do it.
When performing a `t2t-datagen` problem, the bottleneck in computation time is the generation of cases.
The `t2t-datagen` goes through two steps when creating the examples:
1. Creating the vocab file
2. Generating the examples

Unfortunately, `t2t-datagen` runs on only a single CPU core making it very slow for processing large datasets.
Although it is possible to use `multiprocessing` to run on multiple cores, I still have not figured out how to do that, even referring to the [gene_expression](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/gene_expression.py) `multiprocessing` code, and there is some level of complexity involved.

In manually multiprocessing the `Text2Text` data, you have two options:

1. Using the vocab file from the first subset of data
2. Using the vocab file from the entire dataset

The trick is that once you generate the vocab file, you can abort the `t2t-datagen` process, copy the vocab file to all the other data folders that you intend to generate and then run a separate `t2t-datagen` process for the many subsets of data that you have.

`t2t-datagen` prints out that it found the vocab file that you manually placed:

```sh
INFO:tensorflow:Found vocab file: ./data_01/vocab.phrase_generator_problem.65536.subwords
I1002 14:42:20.703675 139778865637120 generator_utils.py:346] Found vocab file: ./data_01/vocab.phrase_generator_problem.65536.subwords
```

**Comment by martinpopel** [comment]
To clarify: you need to create the vocabulary first (which is done on a subset of the training data, so it is relatively fast). You can then manually parallelize the rest of the datagen process, but you need to distribute the same vocab file to all the machines.

**Comment by abnf** [comment]
For reference, here is the script I ended up using.
For simplicity I used the character vocabulary type so that I would not have to handle the vocabulary files.

```sh
#!/bin/sh
# Get the number of cores on the computer
# Because each `t2t-datagen` program takes up one core for computation
NPROC=$(nproc)
echo $NPROC

# Split the dataset into number of files corresponding to the number of cores
# but maintain the newline separation
split --number=l/$NPROC parabank.tsv

# split has now created `nproc` files with names prefixed with 'x'
# We assume that none of the original files in the folder are prefixed with 'x'
mkdir dirs
for file in x*; do
  mkdir dirs/$file 
done;

for file in x*; do
  mv $file dirs/$file
done;

# Make a separate copy of the problem for each file
# Because we do not know how to explicitly provide custom training file path
for file in dirs/*; do
  cp -r phrase_generator $file
done;


for file in dirs/*; do
  mv $file/"${file##*/}" $file/parabank.tsv
done;

# generate the datasets separately
for file in dirs/*; do
  t2t-datagen --t2t_usr_dir=./$file/phrase_generator/trainer --problem=phrase_generator_problem --data_dir=./$file/data --tmp_dir=./$file/data/tmp &
done;

# wait for all the datasets to be generated
wait;

# get the value of first file, we use it to find out what the names of the data folders are
# for example, different number of shards would result in different number of train and eval folders
file1=$(ls dirs | head -n 1)

# we use the first file as the base and separate it from the rest
mv dirs/$file1/data final
rm -rf dirs/$file1

# we concatenate all the other data files with the first file so we end up having all the data files combined.
for file in dirs/*; do
  for datafile in $file/data/*; do
    cat $file/data/"${datafile##*/}" >> final/"${datafile##*/}"
  done;
done;
```
