### ISSUE TITLE
 return self._UNESCAPE_REGEX.sub error line 533 in text_encoder.py

### ISSUE THREAD

**Issue by cyrilfurtado** [tensorflow/tensor2tensor#175]
Got latest on July 21 
Still getting issue 
 File "/home/ai/virtualenv_tf/local/lib/python2.7/site-packages/tensor2tensor/data_generators/text_encoder.py", line 533, in _unescape_token
    return self._UNESCAPE_REGEX.sub(match, escaped_token[:-1])
AttributeError: 'SubwordTextEncoder' object has no attribute '_UNESCAPE_REGEX'

Ubuntu 16.04, python 2.7  , tensorflow in virtual env

**Comment by lukaszkaiser** [comment]
This was corrected in release 1.1.1, maybe it didn't propagate to pypi yet? Could you check your version?
(https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/text_encoder.py#L533)

I'm closing for now, but please reopen if you see it with 1.1.1.
