### ISSUE TITLE
Log output probabilities of decoder during Beam Search

### ISSUE THREAD

**Issue by megvillanueva** [tensorflow/tensor2tensor#1757]
I want to get the output probabilities from the decoder  on every step of beam search. Can you help me log them to file?

I'm currently trying to log the `flat_logits` of [utils/beam_search.py](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/beam_search.py). But I'm failing to print the value of the tensor.

I'm quite new to tensorflow and I really appreciate the help. Thank you.

**Comment by real-brilliant** [comment]
try `tf.Print()` to print values of tensors

```
tensor_a = tensor_b + tensor_c

# add following function
tensor_a = tf.Print(tensor_a, [tensor_a, tensor_b(if needed), ...], message="tensor_a=", summarize=1000)
```

**Comment by megvillanueva** [comment]
It worked! Thank you very much! I'll just pipe them to a file to save them.
