### ISSUE TITLE
Librispeech , when decoding , vocabulary is None

### ISSUE THREAD

**Issue by hl312** [tensorflow/tensor2tensor#1759]
Hi , have you solved it ? When t2t_decode , an error comes, it says "the location
in docding:586:inputs_ids=vocabulary.encode(inputs) , 'NoneType' object has no atrribute 'encode'" .
some question:
1、The content in decode_from_file is whether "the path to real testdata file" or "testfile file" ?
2、vocabulary is geneated in datagen process or prepared by myself ?

**Comment by real-brilliant** [comment]
vocabulary is geneated in datagen process, in the same dir with training&dev dataset

i think there's no problem on loading testfile.  
your program have successfully obtain inputs, but failed to transform these raw text into token_ids by vocabulary

**Comment by hl312** [comment]
> vocabulary is geneated in datagen process, in the same dir with training&dev dataset
> i think there's no problem on loading testfile.
> your program have successfully obtain inputs, but failed to transform these raw text into token_ids by vocabulary

But, in speech_recognition.py:65 , I see p.vocab_size={"inputs" : None , "targets":256} , amazing .

**Comment by hl312** [comment]
Hi , guy , I wanna ask a question : when generating data in speech recognition part , the process generate vocabulary or not for targets ? In my opnion , it should do that but now not . I compared problem "LibriSpeech" with "Translate" , and found that in asr it called "get_or_generate_vocab" nowhere . @stefan-falk
