### ISSUE TITLE
No error, but cannot run!

### ISSUE THREAD

**Issue by minfengUCAS** [tensorflow/tensor2tensor#178]
I add my components to tensor2tensor to implement image caption! There are nothing wrong, but the program cannot run successfully. I think some bug in my programmer. The program output information as below:
INFO:tensorflow:Creating experiment, storing model files in /home/minfeng.zhan/dataset/t2t_train/image_mscoco_tokens_8k_tune/caption-caption_base_single_gpu
['/home/minfeng.zhan/dataset/ms_coco/image_mscoco_tokens_8k_tune-train*']
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Using config: {'_model_dir': '/home/minfeng.zhan/dataset/t2t_train/image_mscoco_tokens_8k_tune/caption-caption_base_single_gpu', '_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_max': 20, '_tf_random_seed': None, '_task_type': None, '_environment': 'local', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1283cf05d0>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_num_worker_replicas': 0, '_task_id': 0, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_session_config': allow_soft_placement: true
graph_options {
  optimizer_options {
  }
}
}
INFO:tensorflow:Performing local training.
WARNING:tensorflow:From /home/minfeng.zhan/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:268: __init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:Doing model_fn_body took 1.089 sec.
INFO:tensorflow:This model_fn took 2.753 sec.
INFO:tensorflow:Weight    body/decoder/layer_0/context_weight_attention/output_transform_single/bias      	shape    (196,)              	size    196
INFO:tensorflow:Weight    body/decoder/layer_0/context_weight_attention/output_transform_single/kernel    	shape    (1, 1, 512, 196)    	size    100352
INFO:tensorflow:Weight    body/decoder/layer_0/context_weight_attention/qkv_transform_single/bias         	shape    (1536,)             	size    1536
INFO:tensorflow:Weight    body/decoder/layer_0/context_weight_attention/qkv_transform_single/kernel       	shape    (1, 1, 512, 1536)   	size    786432
INFO:tensorflow:Weight    body/decoder/layer_0/conv_hidden_relu/conv1_single/bias                         	shape    (2048,)             	size    2048
INFO:tensorflow:Weight    body/decoder/layer_0/conv_hidden_relu/conv1_single/kernel                       	shape    (1, 1, 512, 2048)   	size    1048576
INFO:tensorflow:Weight    body/decoder/layer_0/conv_hidden_relu/conv2_single/bias                         	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/decoder/layer_0/conv_hidden_relu/conv2_single/kernel                       	shape    (1, 1, 2048, 512)   	size    1048576
INFO:tensorflow:Weight    body/decoder/layer_0/decoder_self_attention/output_transform_single/bias        	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/decoder/layer_0/decoder_self_attention/output_transform_single/kernel      	shape    (1, 1, 512, 512)    	size    262144
INFO:tensorflow:Weight    body/decoder/layer_0/decoder_self_attention/qkv_transform_single/bias           	shape    (1536,)             	size    1536
INFO:tensorflow:Weight    body/decoder/layer_0/decoder_self_attention/qkv_transform_single/kernel         	shape    (1, 1, 512, 1536)   	size    786432
INFO:tensorflow:Weight    body/decoder/layer_0/encdec_attention/kv_transform_single/bias                  	shape    (1024,)             	size    1024
INFO:tensorflow:Weight    body/decoder/layer_0/encdec_attention/kv_transform_single/kernel                	shape    (1, 1, 512, 1024)   	size    524288
INFO:tensorflow:Weight    body/decoder/layer_0/encdec_attention/output_transform_single/bias              	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/decoder/layer_0/encdec_attention/output_transform_single/kernel            	shape    (1, 1, 512, 512)    	size    262144
INFO:tensorflow:Weight    body/decoder/layer_0/encdec_attention/q_transform_single/bias                   	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/decoder/layer_0/encdec_attention/q_transform_single/kernel                 	shape    (1, 1, 512, 512)    	size    262144
INFO:tensorflow:Weight    body/decoder/layer_0/layer_norm/layer_norm_bias                                 	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/decoder/layer_0/layer_norm/layer_norm_scale                                	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/decoder/layer_0/layer_norm_1/layer_norm_bias                               	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/decoder/layer_0/layer_norm_1/layer_norm_scale                              	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/decoder/layer_0/layer_norm_2/layer_norm_bias                               	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/decoder/layer_0/layer_norm_2/layer_norm_scale                              	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/encode/conv_hidden_relu/conv1_single/bias                                  	shape    (2048,)             	size    2048
INFO:tensorflow:Weight    body/encode/conv_hidden_relu/conv1_single/kernel                                	shape    (1, 1, 512, 2048)   	size    1048576
INFO:tensorflow:Weight    body/encode/conv_hidden_relu/conv2_single/bias                                  	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/encode/conv_hidden_relu/conv2_single/kernel                                	shape    (1, 1, 2048, 512)   	size    1048576
INFO:tensorflow:Weight    body/encode/layer_norm/layer_norm_bias                                          	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/encode/layer_norm/layer_norm_scale                                         	shape    (512,)              	size    512
INFO:tensorflow:Weight    body/target_space_embedding/kernel                                              	shape    (32, 512)           	size    16384
INFO:tensorflow:Weight    image_modality/image_modality/block0/res_conv0/conv_block_0_single/kernel       	shape    (1, 1, 64, 128)     	size    8192
INFO:tensorflow:Weight    image_modality/image_modality/block0/res_conv0/conv_block_norm_0/layer_norm_bias	shape    (128,)              	size    128
INFO:tensorflow:Weight    image_modality/image_modality/block0/res_conv0/conv_block_norm_0/layer_norm_scale	shape    (128,)              	size    128
INFO:tensorflow:Weight    image_modality/image_modality/block0/sep_conv_block/conv_block_0_single/depthwise_kernel	shape    (3, 3, 64, 1)       	size    576
INFO:tensorflow:Weight    image_modality/image_modality/block0/sep_conv_block/conv_block_0_single/pointwise_kernel	shape    (1, 1, 64, 128)     	size    8192
INFO:tensorflow:Weight    image_modality/image_modality/block0/sep_conv_block/conv_block_1_single/depthwise_kernel	shape    (3, 3, 128, 1)      	size    1152
INFO:tensorflow:Weight    image_modality/image_modality/block0/sep_conv_block/conv_block_1_single/pointwise_kernel	shape    (1, 1, 128, 128)    	size    16384
INFO:tensorflow:Weight    image_modality/image_modality/block0/sep_conv_block/conv_block_norm_0/layer_norm_bias	shape    (128,)              	size    128
INFO:tensorflow:Weight    image_modality/image_modality/block0/sep_conv_block/conv_block_norm_0/layer_norm_scale	shape    (128,)              	size    128
INFO:tensorflow:Weight    image_modality/image_modality/block0/sep_conv_block/conv_block_norm_1/layer_norm_bias	shape    (128,)              	size    128
INFO:tensorflow:Weight    image_modality/image_modality/block0/sep_conv_block/conv_block_norm_1/layer_norm_scale	shape    (128,)              	size    128
INFO:tensorflow:Weight    image_modality/image_modality/block1/res_conv0/conv_block_0_single/kernel       	shape    (1, 1, 128, 256)    	size    32768
INFO:tensorflow:Weight    image_modality/image_modality/block1/res_conv0/conv_block_norm_0/layer_norm_bias	shape    (256,)              	size    256
INFO:tensorflow:Weight    image_modality/image_modality/block1/res_conv0/conv_block_norm_0/layer_norm_scale	shape    (256,)              	size    256
INFO:tensorflow:Weight    image_modality/image_modality/block1/sep_conv_block/conv_block_0_single/depthwise_kernel	shape    (3, 3, 128, 1)      	size    1152
INFO:tensorflow:Weight    image_modality/image_modality/block1/sep_conv_block/conv_block_0_single/pointwise_kernel	shape    (1, 1, 128, 256)    	size    32768
INFO:tensorflow:Weight    image_modality/image_modality/block1/sep_conv_block/conv_block_1_single/depthwise_kernel	shape    (3, 3, 256, 1)      	size    2304
INFO:tensorflow:Weight    image_modality/image_modality/block1/sep_conv_block/conv_block_1_single/pointwise_kernel	shape    (1, 1, 256, 256)    	size    65536
INFO:tensorflow:Weight    image_modality/image_modality/block1/sep_conv_block/conv_block_norm_0/layer_norm_bias	shape    (256,)              	size    256
INFO:tensorflow:Weight    image_modality/image_modality/block1/sep_conv_block/conv_block_norm_0/layer_norm_scale	shape    (256,)              	size    256
INFO:tensorflow:Weight    image_modality/image_modality/block1/sep_conv_block/conv_block_norm_1/layer_norm_bias	shape    (256,)              	size    256
INFO:tensorflow:Weight    image_modality/image_modality/block1/sep_conv_block/conv_block_norm_1/layer_norm_scale	shape    (256,)              	size    256
INFO:tensorflow:Weight    image_modality/image_modality/block2/res_conv0/conv_block_0_single/kernel       	shape    (1, 1, 256, 512)    	size    131072
INFO:tensorflow:Weight    image_modality/image_modality/block2/res_conv0/conv_block_norm_0/layer_norm_bias	shape    (512,)              	size    512
INFO:tensorflow:Weight    image_modality/image_modality/block2/res_conv0/conv_block_norm_0/layer_norm_scale	shape    (512,)              	size    512
INFO:tensorflow:Weight    image_modality/image_modality/block2/sep_conv_block/conv_block_0_single/depthwise_kernel	shape    (3, 3, 256, 1)      	size    2304
INFO:tensorflow:Weight    image_modality/image_modality/block2/sep_conv_block/conv_block_0_single/pointwise_kernel	shape    (1, 1, 256, 512)    	size    131072
INFO:tensorflow:Weight    image_modality/image_modality/block2/sep_conv_block/conv_block_1_single/depthwise_kernel	shape    (3, 3, 512, 1)      	size    4608
INFO:tensorflow:Weight    image_modality/image_modality/block2/sep_conv_block/conv_block_1_single/pointwise_kernel	shape    (1, 1, 512, 512)    	size    262144
INFO:tensorflow:Weight    image_modality/image_modality/block2/sep_conv_block/conv_block_norm_0/layer_norm_bias	shape    (512,)              	size    512
INFO:tensorflow:Weight    image_modality/image_modality/block2/sep_conv_block/conv_block_norm_0/layer_norm_scale	shape    (512,)              	size    512
INFO:tensorflow:Weight    image_modality/image_modality/block2/sep_conv_block/conv_block_norm_1/layer_norm_bias	shape    (512,)              	size    512
INFO:tensorflow:Weight    image_modality/image_modality/block2/sep_conv_block/conv_block_norm_1/layer_norm_scale	shape    (512,)              	size    512
INFO:tensorflow:Weight    image_modality/image_modality/conv0/conv_block_0_single/kernel                  	shape    (3, 3, 3, 32)       	size    864
INFO:tensorflow:Weight    image_modality/image_modality/conv0/conv_block_norm_0/layer_norm_bias           	shape    (32,)               	size    32
INFO:tensorflow:Weight    image_modality/image_modality/conv0/conv_block_norm_0/layer_norm_scale          	shape    (32,)               	size    32
INFO:tensorflow:Weight    image_modality/image_modality/conv1/conv_block_0_single/kernel                  	shape    (3, 3, 32, 64)      	size    18432
INFO:tensorflow:Weight    image_modality/image_modality/conv1/conv_block_norm_0/layer_norm_bias           	shape    (64,)               	size    64
INFO:tensorflow:Weight    image_modality/image_modality/conv1/conv_block_norm_0/layer_norm_scale          	shape    (64,)               	size    64
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_0                                      	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_10                                     	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_11                                     	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_12                                     	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_13                                     	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_14                                     	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_15                                     	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_1                                      	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_2                                      	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_3                                      	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_4                                      	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_5                                      	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_6                                      	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_7                                      	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_8                                      	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/softmax/weights_9                                      	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_0                                   	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_10                                  	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_11                                  	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_12                                  	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_13                                  	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_14                                  	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_15                                  	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_1                                   	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_2                                   	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_3                                   	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_4                                   	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_5                                   	shape    (511, 512)          	size    261632
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_6                                   	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_7                                   	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_8                                   	shape    (510, 512)          	size    261120
INFO:tensorflow:Weight    symbol_modality_8166_512/target_emb/weights_9                                   	shape    (510, 512)          	size    261120
INFO:tensorflow:Total trainable variables size: 16296740

INFO:tensorflow:Global model_fn finished.
INFO:tensorflow:Create CheckpointSaverHook.
2017-07-22 18:46:50.111802: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-22 18:46:50.111909: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-22 18:46:50.111936: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-22 18:46:50.111961: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-22 18:46:50.111982: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-07-22 18:47:03.177599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:09:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
2017-07-22 18:47:03.177737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-07-22 18:47:03.177768: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-07-22 18:47:03.177802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:09:00.0)

Who can tell me why?

-----------------------------
def caption_base():
  """Set of hyperparameters."""
  hparams = common_hparams.basic_params1()
  hparams.hidden_size = 16
  hparams.batch_size = 4096
  hparams.max_length = 32
  hparams.dropout = 0.0
  hparams.clip_grad_norm = 0.  # i.e. no gradient clipping
  hparams.optimizer_adam_epsilon = 1e-9
  hparams.learning_rate_decay_scheme = "noam"
  hparams.learning_rate = 0.1
  hparams.learning_rate_warmup_steps = 4000
  hparams.initializer_gain = 1.0
  hparams.num_hidden_layers = 1
  hparams.initializer = "uniform_unit_scaling"
  hparams.weight_decay = 0.0
  hparams.optimizer_adam_beta1 = 0.9
  hparams.optimizer_adam_beta2 = 0.98
  hparams.num_sampled_classes = 0
  hparams.label_smoothing = 0.1
  hparams.shared_embedding_and_softmax_weights = int(False)

  hparams.add_hparam("filter_size", 2048)  # Add new ones like this.

  hparams.add_hparam("num_heads", 8)
  hparams.add_hparam("attention_key_channels", 0)
  hparams.add_hparam("attention_value_channels", 0)
  hparams.add_hparam("ffn_layer", "conv_hidden_relu")
  hparams.add_hparam("parameter_attention_key_channels", 0)
  hparams.add_hparam("parameter_attention_value_channels", 0)
  hparams.add_hparam("attention_dropout", 0.0)
  hparams.add_hparam("relu_dropout", 0.0)
  hparams.add_hparam("pos", "timing")  # timing, none
  hparams.add_hparam("residual_dropout", 0.1)
  hparams.add_hparam("nbr_decoder_problems", 1)

  hparams.add_hparam("train_vgg", True)
  hparams.add_hparam("context_shape", [196, 512])
  hparams.learning_rate_warmup_steps = 10
  hparams.batching_mantissa_bits = 2

Besides, I passed testCase as below:
class CaptionTest(tf.test.TestCase):

  def _testCaption(self, net):
    batch_size = 3
    image_height = 224
    image_width = 224
    target_length = 7
    vocab_size = 32768
    hparams = caption.caption_base()
    hparams.data_dir = r"/dataset/ms_coco"
    p_hparams = problem_hparams.image_mscoco_tokens(hparams, vocab_size)
    inputs = np.random.random_integers(0, high=255, size=(batch_size, image_height, image_width, 3))
    targets = -1 + np.random.random_integers(
        255, size=(batch_size, target_length, 1, 1))
    with self.test_session() as session:
      features = {
          "inputs": tf.constant(inputs, dtype=tf.float32),
          "targets": tf.constant(targets, dtype=tf.int32),
          "target_space_id": tf.constant(1, dtype=tf.int32),
      }
      model = net(hparams, p_hparams, 0, None, None)
      shadred_logits, _, _ = model.model_fn(features, True)
      logits = tf.concat(shadred_logits, 0)
      session.run(tf.global_variables_initializer())
      res = session.run(logits)
    vocab_size = 34713
    self.assertEqual(res.shape, (batch_size, target_length, 1, 1, vocab_size))

  def testTransformer(self):
    self._testCaption(caption.Caption)

if __name__ == "__main__":
  tf.test.main()

**Comment by lukaszkaiser** [comment]
What problem is that? `image_mscoco` or some other one? With images as input, you need to be careful to use `batch_size_multiplier` or the queues will be empty and there'll be no training example to run on (which is what you might be seeing). It's best to start by running something, e.g., `slicenet` on `image_mscoco` and then slowly replace things one-by-one.

I'm closing for now, feel free to ask more on our discussion group.
