### ISSUE TITLE
tensor2tensor install: what is the suitable tensorflow-gpu version for tensor2tensor 1.15.4?

### ISSUE THREAD

**Issue by zide05** [tensorflow/tensor2tensor#1786]
### Description

i want to install tensor2tensor using  
```
pip install tensor2tensor[tensorflow_gpu] 
```
but got :

```
WARNING: tensor2tensor 1.15.4 does not provide the extra 'tensorflow_gpu'
```
is there a suitable tensorflow-gpu version for tensor2tensor 1.15.4?

**Comment by jh-hello** [comment]
I'm using tensorflow-gpu:1.15.0 and it works.

**Comment by zide05** [comment]
@jh-hello this setting works,  thank you for your reply !
