### ISSUE TITLE
Question about Word Embeddings and Subword Encoding

### ISSUE THREAD

**Issue by brn887** [tensorflow/tensor2tensor#1795]
Hello, as far as I understand, when we use subword encoding, word embeddings are initialized for each subword unit. But I couldn't understand how a word embedding is formed for a token using subword units. Are they concatenated?
Thanks!

**Comment by martinpopel** [comment]
When you use subwords in T2T, no word embeddings are trained/used, only subword embeddings (which may be called word embeddings by someone).
