### ISSUE TITLE
LDC dataset alternative for parsing problem

### ISSUE THREAD

**Issue by agemagician** [tensorflow/tensor2tensor#180]
Does anyone know an alternative dataset for LDC that can work in the parsing problem, since this dataset is not free.

Please, share the dataset name/link as well as a clear steps how did you used it with tensor2tensor.

Thanks a lot for your replies in advance.

**Comment by lukaszkaiser** [comment]
As for freely available data, I only know about a scientific treebank from Elsevier here:
https://github.com/elsevierlabs/OA-STM-Corpus

It might have a slightly different set of annotations and it's not too large, but still, it'd be cool to have it added to tensor2tensor if you wish.

I'll close for now, but for anyone else, please, feel free to add your comments too!
