### ISSUE TITLE
how to use multi GPU on 1 host machine?

### ISSUE THREAD

**Issue by lapolonio** [tensorflow/tensor2tensor#184]
```
PROBLEM=lmptb_10k
MODEL=attention_lm
HPARAMS=attention_lm_moe_large

DATA_DIR=$HOME/t2t_data
TMP_DIR=/data/databases/t2t_datagen
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

# Generate data
t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --num_shards=100 \
  --problem=$PROBLEM

# Train
# *  If you run out of memory, add --hparams='batch_size=2048' or even 1024.
t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --worker_gpu=3 \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR
```

Using the populated worker_gpu value I see in the log that multiple GPUs are recognized however during training I don't see multiple GPUs being used (checking nvidia-smi)

If multiple GPU training is possible on a single machine is it data parallel? (i.e. Are different input batches sent to seperate GPUs then when all batches are done gradients are averaged then synced across GPUs?)

**Comment by martinpopel** [comment]
Have you set `$CUDA_VISIBLE_DEVICES`?
Do you see in the log something like:
```
2017-07-27 15:34:54.100636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1 2
2017-07-27 15:34:54.100655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y Y Y
2017-07-27 15:34:54.100667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y Y Y
2017-07-27 15:34:54.100678: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 2:   Y Y Y
```
?

**Comment by lapolonio** [comment]
No I don't.
What I do see is:
> INFO:tensorflow:datashard_devices: ['gpu:0', 'gpu:1', 'gpu:2']
> INFO:tensorflow:caching_devices: None
> INFO:tensorflow:Doing model_fn_body took 1.790 sec.
> INFO:tensorflow:Doing model_fn_body took 0.838 sec.
> INFO:tensorflow:Doing model_fn_body took 0.787 sec.

**Comment by lukaszkaiser** [comment]
I think that means you're using 3 gpus successfully :). The model is data-parallel across `--worker_gpu` automatically. Your step-time should be a little *slower* than on 1 gpu (because your batch is now 3x larger) and `nvidia-smi` should show they're used. Are they?

**Comment by martinpopel** [comment]
> Your step-time should be a little slower than on 1 gpu

Yes, in my experiments 2 GPUs had about 104% of the one-GPU step-time; 4 GPUs had about 112%.

> (because your batch is now 3x larger)

Is this really the reason? I though the reason is the parallelization overhead.
BTW: Is single-machine multi-gpu parallelization synchronous or asynchronous (HogWild)?
I know that in multi-machine [distributed training](https://github.com/tensorflow/tensor2tensor/blob/master/docs/distributed_training.md) I can choose using `--sync`.

**Comment by lukaszkaiser** [comment]
Yes - in fact we by default do synchronous training nowadays. On a single-machine it's all synchronous. You're right with the overhead, it comes from copying, each gpu has the same computational work as before (same per-gpu batch), but the variables need to sync. 112% on 4-gpu looks quite ok though (It's 400/112% = 3.75x speedup).

**Comment by lukaszkaiser** [comment]
Sorry, 3.57x ...

**Comment by colmantse** [comment]
Sorry, I recently added an additional 1080 ti to have two gpus. However, it now takes double the time to compute the same steps as it was for 1 1080 ti. I checked nvidia smi and it shows both gpus' utility fluctuate around 30% to 70%, it seems the gpus are not being fully utilized. I wonder if this is a setting problem or something else. Would be great if you guys have any lead.
