### ISSUE TITLE
On calculating size of network, GeForce GTX 650 

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#189]
Dear all,

I am using GeForce GTX 650, and I am trying to follow the tutorial to train a model. I lowered the batch_size to like 256 and its still giving me memory error. I am just wondering if there is a way to approximate the memory required for the network running, and if it is a lost cause to use the current GPU to train anything serious with tensor2tensor at all. Thank you all!

Best regards,
Colman Tse

**Comment by lukaszkaiser** [comment]
Checking online, it seems that GeForce GTX 650 has 1GB of RAM and is a Kepler-generation card: to be blunt, I don't think you'll ever be happy trying to do deep learning on it. I think a reasonable minimum is a  GTX 1060, at least it has 6GB of RAM and some speed. I test all our tutorials on a GTX 1080, so it should all run with 8GB, but I also have a 970 with 4GB and things are running there with lower batch size.

**Comment by colmantse** [comment]
Thanks! Guess its time for an upgrade then.
