### ISSUE TITLE
I followed the following guideline to register a new hyperparameter sets,but failed.

### ISSUE THREAD

**Issue by lqfarmer** [tensorflow/tensor2tensor#19]
I followed the following guideline:
******************************************************************
You can currently do so for models, hyperparameter sets, and modalities. Please do submit a pull request if your component might be useful to others.

Here's an example with a new hyperparameter set:

# In ~/usr/t2t_usr/my_registrations.py

from tensor2tensor.models import transformer
from tensor2tensor.utils import registry

@registry.register_hparams
def transformer_my_very_own_hparams_set():
  hparams = transformer.transformer_base()
  hparams.hidden_size = 1024
  ...
# In ~/usr/t2t_usr/__init__.py
import my_registrations
t2t-trainer --t2t_usr_dir=~/usr/t2t_usr --registry_help
You'll see under the registered HParams your transformer_my_very_own_hparams_set, which you can directly use on the command line with the --hparams_set flag.
*************************************************************************
do the same, but I could not find "transformer_my_very_own_hparams_set" from the result, here is the log:

[@nmyjs_160_20 t2t_usr]# t2t-trainer --t2t_usr_dir=~/usr/t2t_usr --registry_help
INFO:tensorflow:
Registry contents:
------------------

  Models: ['attention_lm', 'attention_lm_moe', 'baseline_lstm_seq2seq', 'byte_net', 'diagonal_neural_gpu', 'multi_model', 'neural_gpu', 'slice_net', 'transformer', 'xception']

  HParams (by model):
    * attention: ['attention_lm_base', 'attention_lm_moe_base', 'attention_lm_moe_large', 'attention_lm_moe_small']
    * basic: ['basic_1']
    * bytenet: ['bytenet_base']
    * multimodel: ['multimodel_1p8']
    * neuralgpu: ['neuralgpu_1']
    * slicenet: ['slicenet_1', 'slicenet_1noam', 'slicenet_1tiny']
    * transformer: ['transformer_base', 'transformer_base_single_gpu', 'transformer_big', 'transformer_big_dr1', 'transformer_big_dr2', 'transformer_big_enfr', 'transformer_big_single_gpu', 'transformer_dr0', 'transformer_dr2', 'transformer_ff1024', 'transformer_ff4096', 'transformer_h1', 'transformer_h16', 'transformer_h32', 'transformer_h4', 'transformer_hs1024', 'transformer_hs256', 'transformer_k128', 'transformer_k256', 'transformer_l2', 'transformer_l4', 'transformer_l8', 'transformer_ls0', 'transformer_ls2', 'transformer_parsing_base', 'transformer_parsing_big', 'transformer_tiny']
    * xception: ['xception_base']

  RangedHParams: ['basic1', 'slicenet1', 'transformer_big_single_gpu']

  Modalities: ['audio:audio_spectral_modality', 'audio:default', 'audio:identity', 'class_label:class_label_2d', 'class_label:default', 'class_label:identity', 'generic:default', 'image:default', 'image:identity', 'image:small_image_modality', 'symbol:default', 'symbol:identity']
  
[@nmyjs_160_20 t2t_usr]# ls
__init__.py  my_registrations.py

is there anyone can help me ?

**Comment by rsepassi** [comment]
It may just be the formatting in the GitHub issue, but just to be sure:
the filename should be `__init__.py`, not `init.py`. Could you verify that the file is correctly named? The folder is a standard Python module that is being dynamically imported.

**Comment by rsepassi** [comment]
I see by inspecting the raw issue text that the file is named correctly. My next guess is that you are not using v1.0.5. Please run `pip install --upgrade tensor2tensor`, try again, and report back.

**Comment by lqfarmer** [comment]
thank your, after run pip install --upgrade tensor2tensor, it works.

**Comment by rsepassi** [comment]
Glad it worked. Closing.
