### ISSUE TITLE
Absolute Position Encoding：Why are the two tensors not alternately merged？

### ISSUE THREAD

**Issue by davinca** [tensorflow/tensor2tensor#1925]
https://github.com/tensorflow/tensor2tensor/blob/bafdc1b67730430d38d6ab802cbd51f9d053ba2e/tensor2tensor/layers/common_attention.py#L453

In the orginal paper, the position_embedding is like this:  [..., sin i, cos i, ...]

**Comment by martinpopel** [comment]
See #177 and #1591 (and #1677).

**Comment by davinca** [comment]
just different orderings of the same set of channels,  The effects of both are consistent theoretically.
