### ISSUE TITLE
How to access value of attention weights during prediction?

### ISSUE THREAD

**Issue by xiangyi1900** [tensorflow/tensor2tensor#195]
I am trying to visualize the attention weights in transformer but I don't know where to start. 
The model is quite complicated and built on tflearn which makes it difficult for me to just get an attention weights tensor by name and sess.run() it with proper input (beam search even makes it more involved since I just want the attention values for the best sequence). 
One way of doing it seems to be returning value of attention weights tensors in estimator.predict() but it may require modifying a lot of codes.
Any guidance for getting the attention values or is there a simpler way to get the attention weights during beam search?

**Comment by rsepassi** [comment]
Yes, this is something we'd like to support. Thank you. Merging with #147 (Attention Visualization).
