### ISSUE TITLE
How do you do POS tagging using transformer?

### ISSUE THREAD

**Issue by dixiematt8** [tensorflow/tensor2tensor#199]
I have rewritten my own transformer for POS tagging. It performs very badly. How do you guys train POS tagging using tensor2tensor? I am training POS tagging just to know how much model is good other tasks similar to POS.

**Comment by lukaszkaiser** [comment]
Our parsing problem includes POS tagging (we generate both the constituency tree and the POS tags). Even trained just on Penn Treebank (40k sentences) it's quite good, 9X% tagging accuracy with not too low X. How are you framing your problem?

**Comment by dixiematt8** [comment]
I framed my problem like a translation problem, but I forced the decoder to produce tags that are of the same length as the encoder.

**Comment by lukaszkaiser** [comment]
We did not do that, just used our SubwordTextEncoder. But it's strange it doesn't work for you. In any case, that looks like a more generic ML discussion, maybe suited for our mailing list more than github issues.
