### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by vthorsteinsson** [tensorflow/tensor2tensor#2]
There are some holes in the Python 3 compatibility of the Tensor2tensor code. For instance:

In data_generators/generator_utils.py, `import urllib` needs to be:

```
import sys
if sys.version_info[0] >= 3:
  import urllib.request as urllib
else:
  import urllib
```

In data_generators/image.py, `import cPickle` needs to be:

```
try:
  import cPickle
except ImportError:
  import pickle as cPickle

```
Finally, data_generators/tokenizer.py needs to be revised as it assumes that a char ordinal is always in the range (0, 256), which is not a safe assumption in Python 3. A better solution uses a set instead of array subscripts based on char ordinals. Would you like me to submit a revised version in a pull request?

**Comment by rsepassi** [comment]
Thank you! Yes, please do. The chr assumption may also be in a few other places - e.g. text_encoder.py. Appreciate the help. We're on 2.7 at Google so Python 3 usage isn't as well-exercised/tested.

**Comment by plutusedge** [comment]
Thanks for the info this is helpful

**Comment by vthorsteinsson** [comment]
See PR #22

**Comment by rsepassi** [comment]
PR #22 merged. Thanks!
