### ISSUE TITLE
Slow lstm_seq2seq_attention training

### ISSUE THREAD

**Issue by fstahlberg** [tensorflow/tensor2tensor#205]
I am trying to run the attention-based seq2seq baseline on wmt_ende_tokens_32k by just using

  MODEL=lstm_seq2seq_attention
  HPARAMS=lstm_attention

in the walkthrough. However, training seems to be very slow: the global step/sec rate drops down to around 0.1 on a single K80, and the GPU utility is around 15%. Using a much smaller batch size by adding --hparams='batch_size=32'  to the t2t-trainer command helps a bit but the GPU utility is still around 25%. Am I missing something? Thanks.

**Comment by colmantse** [comment]
I have similar issue, i am sure that my gpu is running but my cpu is also operating on 98%, i wonder if it is normal and it is taking ages as compared with transformer.

**Comment by 2877992943** [comment]
yes ,same to me, compared with transformer with 22 seconds for 100 steps, it took 600 seconds 
 every 100 steps for lstm_attention

**Comment by kolloldas** [comment]
Can you check the latest version? It now uses the `AttentionWrapper` from *seq2seq* library which is much more optimized than the previous implementation. 
For the `translate_ende_wmt_bpe32k` task I'm getting ~5steps/s on a K80

**Comment by rsepassi** [comment]
Thanks @kolloldas!
Transformer will generally be faster.
And hopefully the switch to the seq2seq libs will speed up the LSTM.
Closing for now.
