### ISSUE TITLE
not able to train on a registered problem

### ISSUE THREAD

**Issue by mirkobronzi** [tensorflow/tensor2tensor#208]
Hi,
(not sure this is a bug or a mistake on my side)
I am trying to create some problems and to register them.

As long as I created only one problem, it works fine.
Now that I am adding another problem (registered with another name - in the same python file as the problem above), it works for t2t-datagen, but not for t2t-train.

The error is:
`ValueError: merged_vocab_custom_data_problem not in the supported set of problems:`

Interestingly, I also get the following with `--registry_help`:
Problems: ['algorithmic_addition_binary40', 'algorithmic_addition_decimal40', 'algorithmic_identity_binary40', 'algorithmic_identity_decimal40', 'algorithmic_multiplication_binary40', 'algorithmic_multiplication_decimal40', 'algorithmic_reverse_binary40', 'algorithmic_reverse_decimal40', 'algorithmic_reverse_nlplike32_k', 'algorithmic_reverse_nlplike8_k', 'algorithmic_shift_decimal40', **'custom_data_problem'**, 'image_cifar10', 'image_cifar10_plain', 'image_cifar10_tune', 'image_fsns', 'image_imagenet', 'image_imagenet32', 'image_mnist', 'image_mnist_tune', 'image_ms_coco_characters', 'image_ms_coco_tokens32k', 'image_ms_coco_tokens8k', 'lm_ptb_10k', 'lm_ptb_characters', **'merged_vocab_custom_data_problem'**, 'setimes_mken_tokens_32k', 'wmt_encs_characters', 'wmt_encs_tokens_32k', 'wmt_ende_characters', 'wmt_ende_tokens_32k', 'wmt_ende_tokens_8k', 'wmt_enfr_characters', 'wmt_enfr_tokens_32k', 'wmt_enfr_tokens_8k', 'wmt_zhen_tokens_32k', 'wmt_zhen_tokens_8k']

You can see in bold both the problems - the custom_data_problem, which is working, and the merged_vocab_custom_data_problem, which works only for t2t-datagen (not for t2t-train)

Any idea why this is happening?

Thanks,
Mirko

**Comment by rsepassi** [comment]
My bet is that there's something wrong with your problem's `hparams` method. It should mutate the defaults passed in and return None. The error is misleading because of a bad way of checking whether a problem was registered in the new supported way or the old legacy way by try/excepting a ValueError. Will fix in the next release. Sorry about that. And do let me know if my hunch is correct.

**Comment by mirkobronzi** [comment]
Hi Ryan,
thanks - that may be it.

I am not changing the hparam method though - just inheriting it:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/problem.py#L408

It seems to me this method is already mutating the `defaults `the way I need it, and it is returning `None`.
So, it seems to me it is already fdoing what you suggest to do above.

Am I missing something here?

Thanks,
Mirko

**Comment by mirkobronzi** [comment]
Hi @rsepassi ,
the problem was actually in `feature_encoders` - there was a `ValueError` there, and I suppose this was preventing the code to load the models (thus the 'problem not found' error).
The `ValueError` was caught thus it required some time on my side to find it.

Now I can register/use more than one problem.

Thanks for your help,
Mirko

**Comment by rsepassi** [comment]
Makes sense. I'll fix the error-swallowing in the next release.

**Comment by ghego** [comment]
I'm encountering the same `ValueError: languagemodel_test not in the supported set of problems:` with a problem I defined. What was the solution to this?

**Comment by ghego** [comment]
Solved, it was a config issue

**Comment by soaxelbrooke** [comment]
@ghego What was the config issue? I may be running into the same thing now.

**Comment by soaxelbrooke** [comment]
Figured out the problem I was having: I need to be importing the class from my problem spec python file in `__init__.py`.
