### ISSUE TITLE
SubwordTextEncoder written in Python (not TF)

### ISSUE THREAD

**Issue by ajbouh** [tensorflow/tensor2tensor#214]
Based on my reading of the source, it seems like the Tensor2Tensor wmt_ende_tokens_32k problem can only be performed when the text input has been encoded with SubwordTextEncoder. However, this encoder doesn't seem to have a TensorFlow implementation.

Is my analysis correct? If so, it seems like a TensorFlow implementation is one of the blockers for exporting a usable standalone SavedModel of a trained Transformer model.

**Comment by lukaszkaiser** [comment]
I'm not sure why this would be called a blocker: you need to feed the data into your SavedModel somehow, so you can easily call SubwordTextEncoder.encode before that. Or use tf.py_func to do it in the graph. Implementing string operations in pure TF looks like an exercise in patience, so I don't think we'll be doing this unless there is a strong need that cannot be easily addressed as above.

**Comment by ajbouh** [comment]
Thanks for taking a look. Unfortunately neither of these are compatible
with TensorFlow serving. py_func nodes aren't fully serialized into the
GraphDef/SavedModel and even if they were, TensorFlow serving doesn't have
a Python interpreter available at runtime.

I understand that implementing this in TF alone would be challenging. And
that TensorFlow serving support may be beyond the scope of this project.
Figured I'd at least point out the concern!

**Comment by lukaszkaiser** [comment]
Thanks!
