### ISSUE TITLE
Unable to get unit test running

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#223]
Dear all,

Sorry maybe this is pretty trivial but i have problem running the unit test. I got the log below:

(tensorflow-gpu) L:\python34_colman\tensor2tensor>python tensor2tensor/utils/data_reader_test.py
C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\keras\python\keras\backend.py:3635: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Users\\admen\\.keras\\keras.json' mode='r' encoding='cp1252'>
  _config = json.load(open(_config_path))
C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))

======================================================================
ERROR: testExamplesQueue (__main__.DataReaderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensor2tensor/utils/data_reader_test.py", line 88, in testExamplesQueue
    os.remove(tmp_file_path)
PermissionError: [WinError 32] \u7a0b\u5e8f\u7121\u6cd5\u5b58\u53d6\u6a94\u6848\uff0c\u56e0\u70ba\u6a94\u6848\u6b63\u7531\u53e6\u4e00\u500b\u7a0b\u5e8f\u4f7f\u7528\u3002: 'C:\\Users\\admen\\AppData\\Local\\Temp\\data_reader_testh8s5h2uy\\tmpnzrjvell\\tmpv9j3ne1b'

----------------------------------------------------------------------
Ran 2 tests in 8.394s

FAILED (errors=1)
ERROR:tensorflow:Error removing C:\Users\admen\AppData\Local\Temp\data_reader_testh8s5h2uy: Failed to delete a file: C:\Users\admen\AppData\Local\Temp\data_reader_testh8s5h2uy/tmpnzrjvell/tmpv9j3ne1b

Help would be greatly appreciated!
Thanks,
Colman

**Comment by rsepassi** [comment]
Hmm...the permission issue is odd and might be due to Windows defaults being different.
If you see a problem in the way we're dealing with files that should be different on Windows, let us know. 

Also try `python setup.py test` to run all the tests (in the tensor2tensor code directory).

**Comment by colmantse** [comment]
Thanks I will run the full test and come back. Re-open after I have the result, close for now.

**Comment by colmantse** [comment]
I have tried python setup.py test, is it normal for it to take forever? It has been 4 hrs already, I think it got stuck but cpu shows it is still running.

**Comment by martinpopel** [comment]
For me, Tensor2tensor works great, but `python3 setup.py test` also gets stuck at testCalculusIntegrate (and the two previous tests, AlgebraInverse and AlgebraSimplify, end with ERROR without any details). CPU uses one core for 100%, GPU is unused.
I use Ubuntu 14.04.4, Python 3.4.3, tensorflow 1.2.0, tensor2tensor 1.1.9 (the newest from GitHub).

**Comment by colmantse** [comment]
@martinpopel , I got exactly the same prob. I use window 10, python 3.6, tensorflow 1.3 and t2t 1.1.9

**Comment by rsepassi** [comment]
Please see the `.travis.yml` for the exact commands that are run for the tests.
