### ISSUE TITLE
how to change the train code

### ISSUE THREAD

**Issue by mirkobronzi** [tensorflow/tensor2tensor#225]
Hi all,
given the flexible code (in tensor2tensor) that allows to easily register new problems / hparams / models, I was wondering if there had been any discussion to allow more flexibility with the training process.

E.g., it is not hard to add early stopping, but it requires to change the tensor2tensor code directly.
(instead of using the elegant solution of `--t2t_usr_dir` and `registry` to be able to inject code from some other folder / repository)
Obviously, not duplicating any tensor2tensor code would be preferred given this means there is no problem when updating tensor2tensor.
(while with duplicated code, the duplicated part should be fixed every time)

Any insight w.r.t. how to do that?

Thanks,
Mirko

**Comment by martinpopel** [comment]
My personal opinion: There is a clear and simple interface for problems / hparams / models, which allows to separate the code and inject it from outside and there is low risk that this external code will have to be updated frequently with new versions of t2t.
I am not sure if this is possible with the training process. Maybe it is more desirable (better for users from the long-term point of view) to integrate all enhancements (such as `--early_stopping` option, which should be by default off) to the master (via pull requests).

**Comment by mirkobronzi** [comment]
Thanks @martinpopel - your proposal makes sense.
I'll complete the implementation and follow up - closing the issue for now.

**Comment by lukaszkaiser** [comment]
In the new release 1.2.0 we made it easy to call T2T models from raw session, as in this test:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/trainer_utils_test.py#L96

It can be used for writing your own training loop in a few dozen lines.

**Comment by mirkobronzi** [comment]
thanks for the info @lukaszkaiser  !
