### ISSUE TITLE
How to use with CPU

### ISSUE THREAD

**Issue by haowenli** [tensorflow/tensor2tensor#229]
I am using the transformer model which is an example in README. I haven't NVIDIA card in my computer. How can I use HParams to train transformer model  in README?
 HParams (by model):
    * attention: ['attention_lm_base', 'attention_lm_moe_base', 'attention_lm_moe_large', 'attention_lm_moe_small', 'attention_lm_moe_tiny', 'attention_lm_no_moe_small', 'attention_lm_small', 'attention_lm_translation']
    * basic: ['basic_1']
    * bluenet: ['bluenet_base', 'bluenet_tiny']
    * bytenet: ['bytenet_base']
    * cycle: ['cycle_gan_small']
    * gene: ['gene_expression_conv_base']
    * lstm: ['lstm_attention']
    * multimodel: ['multimodel_base', 'multimodel_tiny']
    * neuralgpu: ['neuralgpu_1']
    * shakeshake: ['shakeshake_cifar10']
    * slicenet: ['slicenet_1', 'slicenet_1noam', 'slicenet_1tiny']
    * transformer: ['transformer_alt', 'transformer_base', 'transformer_base_single_gpu', 'transformer_big', 'transformer_big_dr1', 'transformer_big_dr2', 'transformer_big_enfr', 'transformer_big_single_gpu', 'transformer_dr0', 'transformer_dr2', 'transformer_ff1024', 'transformer_ff4096', 'transformer_h1', 'transformer_h16', 'transformer_h32', 'transformer_h4', 'transformer_hs1024', 'transformer_hs256', 'transformer_k128', 'transformer_k256', 'transformer_l10', 'transformer_l2', 'transformer_l4', 'transformer_l8', 'transformer_ls0', 'transformer_ls2', 'transformer_moe_1b', 'transformer_moe_base', 'transformer_n_da', 'transformer_n_da_l10', 'transformer_no_moe', 'transformer_parameter_attention_a', 'transformer_parameter_attention_b', 'transformer_parsing_base', 'transformer_parsing_big', 'transformer_parsing_ice', 'transformer_small', 'transformer_tiny', 'transformer_vae_base', 'transformer_vae_small']
    * xception: ['xception_base', 'xception_tiny']

**Comment by martinpopel** [comment]
Without GPU, the training (and decoding) will be **very slow**, even when using a fast CPU with e.g. 32 cores. I would suggest to use some of the toy problems (algorithmic). If you really want to try machine translation, use `transformer_tiny` and the [TranslateEndeWmt8k](https://github.com/tensorflow/tensor2tensor/blob/8f3a7fde44b2f17592f46c1a97848c6863f2629a/tensor2tensor/data_generators/wmt.py#L385) problem (which used to be called `wmt_ende_tokens_8k` in older t2t versions), which is likely to train fast (but with lower final BLEU, of course). If TensorFlow does not find a GPU, it automatically switches to CPU.
