### ISSUE TITLE
multilingual translation task, usage

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#235]
Redirected to here.

**Comment by colmantse** [comment]
I do not see any registered problems ended with rev, does that mean adding _rev will allow reverse training in t2t-trainer? and linking problems with - will allow the model to include the data of the problem specified? thank you very much.

**Comment by colmantse** [comment]
or is it intended for the t2t-datagen first.

**Comment by colmantse** [comment]
Hi @martinpopel, it is however unfortunate i have not been able to locate any _rev translation task in t2t-trainer 's registry_help, nor were the t2t-datagen successful in recognizing any translation task ended with _rev. would be great if you could advice further. 

many thanks!

**Comment by colmantse** [comment]
Hi @martinpopel, it is however unfortunate i have not been able to locate any _rev translation task in t2t-trainer 's registry_help, nor were the t2t-datagen successful in recognizing any translation task ended with _rev. would be great if you could advice further.

many thanks!

**Comment by lukaszkaiser** [comment]
You can reverse any generated data by adding `_rev` -- it doesn't show in the registry (maybe it should) and it doesn't require `t2t-datagen`, it's all done in `t2t-trainer`.

**Comment by colmantse** [comment]
oh okay, thank you very much! (maybe a reminder will do)
