### ISSUE TITLE
adapt code to predict vector targets instead of float/int/str

### ISSUE THREAD

**Issue by silky** [tensorflow/tensor2tensor#237]
hello

so i've been keen to try and use tensor2tensor to convert between say wav and arbitrary vector sequences such as:

```
targets = [ [0.1,0.2], [2.432,3.44], [-0.13,4.001], ... ]
```

now, this doesn't work. basically because all data must either by a simple list of ints, floats or a list of strings.

why is this so? am i missing something?

**Comment by lukaszkaiser** [comment]
We use the `wave` module from python when reading wav files, and save the data in already converted format. See here:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/audio.py#L88

I'll close this for now, but don't hesitate to re-open or ask more!

**Comment by silky** [comment]
sorry; maybe i wasn't clear, but yes, i already use that on the _inputs_ side, i was asking about the _targets_ ...

**Comment by lukaszkaiser** [comment]
Ah. For now the easiest thing, I think, it to make them a single list of floats and later, e.g. in the preprocessing function in your `Problem` class, call `tf.reshape` to make a list-of-lists from the single list. That assumes one dimension is constant in the lists, but that's often the case.

**Comment by silky** [comment]
alright cheers for that
