### ISSUE TITLE
Couldn't register a new problem

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#238]
Hi, I used `t2t-trainer --t2t_user_dir=<where my __init__.py lies> --registry_help` to try to register a new problem, which is just a translation problem mimicking wmt with my new data. However, after I ran that command I didn't see my problem registered under the "Problems" category. Did I do it right? Or should I use `t2t-datagen` to register a new problem? Also, after a problem is registered (which in my case merely contains a new dataset), how should one proceed to train the model? And how does one remove a custom problem from registry? Thanks!
My tensor2tensor version is 1.1.9.

**Comment by anglil** [comment]
Also, it seems that in the walkthrough the problem id should be translate_ende_wmt32k instead of wmt_ende_tokens_32k.

**Comment by colmantse** [comment]
its --t2t_usr, not --t2t_user_dir

**Comment by martinpopel** [comment]
> it seems that in the walkthrough the problem id should be translate_ende_wmt32k instead of wmt_ende_tokens_32k.

Yes, #232 fixes this, but no one merged it yet.

**Comment by lukaszkaiser** [comment]
Sorry for the delay, merged!

**Comment by zoezhu** [comment]
Followed steps in doc "T2T: Train on Your Own Data", I ran `t2t-trainer --registry_help`
 ,but I still cannot see "word2def" in the list, can anyone give me more details? Thanks!

My steps:
(1) Install tensor2tensor, the path is "/anaconda/envs/zz_tf/lib/python2.7/site-packages".
(2) Go to file "/anaconda/envs/zz_tf/lib/python2.7/site-packages/tensor2tensor/data_generators", create a file named "word2def.py".
(3) Copy codes from https://github.com/tensorflow/tensor2tensor/blob/master/docs/new_problem.md to "word2def.py", save it.
(4) Run `t2t-trainer --registry_help`

What did I miss or what I did wrong? Thanks!
My tensor2tensor version is 1.2.7.

**Comment by martinpopel** [comment]
Instead of putting `word2def.py` to data_generators/ I suggest to put in in your own directory and register it as described in https://github.com/tensorflow/tensor2tensor/blob/master/docs/walkthrough.md#adding-your-own-components

Someone should update new_problem.md to reflect this best practice.
