### ISSUE TITLE
why does the 'bottom' and 'bottom_targets' always input _x_ as a tensor of int32s?

### ISSUE THREAD

**Issue by silky** [tensorflow/tensor2tensor#239]
my expectation would be that this input _x_ would be based on whatever modality i'm pushing data in by

but i find that it is always int32. this seems quite problematic to me given that i've pushed my data in as a list of floats?

i feel like i must be missing something ...

thanks!

**Comment by lukaszkaiser** [comment]
Does it really? Can it be that we just forgot to update the docs?

**Comment by silky** [comment]
i believe that it really does, insofaras i get type mismatches unless i do `tf.to_float(x)` ... in the respective functions

when i have some time next week i'll try and write a test case; sorry for the half-baked bug reports, i've been trying to use this in anger.

**Comment by lukaszkaiser** [comment]
We have RealModality that's used in genomics models:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/layers/modalities.py#L478

So it must have worked somehow. We're also working on documenting the interface from Problem through Modality to T2TModel and then back. PRs are always welcome!

**Comment by silky** [comment]
yes, i directly used the `RealModality`; that's the one that was problematic.

**Comment by rsepassi** [comment]
Currently the input format from disk is determined by Problem.example_reading_spec which defaults to int64 (and all int64s get converted to int32s in the input_pipeline). You can override the method in your Problem subclass. Maybe we should have the example_reading_spec be based on the specified modality - would welcome a PR if you'd like to try.
