### ISSUE TITLE
Word matrix visualization using Tensorboard

### ISSUE THREAD

**Issue by kevinlu1211** [tensorflow/tensor2tensor#241]
Hello, 
I was wondering if there was support to visualize the word embedding matrix using Tensorboard. As when I use Tensorboard with the models, the word embeddings aren't shown.

**Comment by colmantse** [comment]
maybe you want to go here [https://github.com/tensorflow/tensorboard](url)

**Comment by martinpopel** [comment]
A better link is https://www.tensorflow.org/get_started/embedding_viz
I can see this in TensorBoard for t2t models, but the labels are just the integer IDs.
Note that the best t2t translation models use subwords (not words), so we can have only subword embeddings.
I guess it should be possible to add an option to t2t to save also the subword strings (in addition to IDs) to the graph.

Personally, I would rather like to see the self-attention visualization for individual sentences as discussed in #147.

**Comment by lukaszkaiser** [comment]
An iPython notebook with our viz code is included in the new release 1.2.0, give it a try!

**Comment by hkhatod** [comment]
how about the link to this ipython notebook. Thanks

**Comment by martinpopel** [comment]
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/visualization/TransformerVisualization.ipynb
