### ISSUE TITLE
using more than one feature type

### ISSUE THREAD

**Issue by mirkobronzi** [tensorflow/tensor2tensor#247]
Hi all,
I was trying to use more than one kind of features for a problem.
E.g., the token id (to become embeddings) + a binary feature associated to every token.

To this end, I tried to modify the problem input modality, i.e.,
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/problem.py#L438
adding another feature such as
`new_binary_feature = (registry.Modalities.GENERIC, 1)`

...then I declare the feature type in  `example_reading_spec`:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/problem.py#L177

..and finally the `generator `method will generate these features as well:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/problem.py#L362

Once in the model input function, I am able to see the new feature now, e.g., in
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py#L43
`features `will now contain the new feature - but only if the new feature format is int64 (as the input).

Indeed, otherwise I have problems in input_fn_builder, i.e.,
https://github.com/tensorflow/tensor2tensor/blob/2958ac1214906062ff85428284709eeb77f36ae0/tensor2tensor/utils/input_fn_builder.py#L31

looking at this function, it would seem that it is somehow hard-coded to deal with `inputs `and `targets` only (but I may be wrong on this).

So, I was wondering if you have an idea on how to make this work in the 'cleanest' way - i.e., how to be able to use features in addition to the token id (that will become an embedding) without duplicating / modifying the tensor2tensor code directly.

Thanks,
Mirko

**Comment by mirkobronzi** [comment]
forgot to mention I had to change:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/input_fn_builder.py#L69
in order to have the new features to pass through.
(this is also the part I do not like of the setup - given I have to duplicate this code and change it)

**Comment by rsepassi** [comment]
You're very right - T2T doesn't do a good job right now of supporting multiple input features. Most things expect just "inputs" and "targets". We'd like to support more, probably by adding more hooks to the Problem class or something like that. We'd welcome a PR.

**Comment by mirkobronzi** [comment]
thanks @rsepassi - I think I am close to have something done for data preparation / training.
(still some minor refactoring todo)

But I noticed that the pipeline is somehow different when evaluating (which makes sense - given you generate all the features on the fly from a file, instead of using the `t2t-datagen` command), so, I will need to change that part as well.

**Comment by franckbrl** [comment]
@mirkobronzi Have you finally made it?

**Comment by mirkobronzi** [comment]
hi @franckbrl - yes.
I think with the new version of the code it should be easier (not sure though - cause I modified the code a little while ago), in the sense that if you add features they will 'pass trough' the pipeline, and reach your models.
Obiviously, you need to modify the models to use these new features.
(otherwise they are just ignored)

Hope it helps.

**Comment by franckbrl** [comment]
Thank you @mirkobronzi ! I tried my best and made a PR #703 .
