### ISSUE TITLE
t2t-trainer: command not found

### ISSUE THREAD

**Issue by tb25** [tensorflow/tensor2tensor#25]
I have run into some issues installing on my GPU with Ubuntu 14.04.5. it reaches the
 `Installing collected packages: mpmath, sympy, tensor2tensor` line and then there is a permission denied error. 
<img width="940" alt="screen shot 2017-06-22 at 1 11 05 pm" src="https://user-images.githubusercontent.com/23270649/27446633-50a9bae6-574c-11e7-84e4-7f102f70d1ab.png">

I tried pip installing each individual error into the directory specified and then it said that everything was installed, but the `t2t-trainer --registry_help` did not work. 

this step works fine on my CPU but I also run into the known issue of downloading the dataset.

**Comment by vthorsteinsson** [comment]
The Ubuntu user doing the install must have write permission on the `/usr/local/bin/` directory.

**Comment by stefan-it** [comment]
In case that you're not using a virtual python environment (like `virtualenv` or `anaconda`) it seems that you're trying to install `tensor2tensor` with a non-priviliged user account (which leads to the permission denied message). So you could install `tensor2tensor` on Ubuntu with `sudo pip install tensor2tensor` - or, if you do not want to install it system-wide - use `pip install --user tensor2tensor` (but then you have to adjust your `$PATH` variable to find the `t2t-*` scripts.

**Comment by tb25** [comment]
Thank you all, that advice helped. It is working now!
