### ISSUE TITLE
what's the relationship between moe and decode ensemble model in transformer model?

### ISSUE THREAD

**Issue by njuzrs** [tensorflow/tensor2tensor#251]
I observe the 'transformer_moe.py' file and read the paper about moe (mixture of experts). moe trains the model with an ensemble layer in both encode and decode parts. It is different from the ensemble model when decode (train multi-models and average the probability every step of decode). Is there any relationship between the two ways? Do they work independently? or could I understand that the ensemble model of decoding is a special case of moe?

**Comment by lukaszkaiser** [comment]
There is a fundamental difference: a MoE model only runs 1 or 2 paths through the graph (experts), while an ensemble model runs them all and averages. It can be worthwhile to do ensembles of MoE models too, but of course ensembles are costly, while MoE can be computationally very efficient.

These are all interesting things to discuss, but I'd suggest to use our discussion group (https://groups.google.com/forum/#!forum/tensor2tensor) for that and keep this for issues with the code. Thanks!
