### ISSUE TITLE
How to pass a command line parameter in t2t-datagen to a custom problem

### ISSUE THREAD

**Issue by herbakamil** [tensorflow/tensor2tensor#259]
I have registered the custom problem (via --t2t_usr_dir) but the problem that underlying dataset has multiple versions. I wanted to pass them as a tensorflow flag

tf.flags.DEFINE_string("gen_input_dir", "", "input dir for gendir")
but when I run t2t-datagen it's not propagated even though I pass it as a command line parameter.

Is there any nice way to do that?

Currently probably I'll resolve to single hardcoded path which will be symbolic link to changing dataset folder but maybe there's some cleaner solution?

**Comment by rsepassi** [comment]
Yes, currently flag parsing happens before the t2t_usr_dir import and so the flag isn't available. 

Could you try calling `tf.flags.FLAGS._parse_flags(args=sys.argv[1:])`?
This is normally called once on program start, but maybe re-calling would be alright. 
Let me know how it goes and if it seems to work alright, I can add it in or you can send a PR.

**Comment by martinpopel** [comment]
An alternative solution: create two problems, one as a subclass of the other, overriding only the dataset_version (or gen_input_dir or whatever) property.

**Comment by rsepassi** [comment]
agreed that this would be nicer.

**Comment by herbakamil** [comment]
Actually I'd prefer the first solution because it gives flexibility - I can provide any directory I want and don't need to create subclass for a new directory. When I have time (currently I just use the hack which I've described before and have things with higher priority at work) I'll check if it works correctly for my use case.

**Comment by mirkobronzi** [comment]
@herbakamil same problem here - fixed somehow like you, but instead of a fixed pointer to a folder (whose content may change to provide different data), my fixed pointer is to a config.yaml file, containing all the necessary parameters...

**Comment by rsepassi** [comment]
Closing as this is not functionality we plan on adding.
