### ISSUE TITLE
If each of source and target has a vocab, how to name these vocabs?

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#262]
Currently there is one targeted_vocab_size and one vocab_name field in Text2TextProblem. If one decides to create a vocab for each of the source and the target texts, should he create a new problem class, or is there any way to use text2textproblem?

**Comment by lukaszkaiser** [comment]
You can use Text2TextProblem and just override `feature_encoders`, see e.g. here:
https://cs.corp.google.com/piper///depot/google3/third_party/py/tensor2tensor/data_generators/wmt.py?l=456

One day we should make this cleaner in the base class, a PR is welcome, but for now it should be easy enough to work around, so I'll close this. Feel free to reopen if you have any trouble!
