### ISSUE TITLE
whether to byte-pair encode test data?

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#264]
If bpe is used for the training and dev sets, when doing decoding using t2t-decoder, does one need to byte-pair encode the test data first before feeding it into the decoder? Or just need to feed the raw test text into the decoder?

**Comment by mehmedes** [comment]
Yes, you will need to tokenize and apply BPE.
While tokenizing make sure you use the same tokenizing code you tokenized your training data with.

This how I prepare my text for decoding (EN->DE engine)
```
SRC=en
MOSES=/home/mehmedes/tensor2tensor/processing/moses-scripts
SUB=/home/mehmedes/tensor2tensor/processing/subword-nmt

$MOSES/scripts/tokenizer/tokenizer.perl -q -l $SRC -threads 8 | \
$SUB/apply_bpe.py -c bpe.32000 
```

**Comment by anglil** [comment]
Sorry for reopening it because I encountered a problem using the solution above. @mehmedes , it seems that the bpe used by subword-nmt used a different delimiter (i.e. "@@") than the one used in tensor2tensor (i.e. "_"). Is possible to use something that comes with tensor2tensor for bpe, so that there won't be such a delimiter conflict and maybe some other trivialities?

**Comment by lukaszkaiser** [comment]
It is best to just use the default T2T tokenizer, as the downloaded BPE is fundamentally not reversible and so cannot be used for end-to-end pipeline.

**Comment by anglil** [comment]
@lukaszkaiser For bpe-ed test data, the MT hypothesis is also going to be bpe-ed. I'm wondering what the standard procedure is in tensor2tensor to un-bpe the MT hypothesis?

**Comment by martinpopel** [comment]
@anglil: The T2T standard procedure is to use `text_encoder.SubwordTextEncoder` (applied in all `translate_*` problems except `TranslateEndeWmtBpe32k` and the character-based ones). This way the user does not have to care about manually BPEing the input data - all data (training, dev, test) is tokenized to the subwords automatically and all outputs are automatically detokenized.

**Comment by anglil** [comment]
@martinpopel Thanks!
