### ISSUE TITLE
summarize_cnn_dailymail32k Error Fix

### ISSUE THREAD

**Issue by agemagician** [tensorflow/tensor2tensor#271]
File:
cnn_dailymail.py

Error:
    dailymail_file = generator_utils.maybe_download_from_drive(
        tmp_dir, dailymail_filename, _CNN_STORIES_DRIVE_URL)

Correction:
    dailymail_file = generator_utils.maybe_download_from_drive(
        tmp_dir, dailymail_filename, _DAILYMAIL_STORIES_DRIVE_URL)

**Comment by lukaszkaiser** [comment]
Yes, I already corrected this in internal repo, will go out with 1.2.2. Thanks for noticing!
