### ISSUE TITLE
Does the decoder evaluate with the model at the checkpoint with the best BLEU so far?

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#279]
Does the decoder evaluate with the model at the checkpoint with the best BLEU so far, or the latest model, or take some sort of average? Thanks!

**Comment by martinpopel** [comment]
When you use `t2t-decoder --output_dir=train/xy`, T2T searches for `train/xy/checkpoint` file, which specifies which model to use.
If you just stop training without modifying the `checkpoint` file, it references the latest model.
If you run `t2t-decoder` while training is still in progress, it may happen that each batch will be translated with different model (as newer models appear in the directory), thus I suggest to copy the model you want to evaluate to a separate directory first.

**Comment by anglil** [comment]
@martinpopel I see. Thank you! Btw, does tensor2tensor keep track of the model (not necessarily the latest) that has the highest BLEU (in the case of MT) on the dev set. If so, how to invoke this functionality?

**Comment by lukaszkaiser** [comment]
Currently there is no functionality to do that. Instead, we usually average multiple last checkpoints, that brings good results too.
