### ISSUE TITLE
how to use an existing model to decode in wmt problem

### ISSUE THREAD

**Issue by cshanbo** [tensorflow/tensor2tensor#28]
I trained the wmt transformer_base model,  and see some model checkpoints like.
```
-rw-rw-r-- 1 public public         24 Jun 23 09:47 model.ckpt-55975.data-00000-of-00002
-rw-rw-r-- 1 public public 1320167432 Jun 23 09:47 model.ckpt-55975.data-00001-of-00002
-rw-rw-r-- 1 public public      10449 Jun 23 09:47 model.ckpt-55975.index
-rw-rw-r-- 1 public public   24328177 Jun 23 09:47 model.ckpt-55975.meta
-rw-rw-r-- 1 public public         24 Jun 23 09:57 model.ckpt-56426.data-00000-of-00002
-rw-rw-r-- 1 public public 1320167432 Jun 23 09:57 model.ckpt-56426.data-00001-of-00002
-rw-rw-r-- 1 public public      10414 Jun 23 09:57 model.ckpt-56426.index

```

There are 2 questions:
1. The model.ckpt-xxxx.data-00001-of-00002 is the saved model?
2. how to specify the model to use when decoding? I looked at the demo experiment in the `readme.md`, to see that the --model param is set to `transformer`, which I thought should be set to a specific model file. Will t2t-trainer automatically use the latest checkpoint of saved model?
```

DECODE_FILE=$DATA_DIR/decode_this.txt
echo "Hello world" >> $DECODE_FILE
echo "Goodbye world" >> $DECODE_FILE

BEAM_SIZE=4
ALPHA=0.6

t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --train_steps=0 \
  --eval_steps=0 \
  --decode_beam_size=$BEAM_SIZE \
  --decode_alpha=$ALPHA \
  --decode_from_file=$DECODE_FILE
```

**Comment by rsepassi** [comment]
It will automatically restore from the latest checkpoint in `--output_dir`. If you want to use a checkpoint other than the latest one, the simplest thing you could do is to move the checkpoints you don't want to use out of the directory.

**Comment by lukaszkaiser** [comment]
To make it clear: the checkpoint to use is specified in the first line of the "checkpoints" file (that's the literal file name) in the directory specified by `--output_dir`, which should be your $TRAIN_DIR.
