### ISSUE TITLE
question about buckets

### ISSUE THREAD

**Issue by mirkobronzi** [tensorflow/tensor2tensor#288]
Hi all,
in the old seq2seq code ( https://www.tensorflow.org/tutorials/seq2seq ) there were buckets in order to specify the length of utterances for encoder and decoder (predictions).
I remember that utterances were allocated in the smallest bucket able to 'contain' them.

In tensor2tensor I do not see an explicit option to specify buckets - looking at the code, it would seem that utterance with similar length are clustered in the same minibatch (and padded if needed).

Does this means that buckets are generated by the code itself, possibly by looking at the utterance lengths?
If so, what happens if there is a very long utterance at decoding time? (and at training time we only observed relatively short ones?)

Thanks,
Mirko

**Comment by rsepassi** [comment]
Buckets are determined [here](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/data_reader.py#L229) and examples are routed to the buckets based on their lengths.

The model will still decode sequences longer than it has seen at training time, but it probably won't be as good on them.

**Comment by mirkobronzi** [comment]
Thanks @rsepassi
