### ISSUE TITLE
error in 1.2.1

### ISSUE THREAD

**Issue by vince62s** [tensorflow/tensor2tensor#291]
when running the translate_ende_wmt32k

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 462, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <type 'dict'> to Tensor. Contents: {'inputs': <tf.Tensor 'SparseToDense:0' shape=(?,) dtype=int64>, 'targets': <tf.Tensor 'SparseToDense_1:0' shape=(?,) dtype=int64>}. Consider casting elements to a supported type.

**Comment by xujunrt** [comment]
我也遇到这个问题，但是我使用tensorflow1.3版本，这个问题就解决了

**Comment by vince62s** [comment]
right same mistake, different machine.
