### ISSUE TITLE
 "z" as module body output doesn't take "inputs" into consideration. Why?  

### ISSUE THREAD

**Issue by cuiyong0915** [tensorflow/tensor2tensor#306]
https://github.com/tensorflow/tensor2tensor/blob/37465a1759e278e8f073cd04cd9b4fe377d3c740/tensor2tensor/models/transformer_vae.py#L312

**Comment by cuiyong0915** [comment]
By the way, is there a related paper or reference for transformer_vae. Seems ae_decompress is difficult to be understood. Thanks!

**Comment by lukaszkaiser** [comment]
Hi @cuiyong0915 ! This model is an ongoing work that I play with for research. It doesn't really work for any task at the moment, I'm playing with autoencoding research. It's changing a lot and has a lot of dirty parts as I'm investigating it, but I saw no reason to keep it closed-source or hide in any way. I think it's not worth putting too much time into trying to understand it at the moment -- if sth works, I'll clean it up, if not, I'll just remove it. Hope that helps!

**Comment by cuiyong0915** [comment]
@lukaszkaiser Got it. Thanks for your reply!
