### ISSUE TITLE
how to run binaries without sudo privileges?

### ISSUE THREAD

**Issue by mariru** [tensorflow/tensor2tensor#308]
When I do 
```
pip install tensor2tensor[tensorflow] --user
t2t-trainer --registry_help
```
on a unix machine, I get the error
```
t2t-trainer: command not found
```
Where do I find the binaries and what do I need to do to run them?

**Comment by rsepassi** [comment]
This seems to be an issue with your `PATH`. I'd recommend using [`virtualenv`](https://virtualenv.pypa.io/en/stable/), or inspect your `PATH` and make sure that pip's user dir is in there (usually `~/.local/bin`.
