### ISSUE TITLE
t2t-datagen incompatibility with python 2.7 : TypeError: split() takes no keyword arguments

### ISSUE THREAD

**Issue by ghpu** [tensorflow/tensor2tensor#310]
File "data_generators/generator_utils.py", line 415, in generate 
 parts = line.split("\t", maxsplit=1)
TypeError: split() takes no keyword arguments

Also concerns data_generators/wmt.py line 117

Solution : replace by :  parts = line.split("\t", 1)

**Comment by rsepassi** [comment]
Thanks for pointing out. Will be fixed in the next release.
