### ISSUE TITLE
t2t-decoder error

### ISSUE THREAD

**Issue by haowenli** [tensorflow/tensor2tensor#319]
Command  not found,when I input t2t-decoder.

**Comment by martinpopel** [comment]
Update to T2T v1.2.1 or higher. [t2t-decoder](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/bin/t2t-decoder) is in the same path as `t2t-datagen` and `t2t-trainer`, which should be in $PATH if installed correctly (e.g. with `pip`).

**Comment by colmantse** [comment]
type python path/t2t-decoder

**Comment by haowenli** [comment]
but i can't find t2t-decoder directory

**Comment by colmantse** [comment]
it is located at bin at your installed tensor2tensor directory

**Comment by rsepassi** [comment]
After a pip install it should be in your path. take a look at the github repo for the source code, including the setup.py that actually installs the scripts.
