### ISSUE TITLE
Support framework to plug-in generative adversarial networks 

### ISSUE THREAD

**Issue by redknightlois** [tensorflow/tensor2tensor#32]
There are like a hundred GANs out there, would be great if you can also provide a general framework to standarize the typical GAN parts into tensor2tensor

**Comment by lukaszkaiser** [comment]
It would be good indeed, we welcome a contribution!

**Comment by vlnguyen92** [comment]
I'm on this.

**Comment by rsepassi** [comment]
You can see how [CycleGAN](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/cycle_gan.py) is implemented within Tensor2Tensor. Closing but please reopen if you plan to work on this.
