### ISSUE TITLE
Decoding did not generate any output

### ISSUE THREAD

**Issue by flynnwang** [tensorflow/tensor2tensor#326]
Hi there,

I am trying to use transformer model for a text summarization task. the training seems go well, but decoding did not give me any output. 

the problem definition and Tensorboard results is at [this gist url](https://gist.github.com/flynnwang/7cb2813df8a106cd5b2e77105d114f15).

and my command for training and decoding:

for training:
`
t2t-trainer --generate_data --train_steps=35000 --eval_steps=1000 --save_checkpoints_secs=3600 --keep_checkpoint_max=10 --t2t_usr_dir=~/problem/src --data_dir=~/problem/data --problems=my_problem --model=transformer --hparams_set=transformer_my_problem _hparams_set --output_dir=~/problem/out
`

for decoding:
`
t2t-decoder --t2t_usr_dir=~/problem/src --data_dir=~/problem/data --problems=my_problem --model=transformer --hparams_set=transformer_my_problem_hparams_set --output_dir=~/problem/out --decode_hparams="beam_size=4,alpha=0.6" --decode_from_file=/home/flynn/problem/data/dev.src
`

I'm sure there is not empty target in my training data. So the empty output for all the decoding file is not expected. Please help me if you see anything wrong. Thanks!

**Comment by rsepassi** [comment]
It’d be helpful if you provide the following:
Output of ls in the output_dir
Output of the t2t-decoder command

**Comment by rsepassi** [comment]
Sorry for the delay. Is this still an issue with recent releases?

**Comment by flynnwang** [comment]
seem it's not a say for you to debug. I'll try new version and see. Thanks!
