### ISSUE TITLE
Data Importer: Faces in the wild

### ISSUE THREAD

**Issue by redknightlois** [tensorflow/tensor2tensor#33]
[up-for-grabs] maybe?

**Comment by lukaszkaiser** [comment]
Yes, it would be great to have it. Are you thinking of making a PR?

**Comment by redknightlois** [comment]
@lukaszkaiser, step by step. Let me figure out if I can make tensor2tensor work on Windows first. Some time ago I had a very hard time making tensorflow work; granted the support for windows was brand new (a few days after release).

**Comment by lukaszkaiser** [comment]
Hopefully the instructions for TensorFlow on Windows are better now :). tensor2tensor is pure python, that should make things easy. I'm closing this issue for now, open new ones if you see problems!
