### ISSUE TITLE
Is there a change log somewhere for the project?

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#334]
Hi, I'm wondering if there is a change log to the repository maintained somewhere? It would be helpful to me as I'm deciding on whether to update from 1.2.1 to 1.2.4 while having several projects developed within 1.2.1. Thanks.

**Comment by martinpopel** [comment]
see https://github.com/tensorflow/tensor2tensor/releases
and for more details #325, #318, #290 etc. (see [closed PR](https://github.com/tensorflow/tensor2tensor/pulls?q=is%3Apr+is%3Aclosed])).
