### ISSUE TITLE
How to change the modality of seq2seq problems to be 4-dim?

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#335]
It looks like the modality of language related problems accepts input to Transformer encoder only in 3d, i.e. [batch_size, sent_len, emb_dim]. To make the architecture work for 4d input, should I register a new modality? Also should I register a new model that uses 2d attention in the encoder?

**Comment by anglil** [comment]
Do I need to register a new problem or is there any way to change wmt.TranslateProblem's input and target modalities?

**Comment by rsepassi** [comment]
Currently if you run one of the Translate problems with the Transformer model, the output of the modality is 4D, and the Transformer model then flattens it to 3D (https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py#L62). 

If you want a model that operates on 4D Tensors, you'll want to implement a new model.
