### ISSUE TITLE
When registering a new hparam, is it possible to pass arguments to the registration function?

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#336]
For example, when doing hyperparamter tuning, if each set of hyperparameter needs a hparam registration  function, then writing them all out would be a pain because of the exponentially many combinations. I'm wondering if it is possible to write a generic registration function to which one can pass arguments? Thanks.

**Comment by lukaszkaiser** [comment]
I'm not sure I understand what you mean. For hyperparameter tuning, we support hyperparameter ranges in addition to single configs, so you can define a range like here:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py#L907

If you just want to override some hparams on the command line, you can simply specify `--hparams=...` and it'll override the setting of any hparam. Or did you mean something else entirely? Let us know!

**Comment by martinpopel** [comment]
I see how to define hyperparameter ranges, but I am not sure how to use them.
Is it possible to add a simple usage example, e.g. to the [walkthrough wiki](https://github.com/tensorflow/tensor2tensor#adding-your-own-components)?

**Comment by anglil** [comment]
Thanks @lukaszkaiser . I saw that particular example that you pointed to but didn't understand what it does. Now I understand. Thanks!

**Comment by lukaszkaiser** [comment]
The hyperparameter tuning in TF is still evolving, that's why we don't have a fixed example for now. We'll keep in mind adding it, I'll close this for now as it's more dependent on upstream TF at this point.
