### ISSUE TITLE
How to use all the validation data 

### ISSUE THREAD

**Issue by chenwangliangguo** [tensorflow/tensor2tensor#341]
When training my model with 8000 sentence pairs for validation, I found the code only sample a small size of validation data for ValidationMonitor. I want to use all the 8000 pairs to evaluate the model every time, so how can I do that?

The option eval_steps is the number of times for sampling evaluation data, but every time it only sample less than 30 pairs

**Comment by martinpopel** [comment]
> The option eval_steps is the number of times for sampling evaluation data, but every time it only sample less than 30 pairs

Are you sure? I think by increasing 'eval_steps', you can cover the whole dev set. If you set it too high, you will see a warning that no more data is available (but everything works OK). You can also divide the size of your dev set **in subwords** by the batch_size to assess how many eval_steps you need. The question is how to know the exact size of dev set in subwords.

**Comment by colmantse** [comment]
Hi, I am not sure if I have understood correctly, but I thought eval_steps does not apply to validation data? it is just sampling from training data ? for validation data, we need to use t2t-decoder?

**Comment by martinpopel** [comment]
In [wmt.py](https://github.com/tensorflow/tensor2tensor/blob/c34d16cc5244a9a560e82b24d1dfb6c8d5f136a3/tensor2tensor/data_generators/wmt.py#L190-L210) (or your own problem specification), you define a *train* set and a *dev* set. The latter is used for the internal evaluation.

**Comment by rsepassi** [comment]
Thank you @martinpopel. @colmantse, @martinpopel is correct. Increase `--eval_steps`.
