### ISSUE TITLE
Would t2t support multiple CPUs in future?

### ISSUE THREAD

**Issue by alexwwang** [tensorflow/tensor2tensor#342]
T2T is really a fabulous DNN models structure, convenient and super. Unfortunately I find its binary does not support multiple CPUs, which means that only ONE of my 32 kernels would be utilized for training.

I wonder if any possible in the near future, this feature would be added in?
With great appreciation.

**Comment by martinpopel** [comment]
T2T works on 32 CPU cores without any problems for me, similarly as any Tensorflow app. That said, training (and decoding) on GPU is much faster.

**Comment by rsepassi** [comment]
@martinpopel is correct. T2T uses TensorFlow and TensorFlow on CPU will use all available CPU cores to execute ops.

**Comment by alexwwang** [comment]
I don't see if this is a default behavior since it's only one CPU utilized during the data gen procedure. And where could I get more detailed documents about using multiple CPUs in t2t?  Thanks.

**Comment by rsepassi** [comment]
The data generation is not happening inside TensorFlow and the Problems' generate_data methods generate data in a single thread. Some generate data in parallel processes (see how `--task_id` is used). If you run training, you'll see that during the training steps, multiple cores are used.

**Comment by alexwwang** [comment]
Thank you for answering and it's really help! 
I have studied the documents and codes but still have some uncertainty on concepts:
- I do see the `--task_id` param, but I am not sure how to utilize it 'cuz I have only one host with 32 cores cpu since I take it as using on different physical hosts or virtual guests to make the gen task distributed.
- I am not sure if I should set some additional params to run t2t_trainer, e.g. `--worker_replicas` or `--worker_gpu=0` since I've got no gpu.
I am still trying now but if could get answer, will be very appreciated!

**Comment by rsepassi** [comment]
Most problems' data generation is single threaded. Here's an example
<https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/gene_expression.py#L93>
one one that is multithreaded. If you're implementing your own problem, you
can make it multithreaded.

For the t2t-trainer there is no flag you need to set to get it to be
multithreaded on cpu. TensorFlow uses all the cores.

**Comment by alexwwang** [comment]
Thanks for your information and seems much helpful! Indeed I defined problems my own with 900 million items of data. So multiple processes are needed. 
Pls allow me to learn it carefully first.
