### ISSUE TITLE
Getting BLEU Score Higher than Expected

### ISSUE THREAD

**Issue by kelayamatoz** [tensorflow/tensor2tensor#343]
Dear T2T Team,

I was trying to reproduce the result by following the walkthrough. After 1d18h of training, I managed to obtain a BLEU score that's higher than what's reported from the "Attention is All You Need" paper: 
<img width="522" alt="screen shot 2017-10-07 at 2 45 26 pm" src="https://user-images.githubusercontent.com/1896351/31312051-935a0370-ab6e-11e7-8e42-1e44ee1e87e8.png">

The reported approx. BLEU score from my log is around 33.79. Is that expected? It seems that this score is much higher than what's reported in the official paper.

Thanks!

**Comment by lukaszkaiser** [comment]
The BLEU score on TensorBoard is computed with our tokenization, while most papers (including ours) report BLEU scores that use the MOSES tokenizer. There's a `get_en_de_bleu` script in `utils` that might help you get those results, they're usually a fair bit lower than the approximate BLEU.

**Comment by kelayamatoz** [comment]
That makes sense; thanks!
