### ISSUE TITLE
how to create decoder server?

### ISSUE THREAD

**Issue by xikakera** [tensorflow/tensor2tensor#344]
I want to create a decoder server!
like I have a html page, use ajax to use t2t model ;

**Comment by rsepassi** [comment]
See #349 where others are also working on getting serving working.

**Comment by nadavb** [comment]
@xikakera, you can combine the code in query.py together with Python Tornado webserver. It works well.

**Comment by mehmedes** [comment]
@xikakera Would you mind sharing how you combined query.py with Pythin Tornado webserver?
