### ISSUE TITLE
How to initialize the input weight matrix with a custom matrix?

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#345]
In Text2TextProblem with Symbol modality, how to initialize the input weight matrix with a matrix that requires information (e.g., word embeddings) from the source vocab? Should I initialize it in Modality? If so, how to address the problem that Modality is instantiated before the vocab is established? Thanks.

**Comment by rsepassi** [comment]
You could try defining your own Modality and do what you'd like when you create the embedding var.

**Comment by anglil** [comment]
Thanks. Solved.
