### ISSUE TITLE
How does ranged hparams work ?

### ISSUE THREAD

**Issue by alcaster** [tensorflow/tensor2tensor#351]
As above.
In transformer_base_range i see that there are ranged hparams.
Is this grid search or is it changing during training ? How does it work ?

**Comment by martinpopel** [comment]
It is not documented yet, see https://github.com/tensorflow/tensor2tensor/issues/336#issuecomment-334299597

**Comment by lukaszkaiser** [comment]
Indeed, support for hyperparameter searches is only maturing in TF for now.
