### ISSUE TITLE
results of different models

### ISSUE THREAD

**Issue by feiga** [tensorflow/tensor2tensor#354]
There are various models support by tensor2tensor, like transformer, slicenet, lstm and so on. For each tasks like wmt en2de, is there any document that summaries the results of different models? 

Thanks.

**Comment by lukaszkaiser** [comment]
Not all models would make sense for en2de. We're working on establishing regression tests to be able to catch when our models change or results get worse. Once that's done, we'll be able to make a summary table, but that might take a little more. It's something we want to do, yes.
