### ISSUE TITLE
Getting Low BLEU Score By Following README

### ISSUE THREAD

**Issue by kelayamatoz** [tensorflow/tensor2tensor#356]
Dear T2T Team,

I was following the "Walkthrough" section in the README. I used the transformer model with HPARAMS=transformer_base_single_gpu on a Google Cloud K80 GPU instance. After the training finishes, I decoded the "newtest2013.en" file, did some work to format the decoded file, and calculated the official BLEU score by using the get_ende_bleu.sh script. However, the get_ende_bleu.sh script only reported a BLEU score of 15.14. I am wondering that what could go wrong here? Thanks!

I have also attached the decoded file to this ticket. 
[result.txt](https://github.com/tensorflow/tensor2tensor/files/1380814/result.txt)

**Comment by lukaszkaiser** [comment]
Your results file seems to have a lot of strange "#############" lines. How comes? Could it be that the input file got somehow mis-tokenized in the get_bleu script? More importantly, what's the evaluation perplexity of your model at the end of training? We get sth close to 1.45 or so for good results, it's the first thing to check, I'd say.

**Comment by martinpopel** [comment]
BTW: there are extra line breaks in [get_ende_bleu.sh](https://github.com/tensorflow/tensor2tensor/blob/f9f41eb5df23460ce74f7c77d31a8a7bcbb8ea76/tensor2tensor/utils/get_ende_bleu.sh#L16-L18). Probably everyone who uses it noticed the error, fixed it, but was lazy to do a PR:-).
