### ISSUE TITLE
Reinforcement learning refinement 

### ISSUE THREAD

**Issue by mudong0419** [tensorflow/tensor2tensor#374]
Hello,
    Many thanks to your great work on Tensor2Tensor, It do help me a lot.
    Recently, I read the paper "Google’s Neural Machine Translation System: Bridging the Gap between Human and Machine Translation". It introduced a reinforcement leaning refinement method to refine the maximum likelihood pre-trained model with GLEU score. 
    Will Tensor2Tensor transformer model bring in this mechanism in the future?

**Comment by lukaszkaiser** [comment]
We'd be happy to, but for now we have a lot of other things to work on. If you want to take on it, PRs are welcome!

**Comment by Sanqiang** [comment]
Could I have some ideas (I tried implemented by myself)? The refinement method need sample the sentence (enable backpropagation), is it a drawback to consume a lot of GPU memory (because each word is supposed to depends on all previous words)?
