### ISSUE TITLE
Double linear projection for attention states in lstm

### ISSUE THREAD

**Issue by lucasgreene** [tensorflow/tensor2tensor#375]
I've been working with the lstm modules and was wondering about the attention cell wrapper in models/lstm.py

```
 def call(self, inputs, state):
    """Long short-term memory cell with attention (LSTMA)."""

    if not isinstance(state, AttentionTuple):
      raise TypeError("State must be of type AttentionTuple")

    state, attns = state
    attn_states = self._attn_states
    attn_length = attn_states.get_shape()[1].value
    if attn_length is None:
      attn_length = tf.shape(attn_states)[1]

    input_size = self._input_size
    if input_size is None:
      input_size = inputs.get_shape().as_list()[1]
    if attns is not None:
      inputs = tf.layers.dense(tf.concat([inputs, attns], axis=1), input_size)
    lstm_output, new_state = self._cell(inputs, state)

    new_state_cat = tf.concat(nest.flatten(new_state), 1)
    new_attns = self._attention(new_state_cat, attn_states, attn_length)

    with tf.variable_scope("attn_output_projection"):
      output = tf.layers.dense(
          tf.concat([lstm_output, new_attns], axis=1), self._attn_size)

    new_state = AttentionTuple(new_state, new_attns)

    return output, new_state
```

So the basic logic here is take the current computed attention vector (computed during the previous call to call()), linearly combine it with the current inputs, compute a new lstm state and output, create the next attention state from the new lstm state. All good until here:
```    
with tf.variable_scope("attn_output_projection"):
      output = tf.layers.dense(
          tf.concat([lstm_output, new_attns], axis=1), self._attn_size)
```
Here we are linearly projecting the new attention state with the lstm output. Is there justification for this in a paper somewhere? Im just a little confused because if you are using this function as a generating decoder and feeding in the previous lstm output as the next input you will be combining the output/input with the new attention state twice. Im wondering because I am training a model that takes english sentences as both input and output and I am finding the model tends to repeat itself a good bit when the input and outputs are very similar. The thought here is maybe the attention mech being applied twice is causing it to keep copying the same word from the input source. Any ideas welcome!

**Comment by kolloldas** [comment]
The original [Bahdanau](https://arxiv.org/pdf/1409.0473.pdf) paper only had input attention. But later papers have found output attention helps the model as well. Please check [Luong](https://arxiv.org/pdf/1508.04025.pdf). Essentially:
* Combine the attention (context vector) from the previous time step with the current inputs
* Combine the attention (context vector) from the current time step with the current output

In the latest attention model you can turn off output attention by setting the following flag:
`--hparams=output_attention=0`

You can also switch between Bahdanau (additive) attention and Luong (multiplicative) attention mechanisms by using the appropriate `hparams_set`. 

Hope this helps!

**Comment by rsepassi** [comment]
Closing for now as that code has changed significantly.
