### ISSUE TITLE
Same computation done multiple times in lstm

### ISSUE THREAD

**Issue by lucasgreene** [tensorflow/tensor2tensor#378]
Im looking at the ExternalAttentionCellWrapper class in models/lstm.py and noticed that there is some work in the attention mechanism that is seemingly done for each iteration of the rnn loop. Here is the function:
``` 
 def _attention(self, query, attn_states, attn_length):
    conv2d = tf.nn.conv2d
    reduce_sum = tf.reduce_sum
    softmax = tf.nn.softmax
    tanh = tf.tanh

    with tf.variable_scope("attention"):
      k = tf.get_variable("attn_w",
                          [1, 1, self._attn_size, self._attn_vec_size])
      v = tf.get_variable("attn_v", [self._attn_vec_size, 1])
      hidden = tf.reshape(attn_states, [-1, attn_length, 1, self._attn_size])
      hidden_features = conv2d(hidden, k, [1, 1, 1, 1], "SAME")
      y = tf.layers.dense(query, self._attn_vec_size)
      y = tf.reshape(y, [-1, 1, 1, self._attn_vec_size])
      s = reduce_sum(v * tanh(hidden_features + y), [2, 3])
      a = softmax(s)
      d = reduce_sum(tf.reshape(a, [-1, attn_length, 1, 1]) * hidden, [1, 2])
      new_attns = tf.reshape(d, [-1, self._attn_size])

      return new_attns
```

The relevant portion is here 
```
      hidden = tf.reshape(attn_states, [-1, attn_length, 1, self._attn_size])
      hidden_features = conv2d(hidden, k, [1, 1, 1, 1], "SAME")
```
It looks like attn_states are linearly projected here, which is done before the interaction with `query` is computed. Each loop of the rnn will project all the attn states through convolution. But generally the attn_states are fully known before the loop starts so we can do this before. Unless there is something i am missing this convolution is happening on the exact same data on every rnn loop call. I think the proper place to do this is when the wrapper is instantiated and then pass the projected values.

**Comment by lucasgreene** [comment]
I could definitely make a pull request if we agree it should be done during instantiation

**Comment by kolloldas** [comment]
You are right! The `conv2d()` need not be done every time since `attn_states` is fixed. 

The above code has been completely replaced in the latest version. The model now uses `AttentionWrapper` from the *seq2seq* library which is much more flexible and optimized.

**Comment by rsepassi** [comment]
Closing for now after the code has changed, but please reopen if there's still an issue.
