### ISSUE TITLE
problem about TranslateEnzhWmt8k 

### ISSUE THREAD

**Issue by hellozgy** [tensorflow/tensor2tensor#380]
this following line code , does it look like use the english vocab to encode the chinese?
"return translate.bi_vocabs_token_generator(data_path + ".lang2", data_path + ".lang1",
                                     source_vocab, target_vocab, EOS)"

**Comment by martinpopel** [comment]
See https://github.com/tensorflow/tensor2tensor/issues/315#issuecomment-336407506

**Comment by hellozgy** [comment]
Yes, I have seen it. I'm just puzzled why the code haven't been changed? Is it a bug or just not easy understand but right?

**Comment by rsepassi** [comment]
Seems that this has been fixed.
