### ISSUE TITLE
Deletion of old Tensor2Tensor pip releases

### ISSUE THREAD

**Issue by fhieber** [tensorflow/tensor2tensor#385]
It's great to see tensor2tensor being developed that rapidly! But is there a good reason to delete previous versions from pypi?
The problem is that one cannot reproduce old results on a new machine easily if `pip install tensor2tensor==v1.2.5` does not work anymore.

**Comment by martinpopel** [comment]
What about `pip install https://github.com/tensorflow/tensor2tensor/archive/v1.2.5.zip`
See also https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

**Comment by fhieber** [comment]
Oh that's a great tip, thanks a lot!
