### ISSUE TITLE
Parallelize data_generator ?

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensor2tensor#388]
Seems the code to generate tf_records is serial. We could use all the cores to process the datasets in parallel if running on a single machine.

**Comment by NickShahML** [comment]
@Mistobaan if you could figure out a way to do this, it would be much appreciated. Currently it can take on the order of days to create big datasets.

**Comment by rsepassi** [comment]
Yes, we generate multiple shards of TFRecord files, and it would make sense for very large problems to parallelize across multiple cores (using e.g. the `multiprocessing` module). 

Each problem has a `generate_data` method and you can put whatever you'd like in there. 

`generator_utils.generate_files_distributed` will write to a single shard of data. You'll need to write your generator in a way that can be sharded and then you can use the `multiprocessing` module to do things in parallel. 

This is not something we plan to support for all problems generally.
