### ISSUE TITLE
multi-GPU contradicting performance

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#390]
Dear all,

with reference to #124 #146 #184 I would like to confirm if my current situation is normal.

I am using batch size = 4096, transformer_base_single_gpu and my machine has 2 GTX 1080 ti

when gpu_worker=1, global step per sec = 2.6 and time for 100 steps =38s
when gpu_worker=2, global step per sec = 1.3 and time for 100 steps =76s

i check nvidim smi and it shows for 2 gpu case, both gpu are used in a fluctuating manner.

I read from previous post work per second is calculated as follow:
number_of_gpu * batch_size * global step per sec.

I am very confused because i was expecting for 2 gpu, a global step per sec slightly lower than 1 gpu and a consumed time for 100 steps slightly higher than 1 gpu, not a global step per sec half that of 1 gpu and a time for 100 steps double that of it.

Would be great if someone can shed some light on this. Thank you!

**Comment by NickShahML** [comment]
@colmantse I have had the exact same issue. I too have a two 1080ti machine and it seems that your actual train time remains the same as a single 1080ti. The issue I believe is that since we are constantly copying parameters back and forth between gpus, there is a stall time. The only way to resolve this is to have NVLINK between both gpu's which is impossible for our gamer cards.

What would be super useful instead is if we could asynchronously train the net on both gpus on the same local machine. The parameters could be updated and merged say every 10 or 20 steps. This would greatly boost the efficiency while leading to some minor train error. I'm not sure how to do this, but I think they have built in async training.

**Comment by lukaszkaiser** [comment]
Hi guys, you're both correct in what you say. The problem with async is that it'll still not help in this case: you'll need to copy your parameters from CPU to both GPUs and this will slow you down. What could help would be to put parameters on CPU in the 2-worker case (sync) instead of distributing them on both gpus. Without NVLINK, the interface from cpu to gpu might be faster than cross-gpu copies (depending on your motherboard, I guess). We do this in distributed training here: https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/devices.py#L128

I think it'd be great to try to set caching devices to "cpu:0" in your setup and check if that works better. Can you try and report back?

**Comment by lukaszkaiser** [comment]
To be concrete: I'm thinking of changing this line:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/devices.py#L120

To sth like
```
caching_devices = ["cpu:0"] * FLAGS.worker_gpu
```

**Comment by colmantse** [comment]
i changed line 140, since evaluation for multi-gpu is still not working (i set schedule=train), to cpu. This result in a approx 10% speed up. Still too slow when compared to opening two window setting cuda_visible_devices and run on different problem. But by default, it should be line 120 not 140?

**Comment by vince62s** [comment]
@colmantse 
What is your motherboard ?
I did some measures on the EN to DE task, using a 4096 token batch size.
1 GPU GTX1080ti => 2.64 step per sec [very similar o yours]
4 GPU GTX 1080ti => 2.10 step per sec
resulting in 3.2x speed gain.

On another machine, with 2 GTX1080 (8GB only) Batch size 3072 > 2.56 step per sec

So I do not have the same gain as mentioned in a previous post (ie x3.57) but it also depend on the task.

Motherboard and PCI speed might be a reason on your end.

**Comment by colmantse** [comment]
i am using Gigabyte x299 AORUS Gaming 7, it is really weird, did you install anything apart from cuda and cudnn? or is there anything needed to switch on to achieve your speed up?

**Comment by vince62s** [comment]
try to check something like:
sudo lspci -vv | grep -P "[0-9a-f]{2}:[0-9a-f]{2}\.[0-9a-f]|LnkSta:"

and see if each card is actually in x16 mode

No just cuda, driver 375.66

**Comment by colmantse** [comment]
I am using driver 388
since i am using window, i have the display info displayed below:
`Display Devices
---------------
          Card name: NVIDIA GeForce GTX 1080 Ti
       Manufacturer: NVIDIA
          Chip type: GeForce GTX 1080 Ti
           DAC type: Integrated RAMDAC
        Device Type: Full Device
         Device Key: Enum\PCI\VEN_10DE&DEV_1B06&SUBSYS_374E1458&REV_A1
      Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
Device Problem Code: No Problem
Driver Problem Code: Unknown
     Display Memory: 27362 MB
   Dedicated Memory: 11132 MB
      Shared Memory: 16230 MB
       Current Mode: 1920 x 1080 (32 bit) (60Hz)
       Monitor Name: Generic PnP Monitor
      Monitor Model: D2743
         Monitor Id: GSM58ED
        Native Mode: 1920 x 1080(p) (60.000Hz)
        Output Type: DVI`

it says 32 bit, i could only guess it means 16 + 16, not really sure.

**Comment by vince62s** [comment]
no this isn't related. you need to find a pci info tool, like pci-z or similar.
but honestly I wouldn't be surprised that on windows there are more overheads.

**Comment by colmantse** [comment]
i downloaded the gpu-z to check pcie, it reads both gpu use x16. 
yeah i know, i would be very frustrated if this turns out to be a window issue.

**Comment by NickShahML** [comment]
Thanks @vince62s -- I realize now that my speed is only x8 registering at 8GT/s. And my second gpu is only registered at 2.5GT/s:

```
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1b06 (rev a1) (prog-if 00 [VGA controller])
                LnkSta: Speed 8GT/s, Width x8, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
01:00.1 Audio device: NVIDIA Corporation Device 10ef (rev a1)
                LnkSta: Speed 8GT/s, Width x8, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
02:00.0 VGA compatible controller: NVIDIA Corporation Device 1b06 (rev a1) (prog-if 00 [VGA controller])
                LnkSta: Speed 2.5GT/s, Width x8, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
02:00.1 Audio device: NVIDIA Corporation Device 10ef (rev a1)
                LnkSta: Speed 2.5GT/s, Width x8, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
04:00.0 USB controller: ASMedia Technology Inc. ASM1142 USB 3.1 Host Controller (prog-if 30 [XHCI])
                LnkSta: Speed 5GT/s, Width x2, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
```

I'll have to investigate. My motherboard is ```
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: Z170-E
```
and cpu is ```Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz```

**Comment by colmantse** [comment]
below is result from pci-z:

```
Display controller	NVIDIA Corporation	GP102 [GeForce GTX 1080 Ti]	VGA compatible controller	10DE:1B06 1458:374E	Has Register_Device_Driver. Is currently configured. Can be rebalanced.
Display controller	NVIDIA Corporation	GP102 [GeForce GTX 1080 Ti]	VGA compatible controller	10DE:1B06 1458:3751	Has Register_Device_Driver. Is currently configured. Can be rebalanced.
```
I cannot really see the lane tho.

**Comment by colmantse** [comment]
btw, @vince62s , did you set schedule=train while training?

**Comment by vince62s** [comment]
yes. otherwise it doesn't work with multi-gpu. see multiple issues on this. but you can monitor the training with tensorboard on another machine with continuous eval.

**Comment by colmantse** [comment]
yes, I was just wondering if that might be an issue. I did saw those posts.

**Comment by colmantse** [comment]
I concluded this is a window problem, it happens when tensorflow is not compiled from source. I decided to include linux to my machine, dual boot between win10 and ubuntu. while problem persists in the former, GPU is now fully utilized in the latter, resulting a 6x speed boost.
