### ISSUE TITLE
Mismatch position encoding with paper

### ISSUE THREAD

**Issue by Zrachel** [tensorflow/tensor2tensor#391]
https://github.com/tensorflow/tensor2tensor/blob/9bdc801e23586321e04e743fc61dd66b10adbc1d/tensor2tensor/layers/common_layers.py#L1044

According to the code above, position encoding should be:
PE(pos, 0:channels/2)=sin(scaled_time)
PE(pos, channels/2:) = cos(scaled_time)

however, as described in the paper, it should be
PE(pos, [0,2,4,...]) = sin(scaled_time)
PE(pos, [1,3,5,...]) = cos(scaled_time)

Is it matters?

**Comment by lukaszkaiser** [comment]
I think this does not matter, since there is a fully connected layer after the encoding is added (and before) and it can permute the coordinates. Good catch though!

**Comment by ColainCYY** [comment]
Sorry but where is the mentioned “a fully connected layer”，I can't find it. Thanks!

**Comment by zZer0o** [comment]
@lukaszkaiser  Could you further explain the 'permute'?  Thx!
