### ISSUE TITLE
Is there a way to add a user defined eval_metric function

### ISSUE THREAD

**Issue by safpla** [tensorflow/tensor2tensor#395]
I see that all evaluation functions are defined in metrics.py. But in my task I need a evaluation function that hasn't been defined there. Is there a way to add a user defined eval function without changing the original t2t code, just like defining a problem or model in usr_t2t folder? I don't want to edit the metrics.py because when there is a new release, I would need to add my code to the metrics.py again.

**Comment by rsepassi** [comment]
Yeah, that's a current limitation. We're hoping to move more functionality into `Problem` and `T2TModel` so that users can more easily extend the code. Not an immediate thing, but soon-ish (I'd guess 3-6 weeks).

**Comment by safpla** [comment]
thanks～
            On 11/14/2017 05:59, Ryan Sepassi wrote: Yeah, that's a current limitation. We're hoping to move more functionality into Problem and T2TModel so that users can more easily extend the code. Not an immediate thing, but soon-ish (I'd guess 3-6 weeks).

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tensorflow/tensor2tensor","title":"tensorflow/tensor2tensor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tensorflow/tensor2tensor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rsepassi in #395: Yeah, that's a current limitation. We're hoping to move more functionality into `Problem` and `T2TModel` so that users can more easily extend the code. Not an immediate thing, but soon-ish (I'd guess 3-6 weeks). "}],"action":{"name":"View Issue","url":"https://github.com/tensorflow/tensor2tensor/issues/395#issuecomment-344072909"}}}
