### ISSUE TITLE
TransformerVisualization.ipynb: Unreadable Notebook, NotJSONError

### ISSUE THREAD

**Issue by christopherblum** [tensorflow/tensor2tensor#406]
When I tried to open "TransformerVisualization.ipynb" using jupyter notebook, I got the following error message (operating system: CentOS, browser: Firefox):

_Unreadable Notebook: /myhost/myuser/py2.7_tf1.3.0/lib/python2.7/site-packages/tensor2tensor/visualization/TransformerVisualization.ipynb NotJSONError("Notebook does not appear to be JSON: u'\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lan...",)_

I was able to reproduce the error when I copied the notebook to another Computer (OS: Ubuntu, , browser: Firefox):

_Unreadable Notebook: /home/myuser/Desktop/TransformerVisualization.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...",)_

In both cases, I ran jupyter notebook in a virtualenv using python2.7. The virtual environments have been set up _without_ the `--system-site-packages` flag.

The error has been described before in a different context related to jupyter: [https://github.com/jupyter/help/issues/171]()

I would greatly appreciate your help.

**Comment by christopherblum** [comment]
Figured it out. The github link appears to be broken (wget https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/visualization/TransformerVisualization.ipynb just downloads some html file).

Instead, when I click on "raw" and then copy/paste the content, the notebook can be opened.

**Comment by rsepassi** [comment]
Glad you figured it out. 

wget https://raw.githubusercontent.com/tensorflow/tensor2tensor/master/tensor2tensor/visualization/TransformerVisualization.ipynb
