### ISSUE TITLE
How can I sepcific gpu id and gpu numbers in my transformer code ?

### ISSUE THREAD

**Issue by liesun1994** [tensorflow/tensor2tensor#409]
I am trying to use t2t recently. 
Problem is as title described. 
```
t2t-trainer \
  --generate_data \
  --data_dir=~/t2t_data \
  --problems=translate_ende_wmt32k \
  --model=transformer \
  --hparams_set=transformer_base_single_gpu \
  --output_dir=~/t2t_train/base
```
Can I sepcific gpu ids ?

**Comment by martinpopel** [comment]
As I answered you in #124 on the exactly same question three hours ago, use **CUDA_VISIBLE_DEVICES**.
If you tried this without any success, you should report the details in your question.

**Comment by liesun1994** [comment]
Thanks @martinpopel . Solved my problem . Aha
