### ISSUE TITLE
new space id registration

### ISSUE THREAD

**Issue by apiro** [tensorflow/tensor2tensor#429]
Hi,

I defined my specific seq2seq problem using the decorator. 
This task is not a MT task so I need 2 new space id tokens, let's say "TASK0_ENC" and "TASK0_DEC". 
I will use them in the same way of "EN" or "DE".

So my question is, how can I register a new space id that I can later retrieve using "problem.SpaceID" ? 

I suppose that, if my model only takes data from this task, it doesn't matter if I use some fake tags such as "EN" "DE" even if the encoder doesn't actually take English data. Am I right? 

Thank you and congrats for the great work,

Alberto

**Comment by rsepassi** [comment]
Hi Alberto, the space ids are really only used for multi-task models, so the default is `0=generic`. If you think it'd be a generally useful one, you can send a PR adding to the [`SpaceID` enum](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/problem.py#L34).

**Comment by apiro** [comment]
I imagined that but I wanted to be sure. Thank you so much for the response :)
