### ISSUE TITLE
review code and have some issues.

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensor2tensor#430]
1. convert direct num to below https://github.com/tensorflow/tensor2tensor/blob/5233253f2e5af8d342305e98a89697f20e2b354a/tensor2tensor/data_generators/problem_hparams.py#L56

should be like `tf.to_int32(example.pop("audio/num_channels"))`

2.  duplicated
https://github.com/tensorflow/tensor2tensor/blob/5233253f2e5af8d342305e98a89697f20e2b354a/tensor2tensor/data_generators/translate_enzh.py#L37

3. why not exist this method?
https://github.com/tensorflow/tensor2tensor/blob/5233253f2e5af8d342305e98a89697f20e2b354a/tensor2tensor/bin/t2t-datagen#L181

Can register _SUPPORTED_PROBLEM_GENERATORS's problem????

**Comment by rsepassi** [comment]
We'd welcome a PR if you have fixes you'd like to make.

To register a new problem, subclass `Problem` and register it. Take a look at [translate.py](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/translate.py) for some examples. You can override the `generate_data` method to generate data.

`_SUPPORTED_PROBLEM_GENERATORS` is deprecated. See [generate_data_for_registered_problem](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/bin/t2t-datagen#L199)
