### ISSUE TITLE
question about translate_enzh_wmt8k

### ISSUE THREAD

**Issue by yuimo** [tensorflow/tensor2tensor#433]
hi, i have a question about problem of translate_enzh_wmt8k
translate_enzh_wmt8k is used to translate from english to chinese
and translate_enzh_wmt8k_rev is from chinese to english, is that right?

and i am wondering how translate_enzh_wmt8k_rev is realized? can u give me some explanations?

another quesiton: if i use translate_enzh_wmt8k_rev to train a system, when run t2t_decode， the input is chinese, and the output is english, is than right?
thanks a lot.

**Comment by martinpopel** [comment]
> translate_enzh_wmt8k is used to translate from english to chinese

Yes

> and translate_enzh_wmt8k_rev is from chinese to english, is that right?

Yes.

> and i am wondering how translate_enzh_wmt8k_rev is realized?

It simply reverses the source and target modalities+vocab+space ids: https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/problem.py#L487

> another quesiton: if i use translate_enzh_wmt8k_rev to train a system, when run t2t_decode， the input is chinese, and the output is english

Yes. (That was you second question:-))

**Comment by yuimo** [comment]
got it. thanks a lot.
