### ISSUE TITLE
questions about dimentions of tensor

### ISSUE THREAD

**Issue by yuimo** [tensorflow/tensor2tensor#438]
for the seq2seq task, when generate datas, t2t convert batch of seqs to tensor of [batch, seq_len]
but at the beginning of transformer model, the input data is 4-d
so, how to convert from 2d to 4d?
and why use 4D inputs other than 3D .
thanks.

**Comment by mirkobronzi** [comment]
I may be wrong, but I think the added dimension is to help with convolutions?

I think dimensions are something like:
 [batch_size, input_length, 1, embedding_size]
(1 is for the convolution dimension - note that you have embedding_size given embedding lookup already happened)

**Comment by martinpopel** [comment]
I think the extra dimension is for (2D) image processing. As @mirkobronzi wrote, in sequence processing this dimension is always 1 (i.e. unused).

**Comment by yuimo** [comment]
yes, in t2t, the author replaces dense layer with conv layers, that need to expand one dim
thanks a lot.
