### ISSUE TITLE
how to ensemble model in C++ project

### ISSUE THREAD

**Issue by yuimo** [tensorflow/tensor2tensor#447]
hi all, i trained a translate model using t2t, but i do not how to ensemble it to my C++ project,
should i code for the beam search code? or can i use code of t2t-decoder directly?
thanks very much.

**Comment by rsepassi** [comment]
You'll have to export a SavedModel (run the trainer with `--export_saved_model`) and then load that in C++ with the TensorFlow C++ API or the [TensorFlow Serving](https://github.com/tensorflow/serving) code.
