### ISSUE TITLE
output node names (for --export_saved_model)

### ISSUE THREAD

**Issue by mirkobronzi** [tensorflow/tensor2tensor#448]
Hi all,
I was trying to save models with `--export_saved_model` to be able to re-use them.

It all works, and I am able to reload the models with
`tf.saved_model.loader.load(
            sess, [tf.saved_model.tag_constants.SERVING], frozen_graph_filename)`

The problem though is that I cannot find the output node name (I am using transformer here).
If I look at the output ot the transformer model, I do not see int (i.e., token_id), but float (I assume hidden states?).
I am trying to look into the symbol modality (possibly bottom?), but I still canno find the output node (containing the output token ids).

I also tried to list all the nodes in the saved models, but if I grep for the type int, I do not see the correct one.
(I tried with some softmax ones, but no luck)

Does anyone have some insight on this?

Thanks,
Mirko

**Comment by yuimo** [comment]
from the tensorboard you can get names of all ops

**Comment by mirkobronzi** [comment]
adding some information - I tried to compare the graph I can see on the tensorboard with the nodes I get after freezing the models.
I think they are different, e.g., in the tensorboard I see a loss node, while I cannot see that in the frozen/exported pbtxt.

This seem to make sense, given the tensorboard is looking at the training models (which obviously care about the loss value) while the exported models are kind of the inteference models (not needing the loss - just predictions).

Is that correct?

In any case, I still cannot find some suitable output nodes (for the output token_ids).
I am wondering if some part of the graph does not get serialized?
(e.g., the part that argmax the logits in the decoder to get the token_ids?)

Thanks,
Mirko

**Comment by mirkobronzi** [comment]
I may have found a point to 'intercept' the output node (and possibly rename it so that it can be easily used  after loading pbtxt):
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/t2t_model.py#L217

even so, I am still in doubt about the question above - in particular, it would seem that I need to feed the placeholder "targets", which is kind of weird (that should be there only for training models, not to produce predictions)...
I remember I had the same problem with the 'old' seq2seq code (I was freezing the 'training' version of the decoder - that was getting its input from the targets, not from the previous output) - do you know if something similar may be happening here?
(checking now if the eval_run_autoregressive may play a role here..)

**Comment by yuimo** [comment]
hi, how do you set the input as your code, as a placeholder?
now, i want to export the graph out to ensemble in my C++ project, any ideas?
thanks a lot.

**Comment by mirkobronzi** [comment]
you can add an explicit name to the output node by adding the line `samples = tf.identity(samples, 'output')` before the return statement in https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/t2t_model.py#L217

Then, you can train a model/export, and use it, e.g., with:
```
import tensorflow as tf


def load_graph(exported_models, token_ids):
    with tf.Session(graph=tf.Graph()) as sess:
        tf.saved_model.loader.load(
            sess, [tf.saved_model.tag_constants.SERVING], exported_models)
        graph = tf.get_default_graph()
        # preparing input
        name = 'inputs:0'
        node = graph.get_tensor_by_name(name)
        xs = {}
        xs[node] =  token_ids
        # preparing output
        ys_names = 'output:0'
        ys = graph.get_tensor_by_name(ys_names)
        # run
        return sess.run(ys, feed_dict=xs)


exported_models = 'output/export/Servo/1512144610'
token_ids = [7, 7, 4, 9422, 282, 1]
result = load_graph(exported_models, token_ids)
print('result size: {}\ndump: {}'.format(len(result), result))
```

unfortunately, this still does not work - if you provide 6 token ids (as in the example above), instead of being parsed as a a sequence with 6 tokens, it will be parsed as 6 sequences of length 1.
Maybe related to how tensor2tensor deals with batches?
(see @lukaszkaiser here: https://github.com/tensorflow/tensor2tensor/issues/17 )

**Comment by rsepassi** [comment]
Several sections of this [guide](https://www.tensorflow.org/programmers_guide/saved_model#apis_to_build_and_load_a_savedmodel) may be helpful.

**Comment by rsepassi** [comment]
Also take a look at the end of the `saved_model.pbtxt` file that's part of the export. In the `signature_def` it has the names of the output tensors.

**Comment by yuimo** [comment]
@mirkobronzi hi, i have read the doc of EstimatorSpec, and it has a item name "export_outputs" which should be the export names
but i don't know how to get the input node as a placeholder to use in predict, do you have a idea about this?

**Comment by yuimo** [comment]
hi, how do you export model? can you show me your command?
i have tried to export my trained model with command below, but it fails
see "https://github.com/tensorflow/tensor2tensor/issues/457"
thanks a lot.

 "
t2t-trainer  --data_dir=/home/devops/yuimo/mt/translate_zhen_wmtun_base32k/t2t_data --t2t_usr_dir=/home/devops/yuimo/mt/code/t2t_wmt_zhen/data_generators --tmp_dir=/home/devops/yuimo/mt/translate_zhen_wmtun_base32k/t2t_data/original --problems=translate_zhen_wmtun_base32k --model=transformer --hparams_set=transformer_zhen_wmtun_base32k --output_dir=/home/devops/yuimo/mt/translate_zhen_wmtun_base32k/t2t_data/base --train_steps=5 --eval_steps=50  --keep_checkpoint_max=200 --save_checkpoints_secs=3600 --export_saved_model=True"

**Comment by mirkobronzi** [comment]
thanks a lot @rsepassi - that helps with node names.
So, thanks to that link, I am now using the 'official' commands to run the exported models.

Unfortunately though, I get exactly the same problem, i.e., it is like the code is interpreting N tokens as N separated utterances with a single token.

E.g., (note these medels are trained just a few steps - so, the token ids do not make sense)

```
saved_model_cli run --dir output/export/Servo/1512078709/ --tag_set serve --signature_def output --input_exprs 'inputs=[[[[1]]],[[[2]]],[[[3]]],[[[4]]]]'


Result for output key outputs:
[[151 188  15 319 259 259 259 188  15 319 188 151  15   3  15 319 188 151
  151  15 319 188 151 188 151  15   3  93  15 319 151  15 151 188  15 319
  151 151  15 319 188 151 188 151  15 319 188 151 188 151  15]
 [311 330  67  67  67  67  67  67  67  67  67  67  67  67  67  67  67  67
   67  67  67  67  67  67  67  67  67  67  67  67  67  67  67  67  67  67
   67  67  67  67  67  67  67  67  67  67  67  67  67  67  67]
 [374   7  22  22  22  22  22  22  22  22  22  22  22  22  22  22  22  22
   22  22  22  22  22  22  22  22  22  22  22  22  22  22  22  22  22  22
   22  22  22  22  22  22  22  22  22  22  22  22  22  22  22]
 [311 330 209 209 209 209 151 209 209 209 209 209 151 209 209 209 209 209
  151 209 209 209 209 209 209 151 209 209 209 209 209 151 209 209 209 209
  209 151 209 209 209 209 209 209 151 209 209 209 209 209 151]]
```
note how I feed 4 tokens but I get 4 utterances in output.

As a test, I can run this only on a single token only (the first one), and I get exactly the first output above:
```
s$ saved_model_cli run --dir output/export/Servo/1512078709/ --tag_set serve --signature_def output --input_exprs 'inputs=[[[[1]]]]'                    Result for output key outputs:
[[151 188  15 319 259 259 259 188  15 319 188 151  15   3  15 319 188 151
  151  15 319 188 151 188 151  15   3  93  15 319 151  15 151 188  15 319
  151 151  15 319 188 151 188 151  15 319 188 151 188 151  15]]
```

I think this confirms that, somehow, a N token input is parsed as N utterances (single token).
Any idea why this is happening?

**Comment by rsepassi** [comment]
I think the shape of the inputs is wrong the way you're passing them in.

Try [[[[4, 3, 2, 1]]]]

**Comment by mirkobronzi** [comment]
thanks @rsepassi , I actually tried that (forgot to mention).
The shape will complain in that case:

```
$ saved_model_cli run --dir output/export/Servo/1512078709/ --tag_set serve --signature_def output --input_exprs 'inputs=[[[[1, 2, 3, 4]]]]'
Traceback (most recent call last):
...
ValueError: Cannot feed value of shape (1, 1, 1, 4) for Tensor u'ExpandDims_2:0', which has shape '(?, 1, 1, 1)'
```

It seems to me the only accepted shape is `[[[[1]]],[[[2]]],[[[3]]],[[[4]]]]`.
Indeed, it seems the only 'unbound' dimension is the first one (the -1 one):
```
The given SavedModel SignatureDef contains the following input(s):
inputs['inputs'] tensor_info:
    dtype: DT_INT32
    shape: (-1, 1, 1, 1)
    name: ExpandDims_2:0
```

**Comment by rsepassi** [comment]
Ah interesting. Then this may indeed be a bug. I’ll look into it.

**Comment by yuimo** [comment]
@mirkobronzi i have exported the model, but when loaded it in python ,the predict result is totally wrong, see issue: https://github.com/tensorflow/tensor2tensor/issues/462
have any ideas about this?
or have you succeed with exporting models?
thanks.

**Comment by mirkobronzi** [comment]
thanks again @rsepassi 

@yuimo : well, as you see in this thread, I cannot get meaningful results unfortunately..
(but not sure it's your same problem though)

**Comment by rsepassi** [comment]
Please see the updated [serving README](https://github.com/tensorflow/tensor2tensor/tree/master/tensor2tensor/serving).

**Comment by mirkobronzi** [comment]
thanks @rsepassi - will take a look

**Comment by mirkobronzi** [comment]
@rsepassi: yes, it is working now - thanks again.

one thing: it would seem that the decoder (using transformer here - not sure it's the same for all models) is running past the EOS.
(note I am sending a single utterance per batch)
Is this expected?

I see a stop_at_eos option in the code:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/t2t_model.py#L661

but it seems to not be used while t2t-decoding or when using export.
(so, also when using the exported models)

Is there a way to enable this?

Thanks,
Mirko

**Comment by mirkobronzi** [comment]
I think I can confirm the above.
Also, I saw (in 1.4.2) that the transformer greedy decoder was running past EOS.
(I was able to fix it locally)
Not sure though this is the case anymore in the new versions.

Anyway, I think I can close the issue - thanks a lot @rsepassi  for all the help.

**Comment by xu-song** [comment]
I find there is no difference when set `--export_saved_model=True` or `False`?

```
$ cd t2t_train/model
$ ls -lh
 81B Aug 10 13:58 checkpoint
 19M Aug 10 13:58 events.out.tfevents.1533880718.localhost
1.5K Aug 10 13:58 flags.txt
952B Aug 10 13:58 flags_t2t.txt
8.6M Aug 10 13:58 graph.pbtxt
3.5K Aug 10 13:58 hparams.json
 24B Aug 10 13:58 model.ckpt-1.data-00000-of-00002
114M Aug 10 13:58 model.ckpt-1.data-00001-of-00002
 15K Aug 10 13:58 model.ckpt-1.index
5.0M Aug 10 13:58 model.ckpt-1.meta
```
