### ISSUE TITLE
Dynamic compution graph confidence 

### ISSUE THREAD

**Issue by liesun1994** [tensorflow/tensor2tensor#450]
Hello , I am using tensor2tensor recently. The code is really confisuing owning to the static graph . Is is possible to support dynamic grapha using Eager Excution in the near future ?

**Comment by martinpopel** [comment]
I guess compatibility with Eager is planned (see https://github.com/tensorflow/tensor2tensor/pull/449/commits/c65a646c0a5b5b5b93a70fa5dce13eebfd101a0a), but I am not sure if in case of t2t it will result in a source code, which is easier to understand. I guess for TPUs it will be needed to go the other direction and put even bigger parts in static graphs.

**Comment by rsepassi** [comment]
Yes, `T2TModel` and `Problem` are Eager-compatible as of v1.3.1! We're very excited about Eager usage because model development can be so much more interactive.

See this [ipynb](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/notebooks/hello_t2t.ipynb) for usage. 

>
