### ISSUE TITLE
Cannot get example data

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensor2tensor#452]
In https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/notebooks/hello_t2t.ipynb,  
We cannot get this data blew:

```
gs_data_dir = "gs://tensor2tensor-data"
gs_ckpt_dir = "gs://tensor2tensor-checkpoints/"
```

**Comment by Zhengxuru** [comment]
so do I. Have you fixed this problem? Could you show me?
