### ISSUE TITLE
questions about loading exported model in python

### ISSUE THREAD

**Issue by yuimo** [tensorflow/tensor2tensor#462]
hi all, i have used t2t to trained a translate model for a total batch of 20K
then i export the model using t2t-trainer with flags bellow:
--export_saved_model=True --locally_shard_to_cpu --worker_gpu 0 --train_steps=215827
(which will load the latest checkpoint)
and generate a dictionary---export/Servo/1512453508 having two file or dict like bellow:
saved_model.pbtxt  variables

the problem is:
when i load the savedmodel in python using such code, the result is totally wrong
however if i use t2t-decoder to translate my input with checkpoint files, the result is quite right.

i have checked the documents of estimator, but no useful things are finded 
i have no idea about this

<img width="678" alt="image" src="https://user-images.githubusercontent.com/22741826/33595358-b3a3a8c4-d9d2-11e7-9550-d4c00cb86aa6.png">

        tf.saved_model.loader.load(
            sess, [tf.saved_model.tag_constants.SERVING], exported_models)
        graph = tf.get_default_graph()
        name = 'ExpandDims_1:0'
        node = graph.get_tensor_by_name(name)
        xs = {}
        xs[node] =  token_ids
        # preparing output
        ys_names = 'strided_slice_8:0'
        ys = graph.get_tensor_by_name(ys_names)
        # run
        return sess.run(ys, feed_dict=xs)

notes: 'ExpandDims_1:0' and 'strided_slice_8:0' are nodes in the saved_model.pbtxt, belong to signature_def node

thanks a lot.

**Comment by yuimo** [comment]
by the way, my input is a chinese sentence, the process is below:
1) i load the source(chinese) and target(english) vocabulary generated in the t2t-datagen process
2)encode the sentence into ids by the dict, code looks like this:
    token_ids = source_token_vocab.encode(line.strip()) + eos_list
3)expand dims of token_ids to (1, -1, 1, 1) to meet the input requirement of the model
4)feed it to a dict to get the result like this:
      name = 'ExpandDims_1:0'
    node = graph.get_tensor_by_name(name)
    xs = {}
    xs[node] =  token_ids
    # preparing output
    ys_names = 'strided_slice_8:0'
    ys = graph.get_tensor_by_name(ys_names)
    # run
    return sess.run(ys, feed_dict=xs)

**Comment by sicklife** [comment]
@hhxxttxsh  I got the same problem, how did you solve this?
