### ISSUE TITLE
t2t-decoder generate result randomly

### ISSUE THREAD

**Issue by yuimo** [tensorflow/tensor2tensor#464]
hi all, after training 20K for transformer, i use t2t-decoder to decode from files twice
same command, same file, but i get different result below
when i run with flag decode_interactive, the result is randomly different
does anybody know why?
how does this happen?
thanks a lot 

**my command:**
t2t-decoder --data_dir=/home/devops/yuimo/mt/translate_zhen_wmtun_base32k/t2t_data --t2t_usr_dir /home/devops/yuimo/mt/code/t2t_wmt_zhen/data_generators --tmp_dir=/home/devops/yuimo/mt/translate_zhen_wmtun_base32k/t2t_data/original --problems=translate_zhen_wmtun_base32k --model=transformer --hparams_set=transformer_zhen_wmtun_base32k --output_dir=/home/devops/yuimo/mt/translate_zhen_wmtun_base32k/t2t_data/base  --decode_from_file=/tmp/translate.txt

<img width="964" alt="image" src="https://user-images.githubusercontent.com/22741826/33642085-445691d8-da73-11e7-87c0-e0298e76ec1f.png">
<img width="969" alt="image" src="https://user-images.githubusercontent.com/22741826/33642096-4e2d5200-da73-11e7-92ab-955173cb7728.png">

**Comment by thompsonb** [comment]
I don't have this issue in 1.2.9. Does this happen for you if you train the default en-de settings (i.e. problem translate_ende_wmt32k)? If not, you probably need to check your data generation / vocabulary code (e.g. the code in your t2t_usr_dir directory) to make sure it is consistent from one run to the next.

**Comment by yuimo** [comment]
the problem gone after i upgrade to the new version of 1.3.1
thanks all.
