### ISSUE TITLE
About hparams

### ISSUE THREAD

**Issue by hzrtom** [tensorflow/tensor2tensor#468]
How could I find out those specific params of hparams? I want to set the max training step of my training task.

**Comment by mehmedes** [comment]
The training steps are set to 250.000 by default. You can change them by adding the flag ```--train_steps``` to ```t2t-trainer```, for example:
```
t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --train_steps=500000 \
  --output_dir=$TRAIN_DIR
```

**Comment by hzrtom** [comment]
thanks!
