### ISSUE TITLE
generate_calculus_integrate_sample failure - Exceptions and/or ComplexInfinity

### ISSUE THREAD

**Issue by ip01** [tensorflow/tensor2tensor#47]
When called from `t2t-datagen  --problem=algorithmic_calculus_integrate ...`, `generate_calculus_integrate_sample()` in `tensor2tensor/data_generators/algorithmic_math.py` raises  exception, or causes subsequent `KeyError `exception in `int_encoder()`.

The reason is an attempt to integrate expressions like `"(b-d)/(a-a)"` w.r.t. `"b"` - it leads to `sympy.polys.polyerrors.PolynomialDivisionFailed` or builds expresions with `ComplexInfinity` (aka `zoo`), confusing `int_encoder()`.

The straightforward fix would be to put _retry loop_ into `calculus_integrate()`. Alternatively, `random_expr_with_required_var()` could be refined.

**Comment by lukaszkaiser** [comment]
Thanks for finding this! Would you be interested in making a PR with the fix? (Both suggestions looks fine to me.)

**Comment by lukaszkaiser** [comment]
I think PR#52 solved that, so I'm closing. Feel free to reopen if there're still problems, of course!
