### ISSUE TITLE
[Bug]: Wrong package reference in documentation 

### ISSUE THREAD

**Issue by MChromiak** [tensorflow/tensor2tensor#470]
In documentation of [Data Input Pipeline](https://github.com/tensorflow/tensor2tensor/blob/master/docs/example_life.md#data-input-pipeline) I believe there should be:

> the new tf.data.Dataset API (previously tf.contrib.data.Dataset).

instead:
> the new tf.data.Dataset API (previously tf.data.Dataset).

If preferred, can provide PR.

**Comment by rsepassi** [comment]
Thank you! Fixed. Always feel free to directly submit a PR for these small things instead of opening an issue.
