### ISSUE TITLE
Key not found when using transformer_ae with transformer_ae_base parameter

### ISSUE THREAD

**Issue by yynil** [tensorflow/tensor2tensor#472]
Hello, awesome developers!
I'm trying to evaluate the transformer vae model. I'm using the same corpus but with different model.
The model training is running normally. But when I'm trying to infer data with the same configuration, the key not found error is thrown.
I tried both CPU and GPU to decode, same thing happened.

The training/infer parameters are:
model=transformer_ae
hparams=transformer_ae_base
decode_hparams="beam_size=1,alpha=0.6"

I used the t2t-decoder to do the infer, the error happened.

Any help is appreciated!
Thanks in advance!

**Comment by jiangbojian** [comment]
顶

**Comment by rsepassi** [comment]
Please provide the command-line you used as well as the logs and stack trace.

**Comment by rsepassi** [comment]
And the t2t version you're using.

**Comment by stefan-it** [comment]
@yynil Is this still a problem? Otherwise I guess we could close that issue :)

**Comment by martinpopel** [comment]
@yynil: the issue can be closed only by its author (you) or someone with admin rights for this repo, but it seems the admins are busy last few months. BTW: thanks @stefan-it for trying to tidy up the issues.

**Comment by yynil** [comment]
Thanks for mention that! @martinpopel
