### ISSUE TITLE
How does t2t-decoder use specified checkpoint ?

### ISSUE THREAD

**Issue by efeiefei** [tensorflow/tensor2tensor#476]
I want to evaluate all checkponts' real bleu with t2t-decoder and standard bleu script.
It would be convenient if you supported specifying checkpoint.

Thx

**Comment by martinpopel** [comment]
I did a [PR adding a `--checkpoint_path` option to `t2t-decoder`](https://github.com/tensorflow/tensor2tensor/pull/436/files#diff-74fa53158ab99b198939587e62959842). It has been merged, but than someone reverted it.

You may be interested in my scripts [t2t-bleu](https://github.com/martinpopel/tensor2tensor/blob/bleu2/tensor2tensor/bin/t2t-bleu) and [t2t-translate-all](https://github.com/martinpopel/tensor2tensor/blob/bleu2/tensor2tensor/bin/t2t-translate-all). I plan to do a PR after cleaning those a bit.

**Comment by efeiefei** [comment]
@martinpopel 
Thanks a lot. Looking forward to your PR.

**Comment by rsepassi** [comment]
One way you can do this is by copying the checkpoint you want evaluated into a directory and then setting `--output_dir` to that folder.

**Comment by martinpopel** [comment]
@efeiefei: My PR is finally done: #488

**Comment by martinpopel** [comment]
`--checkpoint_path` works for me, thanks to https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/bin/t2t_decoder.py#L89.
It works only with `decode_from_file`. It does not work with `decode_interactive` and `score_file` (although it could; if you need it, send a PR, I would say).

**Comment by SkyAndCloud** [comment]
@martinpopel Thank you for your help, I have sent a PR which enables checkpoint_path arg in interactive decoding.

**Comment by SkyAndCloud** [comment]
My PR was merged, look #694
