### ISSUE TITLE
Transformer consumes a lot of memory for large vocab

### ISSUE THREAD

**Issue by faniuy** [tensorflow/tensor2tensor#479]
I used a customized tokenizer for transformer model, the vocab size is about 280k. The model took about 50GBs of memory as well as GPU memory. And it's ridiculously slow.
It seems like the input layer is somehow converted to dense tensor with 280k x 512 shape which could count for the memory consumption and slow speed.
So I search for the explicit conversion to dense tensor and replaced them in convert_gradient_to_tensor. but it didn't help.

**Comment by rsepassi** [comment]
280k is a very very large vocab and you should expect it to take a lot of memory. For our state-of-the-art translation models, we have a vocab ~32k. Symbols need to converted to dense tensors before they get fed into the rest of the model. That's done in SymbolModality.bottom which embeds the symbols into a hidden_dim, which in the hparams you're using seem to be set to 512, hence the 280k*512 dense tensor.

**Comment by faniuy** [comment]
@rsepassi  thank you for the reply.  But to my knowledge, the tensor should be 280k * 512 * 4bytes ~ 560MB instead of several GB's.

**Comment by rsepassi** [comment]
True...
Try running with a batch size = 1 and --dbgprofile and take a look at the profile it spits out. Maybe you can see which Tensors are hogging the memory.

**Comment by rsepassi** [comment]
`--hparams=use_fixed_batch_size=True,batch_size=1`

**Comment by faniuy** [comment]
Thank you. I'll try it out and come back.

**Comment by faniuy** [comment]
I think the problem might be at the symbol_modality sharding. 
when the num of shards is 16, the shape of "symbol_modality/shared/concat_grad/Slice_x" is 280k / 16 * 512，but the requested_bytes is still 280k * 512 * 4bytes.
that makes the tensors 16x larger.
The problem also exist on the tensors "symbol_modality/shared/concat_grad/tuple/control_dependency_x"

To verify this, I changed symbol_modality_num_shards to 1, and the memory consumption significantly reduced to 5GB

**Comment by rsepassi** [comment]
Wow that’s very surprising. Why would that be? It may make sense to set the
default to 1 if this is true.

**Comment by faniuy** [comment]
@rsepassi sorry, I think that's my misunderstanding. the requested_bytes should not be added together since the shards share the same ptr.
I think it's the batch size settings that reduced the memory consumption.

**Comment by lukaszkaiser** [comment]
I think I'll close this now, feel free to reopen if the problem appears again!
