### ISSUE TITLE
Least invasive way to use a decoder-only Transformer with fast decoding?

### ISSUE THREAD

**Issue by AranKomat** [tensorflow/tensor2tensor#493]
I'd like to use a decoder-only Transformer with fast coding ability to use it as a RL agent in NLP like SeqGAN. transformer_moe.py has decoder-only option, but it seems to require onerous modification of fast decoding method and its related methods of transformer.py. What's your thought?

**Comment by rsepassi** [comment]
There's a `TransformerDecoder` model that you may be able to use. However, you may still have to modify the fast-decode codepath to have it work.

**Comment by AranKomat** [comment]
Thanks so much for your advice. It works very well.

**Comment by phiresky** [comment]
Looks like TransformerDecoder was removed in https://github.com/tensorflow/tensor2tensor/commit/5aedc3deda7b5e640f201874c38413822cb4daf3. Why?

**Comment by tensorator** [comment]
I have the same exact requirement, any luck @phiresky ?
