### ISSUE TITLE
Why `ClassLabelModality` implement `targets_bottom` with `tf.zeros` instead of `tf.one_hot`?

### ISSUE THREAD

**Issue by FrankWork** [tensorflow/tensor2tensor#497]
I want to implement a text classification problem using tensor2tensor. My hparams is
`p.target_modality = (registry.Modalities.CLASS_LABEL, target_vocab_size)`.

However, the `targets_bottom` method of `ClassLabelModality` is defined as:
```
def targets_bottom(self, x):
    with tf.variable_scope(self.name):
      return tf.zeros(
          [common_layers.shape_list(x)[0], 1, 1, self._body_input_depth])
```

Why not use `tf.one_hot`? For example:
```
def targets_bottom(self, x):
    with tf.variable_scope(self.name):
      return tf.one_hot(x, self._vocab_size)
```

**Comment by rsepassi** [comment]
Because `targets_bottom` is meant for auto-regressive models and the model body shouldn't have access to the actual class label, so we pass zeros.
