### ISSUE TITLE
Training on 1.4.1 hangs

### ISSUE THREAD

**Issue by vince62s** [tensorflow/tensor2tensor#498]
Hi,
Since the upgrade to 1.4 I trained a few runs and each hung after a few hours.
seems to be a comparable issue related here #494 and here #496 

Anyone with similar problem ?

Just to be clear, it goes up to freezing the machine need a hard reboot.
I trained without any issue on another toolkit (just to check it was not a hard drive / gpu issue)

**Comment by rsepassi** [comment]
Can you show where it hangs?

**Comment by vince62s** [comment]
on the last run, the last log line was "saving checkpoint" after about 10-12 hours of training.
Not sure for the previous ones, but I think one time was during "restoring checkpoint".

**Comment by vince62s** [comment]
did not happen again so closing this for now

**Comment by SPOT-SMARTHOME** [comment]
I have the same issue and it happens all the time.
