### ISSUE TITLE
Toy DataSet - algorithmic_reverse_nlplike

### ISSUE THREAD

**Issue by ReDeiPirati** [tensorflow/tensor2tensor#5]
Would a Toy DataSet(e.g. predict a reverse sentence) be useful  for sanity-check as used in [tf-seq2seq](https://github.com/google/seq2seq)?

**Comment by rsepassi** [comment]
We have some algorithmic problems which are quite simple.

You can see one used in the trainer test here:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/trainer_utils_test.py

And some of the other algorithmic problems registered here:
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/bin/t2t-datagen#L62

Do these datasets suffice for what you mean?

**Comment by lukaszkaiser** [comment]
The `algorithmic_reverse_decimal40` problem is similar. But it has only 10 symbols (digits) and they're uniformly distributed. I think it'd still be great to have a reversing problem on more realistic data, more tokens and maybe a different distribution. @ReDeiPirati would you be interested in adding one? I'd be happy to help.

**Comment by ReDeiPirati** [comment]
@rsepassi sorry,  i've missed all the dataset generated from algorithmic because i've focused my attention only at the wmt and image problems. @lukaszkaiser that is exactly what i was looking for.  Well if you have some idea, i will be happy to contribute. What do you mean with realistic data? a noisy distribution? or simply a non uniform distribution?

**Comment by lukaszkaiser** [comment]
I'm thinking about adding and `algorithmic_reverse_nlplike` task that:

(1) has more symbols, at least 8k, maybe 32k (more similar to word-level language tasks)
(2) chooses length from a Gaussian, not uniform distribution (or even sth more natural).
(3) chooses the symbols with np.random.zipf (https://en.wikipedia.org/wiki/Zipf%27s_law)

It's still a toy task, but at least more similar to NLP. We could then debug new networks by starting with the very toy algorithmic tasks, then trying this one, and then moving on to real NLP data. But I'll leave it to you to consider and decide what'd be best. Thanks!

**Comment by ReDeiPirati** [comment]
Thank you for the specs, i get to work

**Comment by ReDeiPirati** [comment]
@lukaszkaiser This is my implementation(it's not ready for a PR): [reverse_generator_nlplike](https://github.com/ReDeiPirati/tensor2tensor/blob/algorithmic_reverse_nlplike/tensor2tensor/data_generators/algorithmic.py#L96) and the [test](https://github.com/ReDeiPirati/tensor2tensor/blob/algorithmic_reverse_nlplike/tensor2tensor/data_generators/algorithmic_test.py#L44) that is almost the same as `testReverseGenerator`.
Some consideration:
1. I left the max_length of the sequence as for the reverse task, because we are playing with a toy dataset;
2. The default standard error is set 1.0 but maybe have a bit of variance will it be better? std=10-20% of the max value(as default value)?
3. The default alpha of the Zipf's Law is set to 2.0(as used in examples). Unfortunately i haven't find some interesting value to reproduce a text-like distribution but i'have read that to model languages usually is in the range [1.1-1.6].
4. The Zipf distribution with alpha between [1.0-2.0] produces values that are out of the max token range. I don't find normalization a good idea as suggested in this [post](https://stackoverflow.com/questions/13736115/how-to-create-values-from-zipf-distribution-with-range-n-in-python) but i can run the command until all the values are in the range(bad choice of alpha and/or tokens would never converge with this sanity check).

**Comment by lukaszkaiser** [comment]
It looks very good to me, great thanks. I'd set the Zipf's default to 1.5 maybe, judging by what you say. I also think that you need to generate one-by-one the list, or maybe I'm not understanding something in the current code. As you can see in the standard reverse now, we also shift the symbols by 2, because 0 is reserved for padding and 1 for end-of-sequence symbol. So you'd need to do that and add [1] as end-of-sequence (either only to targets or to both inputs and targets, I guess both are fine).

Great thanks for doing this :). I'll close this issue, make a PR and we can finish it there!
