### ISSUE TITLE
notebook visualisation does not run due to wrong dimensionality of attention_weights 

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#500]
Hi all,

I am playing with the visualisation notebook and after some work, i manage to get everything apart from the last cell running. I find that enc_attn and dec_attn has different shape and therefore in the last cell, during get_attention, they wont concat. It would be great if somebody could take a look and see if i am missing something. 

I have attached the visualisation code here.
[TransformerVisualization.log](https://github.com/tensorflow/tensor2tensor/files/1599469/TransformerVisualization.log)

which is basically the IPYNB file with the ending changed to log. (since github does not support ipynb upload) It recorded also the output at runtime and the stack trace as well.

Thank you very much!

**Comment by benjamincohen1** [comment]
Also been having this issue - will let you know if I make any progress!

**Comment by benjamincohen1** [comment]
It appears that the source of the issue is that np_encdec_atts is of shape (6, 1, 8, 932, 882), while it's expected to be (6, 1, 8, 882, 932)

**Comment by rsepassi** [comment]
I believe this has been fixed.

**Comment by colmantse** [comment]
I have yet to verify it because I am having trouble visualizing byte2byte models because of json dump format. I will report back after I get the byte serialization problem fixed, will report back afterwards and reopen if needed.
