### ISSUE TITLE
Improving Inference Performance "T2T with TF Eager" [QUESTION]

### ISSUE THREAD

**Issue by a-a-e** [tensorflow/tensor2tensor#501]
I have trained a translator model and I'm now trying to use it to interactively decode inputs, like in the README [https://github.com/tensorflow/tensor2tensor/blob/master/README.md](url):

> t2t-decoder \
>   --data_dir= ~/t2t_data \
>   --problems= translate_ende_wmt32k \
>   --model= transformer \
>   --hparams_set= transformer_base_single_gpu \
>   --output_dir= ~/t2t_train/base \
>   --decode_interactive

I want to deploy the model using FLASK but can't figure out how it would work using the method above. Additionally, I saw that there is also no solution so far based on Tensorflow Serving [https://github.com/tensorflow/tensor2tensor/issues/349](url) . The simplest approach seems to be based on the "T2T with TF Eager" notebook provided: [https://colab.research.google.com/notebook#fileId=/v2/external/notebooks/t2t/hello_t2t.ipynb](url) 

![grafik](https://user-images.githubusercontent.com/13366721/34566902-a071d280-f160-11e7-915c-f2eb54007382.png)

Everything works fine, but the problem is that decoding a single sentence takes always 8-10 seconds,  which makes a deployment unfeasible. The issue is that the model is reloaded for any new input: 

![screenshot_1087](https://user-images.githubusercontent.com/13366721/34567096-3135757e-f161-11e7-9fe2-717c267ce391.jpg)

Are there any workarounds in order to get to the same translation speed as with:
> t2t-decoder \
>   --data_dir= ~/t2t_data \
>   --problems= translate_ende_wmt32k \
>   --model= transformer \
>   --hparams_set= transformer_base_single_gpu \
>   --output_dir= ~/t2t_train/base \
>   --decode_interactive

?

**Comment by rsepassi** [comment]
We'll have an updated TensorFlow Serving -based export in an upcoming release.

**Comment by martinpopel** [comment]
@a-a-e see https://github.com/tensorflow/tensor2tensor/tree/master/tensor2tensor/serving and if it works for you please close this issue.

**Comment by a-a-e** [comment]
@martinpopel Yes, great. Thank you.
