### ISSUE TITLE
Why in TranslateEndeWmtBpe32k used TokenTextEncoder, not SubwordTextEncoder? 

### ISSUE THREAD

**Issue by GolovanovSrg** [tensorflow/tensor2tensor#503]
https://github.com/tensorflow/tensor2tensor/blob/c1cd87517cf12f6e0bb0089291466846fc1ac260/tensor2tensor/data_generators/translate_ende.py#L91

**Comment by vince62s** [comment]
Because it supposes that you tokenized with your own BPE model and therefore it does not apply any T2T-internal subtokenization.

**Comment by GolovanovSrg** [comment]
But when using scripts from bin for this problem it is not possible to specify your own tokenizer, and by default TokenTextEncoder is used, which is incorrect. Or am I wrong?

**Comment by vince62s** [comment]
no it is not incorrect, I don't see your point.
this problem expects you to pre-tokenize with a BPE model, and will just use tokens as they are.

**Comment by GolovanovSrg** [comment]
Ок. Thank You.
