### ISSUE TITLE
how to use distributed tensor2tensor

### ISSUE THREAD

**Issue by lqfarmer** [tensorflow/tensor2tensor#51]
Hi, I am a newbie for distributed tensorflow. I followed the instruction here 
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/docs/distributed_training.md
I created the TF_CONFIG, But, I don't know how to use it  during the training in commanline or anyother way.
could you give me some advice or some document instructions.

**Comment by rsepassi** [comment]
Sure, I'll add an example invocation to the doc.

**Comment by rsepassi** [comment]
Should be more clear now. Please take a read.

**Comment by rsepassi** [comment]
And please upgrade to 1.0.8
