### ISSUE TITLE
SOS : problems with attention visualization

### ISSUE THREAD

**Issue by weitaizhang** [tensorflow/tensor2tensor#526]
hi, guys,
I want to have the attention visualization graph printed in the paper. I tried with the viz code in the source code, but encounter two problems:
1. actually I cannot get any visualizations although i could get the encdec_attention arrays. It looks like this:
![image](https://user-images.githubusercontent.com/30943456/35095730-88a2aa56-fc84-11e7-9ff0-26e14ad58ba9.png)
2. I tried to analyze the np_encdec_atts variable without visulization ,but found that the normalized weights does not seem right because the weight of last dimension of each head of each layer is always the biggests.
the following image is the attention weihts of one head of one decoder layer in the variable np_encdec_atts, 
my inputs are(7 words) : 总之 我 要 听 歌 。 _EOS
and the trans are (12 words): anyway , i want to listen to songs . _EOS _PAD _PAD 
![image](https://user-images.githubusercontent.com/30943456/35095852-0c3e3da8-fc85-11e7-80bc-586de8730b5a.png)

Hope you could help me understand more .
Thx.

**Comment by liesun1994** [comment]
How to get the  encdec_attention arrays ? Can u give me the script u used ? Thanks .

**Comment by weitaizhang** [comment]
using tensor2tensor/tensor2tensor/visualization/TransformerVisualization.ipynb
but my results seems something wrong. don't know why.

**Comment by liesun1994** [comment]
@weitaizhang   have you used force decoding before ? With  the given source and target sentences, you can measure word alignment quality .

**Comment by weitaizhang** [comment]
@liesun1994 I do know force decoding and I used that in RNN enc-dec framework. It works and gives word alignments correctly.
here in transformer,  tensor2tensor/tensor2tensor/visualization/TransformerVisualization.ipynb also use the given source and target sentences, But the alignment of each head and each layer does not seems right in my model and data. and that confused me .

**Comment by lkluo** [comment]
I ran TransformerVisualization.ipynb, however, I got constantly error as follows:

LookupError: HParams set transformer_base_single_gpu never registered. Sets registered:

Quite strange as transformer_base_single_gpu shall have been already registered. Anyone figures out what is going on?

**Comment by weitaizhang** [comment]
@lkluo ,sorry, I run with myown hparams which is defined in t2t_usr_dir and import that in the ipynb file.
if you could run training or decoding with normal ways you should also run in ipynb file with the same definition .

**Comment by lkluo** [comment]
@weitaizhang Thanks for reply. As you can see, I used predefined HParams "transformer_base_single_gpu".  I found that, it uses the following function to create hparams:

> def hparams(name):
>  if name not in _HPARAMS:
>   error_msg = "HParams set %s never registered. Sets registered:\n%s"
>    raise LookupError(
>       error_msg % (name,
>                   display_list_by_prefix(list_hparams(), starting_spaces=4)))
>  return _HPARAMS[name]

while name= transformer_base_single_gpu in my case, and in registry.py, _HPARAMS={} is such defined. I have no idea how parameters are passed to _HPARAMS.

**Comment by weitaizhang** [comment]
I think the @registry.registry_hparams would do that.

**Comment by lkluo** [comment]
@weitaizhang Yes, you are right. It turns out that the hparams_set will not be registered by setting name only, e.g., transformer_base_single_gpu. The error dismisses by importing transformer_base_single_gpu  from tensor2tensor.models.transformer.

**Comment by weitaizhang** [comment]
@lkluo  hope you will get the right attention weights and post your results later.
I am still confused with my "wrong" attention weights.

**Comment by lkluo** [comment]
@weitaizhang  I hoped so. However, bugs come one after another. This time I got the following error:
KeyError: "The name 'body/model/parallel_0/body/encoder/layer_0/self_attention/multihead_attention/dot_product_attention/attention_weights' refers to an Operation not in the graph."
I am not sure whether TransformerVisualization.ipynb is up to day, because I also saw some reported bugs somewhere else.

**Comment by liesun1994** [comment]
@weitaizhang yeah , the word alignment is able to print after you modified the transformer code . 💇‍♂️

**Comment by martinpopel** [comment]
> KeyError: "The name 'body/...' refers to an Operation not in the graph."

This usually means that you are trying to load an old checkpoint (<v1.3.0) with a newer T2T version (>=v1.3.0).

**Comment by lkluo** [comment]
@martinpopel Thanks for your reply. I trained my model with T2T-1.4.1, and run iPython notebook with 1.4.2. I also try to downgrade T2T to 1.4.1 version, unfortunately, it has not trainer_lib module that iPython notebook requires. Is there alternative to run that iPython notebook with 1.4.2 and old checkpoint (e.g., <1.4.2). Change the operation name 'body/....'? Thanks.

**Comment by lkluo** [comment]
@martinpopel I finally succeeded in displaying the attention weights, however, I am confused about their interoperation. Take encoder self-attention for example, it seems that all attention weights are equal, as shown below, in which the darkness does not vary.
<img width="478" alt="screen shot 2018-01-30 at 15 04 10" src="https://user-images.githubusercontent.com/26020832/35552579-667fe91c-05cf-11e8-9d47-b826bd0b54d3.png">

**Comment by weitaizhang** [comment]
@lkluo could you give a simple example and print the weights? 
now I think that the attention relation in transformer may be not as explainable as that in rnn nmt.

**Comment by martinpopel** [comment]
@lkluo: I've tried http://goo.gl/wkHexj just once and I confirm I was not able to see anything else than uniform distributions in all the (self)attentions. It seems like a bug, but I had not time to inspect it and report (now I am not able to execute the Colab code at all because of some problems with the `gym` package).

**Comment by lkluo** [comment]
Thanks @martinpopel . I print out the enc_atts in one layer, and seems little change to result in uniform distributions according to the values, right? My input has 4 words.
<img width="564" alt="screen shot 2018-01-30 at 15 29 34" src="https://user-images.githubusercontent.com/26020832/35553687-e06d3faa-05d3-11e8-9a1f-179268846d68.png">

**Comment by lkluo** [comment]
@weitaizhang  see above reply.

**Comment by liesun1994** [comment]
@weitaizhang really amazing . The attentions in transformer  is not the same as word alignment in rnn attention .

**Comment by lkluo** [comment]
@weitaizhang: Just realised that. It could be bug according to martinpopel. BTW, I implemented it using [http://goo.gl/wkHexj](url)

**Comment by weitaizhang** [comment]
I am going to close this issue 'cause I do think the problem has been resolved to some extend.
the alignment in transformer seems a bit more complicated  with more heads than that in rnn nmt.
as @lukaszkaiser said in gitter, we still could find one head that aligns.

**Comment by lkluo** [comment]
@weitaizhang: T2T released 1.4.3 version several hours ago, and a new visualisation iPython notebook. I think I've got what I need. You may also give a try.

**Comment by colmantse** [comment]
It seems that the attention_visualizer does not allow custom data via t2t_usr ? or have I missed something?

**Comment by weitaizhang** [comment]
@colmantse I try that with my own data via t2t_usr.

**Comment by helson73** [comment]
@lkluo 
Could you tell me how did you make that work?
I have similar problem (#557).

**Comment by lkluo** [comment]
You shall use the ipython notebook the authors provided, which locates
under tensor2tensor/visualization. It shall simplify your work.

On 5 Feb 2018 21:00, "Jianri Li" <notifications@github.com> wrote:

@lkluo <https://github.com/lkluo>
Could you tell me how did you make that work?
I have similar problem (#557
<https://github.com/tensorflow/tensor2tensor/issues/557>).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensor2tensor/issues/526#issuecomment-363077703>,
or mute the thread

**Comment by colmantse** [comment]
Dear lkluo,

I checked the source code of the attention_visualisation, there is no parameter t2t_usr_dir, if you pass in the dataset, do you just do t2t_usr_dir=~your_path_to_t2t_usr at the front and it somehow works?

**Comment by lkluo** [comment]
@colmantse: You need to import user defined problems, hparamas, etc from your directory.

**Comment by helson73** [comment]
@lkluo 
My models are trained on OpenNMT, I just want to use the UI. 
Everything about UI is in attention.py, and should not depends on anything else

**Comment by helson73** [comment]
@lkluo 
Suddenly it works, I don't know why, but thanks anyway.

**Comment by colmantse** [comment]
@lkluo @weitaizhang  The new visualization notepad packed everything in the attention_visualizer function, which does not define t2t_usr_dir as an argument. May I know how exactly do you import your custom data?

**Comment by lkluo** [comment]
@colmantse: Suppose your problem is defined in `your_problem.py`, then try `from your_problem import *` ; same as hparams.
