### ISSUE TITLE
attention_lm based rescoring

### ISSUE THREAD

**Issue by pdcoded** [tensorflow/tensor2tensor#53]
@lukaszkaiser Can you please help me with an inference script that basically takes a lot of hypothesis sentences and gives a score for each sentence using tensor2tensor approach. The current rnn based lm approach is quite slow. Meanwhile, I will try training a character level language model using the same technique.

Thanks

**Comment by rsepassi** [comment]
Please use the `t2t-decoder` - see an example invocation in the README.
