### ISSUE TITLE
What model can I use to run image_caption

### ISSUE THREAD

**Issue by apeterswu** [tensorflow/tensor2tensor#530]
Hi,

I want to run image caption experiment on transformer, but seems transformer model doesn't support image caption exp. So what model can I use to run image caption experiment?

I tryied multimodel and slicenet by setting like this:

PROBLEM=image_ms_coco_tokens32k
MODEL=multi_model
HPARAMS=multimodel_base

But they all push error: 
`TypeError: get_or_generate_vocab() missing 1 required positional argument: 'sources'`

What should I do if I want to run this exp? Thanks.

**Comment by YunseokJANG** [comment]
Hi, did you find the answer (a setting) that can train an image captioning module? If you found, then can you share the configurations (command, code, blog post, or whatever) ?
