### ISSUE TITLE
How to use multi_model correctly?

### ISSUE THREAD

**Issue by SugarInGithub** [tensorflow/tensor2tensor#531]
I haved tried to run multi_model, but the loss of multimodel on cifar10 is very large (around 450). And multimodel cannot run on nmt tasks. 

How to use multi_model correctly? 
(It seems that the model has not been finished?)

Thanks.

**Comment by rsepassi** [comment]
Unfortunately MultiModel is no longer supported though we may add back support later. Contributions welcome. See #487.

**Comment by estathop** [comment]
I can see it in the list with the available models but is it still dropped ? is it that hard to alterate it and use it accordingly?
