### ISSUE TITLE
saving checkpoint after restoring

### ISSUE THREAD

**Issue by lkluo** [tensorflow/tensor2tensor#534]
During continuously training, the program automatically saves checkpoint immediately after it restores the latest one, thus resulting in two checkpoint models with only one step gap, e.g., , model.ckpt-1000 and model.ckpt-1001. I did find difference between these two models via testing, i.e., resulting in different outputs. May I know why saving checkpoints in such a manner? Any special concern?

**Comment by martinpopel** [comment]
This issue is a duplicate of https://github.com/tensorflow/tensor2tensor/issues/495#issuecomment-358975868

**Comment by lkluo** [comment]
@martinpopel Yes, I trained an MT model. The BLEU difference is tiny for my test data (around 15k sentences), but the translations vary in terms of fluency for some sentences.
