### ISSUE TITLE
Prevent use of continuous_train_and_eval with the ValidationMonitor 

### ISSUE THREAD

**Issue by epurdyf** [tensorflow/tensor2tensor#537]
Right now, the ValidationMonitor is silently ignored when the schedule is set to continuous_train_and_eval. This is a frustrating issue to debug, especially since the default schedule recently switched to continuous_train_and_eval (and thus code that recently worked can stop working). 

I think that the best solution would be an explicit failure in this situation, with an informative error message, since that ensures that the user knows they have chosen an incompatible set of options.

**Comment by rsepassi** [comment]
Thanks for the issue. I've added a warning which should come out with the next release. Use `--schedule=train_and_evaluate` to use `ValidationMonitor`.
