### ISSUE TITLE
Any workable TransformerVisualization.ipynb?

### ISSUE THREAD

**Issue by lkluo** [tensorflow/tensor2tensor#540]
It occurs to me that the Jupyter notebook does not work after simply changing user-defined directories. For example, I need to import transformer_base_single_gpu when I use the problem. I also need to define FLAGS.decode_hparams because it is missing. After that, I encountered the following error:
KeyError: "The name 'body/model/parallel_0/body/encoder/layer_0/self_attention/multihead_attention/dot_product_attention/attention_weights' refers to an Operation not in the graph."

I am not sure if I have wrong configuration or missed something. Any suggestions?

**Comment by lukaszkaiser** [comment]
Could you try this notebook: goo.gl/wkHexj ? I think that one works, please reopen if it does not!

**Comment by lkluo** [comment]
@lukaszkaiser. Yes, the notebook does work, however, the result seems wrong. I got uniform distributed attentions, and even strangely, the attention array has rows values summing up not equal to one., details and similar problems are in #526.
