### ISSUE TITLE
Vocabulary size in WMT translation task

### ISSUE THREAD

**Issue by cshanbo** [tensorflow/tensor2tensor#55]
Hi all,
I'm a little confused with the `vocab_size` defined in [problem_hparams.py](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/problem_hparams.py#L407).

In `wmt_ende_bpe32k`, the `vocab_size` param is set to `40960`, while in `wmt_enfr_tokens`, there's a `wrong_vocab_size` param, which is set to `2**13` if in `wmt_enfr_tokens_8k`. I'm guessing that this might not be the actual number of the vocabulary.

My question is:
When setting [input_modality](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/problem_hparams.py#L409), how to set the `vocab_size`? 

More specifically, If I have a separated source vocab and target vocab, with size n_src, n_tgt, respectively, should I set the `vocab_size` to `n_src + n_tgt` or something else?

Thank you

**Comment by lukaszkaiser** [comment]
As for BPE, unluckily it's called "bpe32k" but it contains about 40000 word-pieces. We're trying to move away from that, we used it because it was used in previous work. As for `wrong_vocab_size`, I'll need to take a look...

**Comment by rsepassi** [comment]
Yes, this is currently a bit confusing. The vocabulary file backing a `SubwordTextEncoder` is built with a target vocab size - i.e. the process will try to achieve a vocab size close to that target. That target vocab size is used in the filename of the vocab file, e.g. `tokens.vocab.8192`. The actual vocab size will likely be different than the target vocab size, hence `wrong_vocab_size`. `wrong_vocab_size` I believe is only used for the filename. The actual vocab size is recovered from the instantiated `SubwordTextEncoder` and used to instantiate the modality. The modality spec needs the true vocab size.
