### ISSUE TITLE
Difference between NMT and T2T BLEU

### ISSUE THREAD

**Issue by dsmiller** [tensorflow/tensor2tensor#569]
The BLEU scoring script at tensorflow/nmt/nmt/scripts/bleu.py and the newly-committed t2t-bleu.py  compute vastly different BLEU scores, even when similarly parameterized (NMT produces higher scores).

Can anyone clarify the main points where these scripts differ?

**Comment by martinpopel** [comment]
I am the author of [t2t-bleu](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/bin/t2t_bleu.py) (but it is mostly reusing the code which was already in T2T). It expects **raw sentences as input** and it tokenizes them internally, so it gives exactly the same results as the authoritative implementation [mteval-v14.pl](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v14.pl) (with `--international-tokenization`) and as [sacréBLEU](https://github.com/awslabs/sockeye/tree/master/contrib/sacrebleu) (with `-lc --tokenization intl`). It's main advantage over these two scripts is that it can also generate learning curves to a TensorBoard events file (and that it is available out of the box in T2T without introducing any dependencies). For reporting BLEU in publications, I strongly recommend [sacréBLEU](https://github.com/awslabs/sockeye/tree/master/contrib/sacrebleu) and reporting its *signature*.

So far I was not aware of [nmt/scripts/bleu.py](https://github.com/tensorflow/nmt/blob/master/nmt/scripts/bleu.py). It seems as one of the thousands of BLEU reimplementations that expect **tokenized sentences as input**, and are thus not self-contained and the resulting scores varies greatly depending on the tokenization used.

**Comment by dsmiller** [comment]
OK, thanks for clearing that up.
