### ISSUE TITLE
Contributing - Permission denied (403)

### ISSUE THREAD

**Issue by nadavb** [tensorflow/tensor2tensor#571]
Hi, I am trying to contribute.
Trying to push to tensor2tensor remote, on a different branch so I can create a pull request, 

I do git `push -u origin <branch-name>`
and I get: remote: `Permission to tensorflow/tensor2tensor.git denied to nadavb`

Are there any specific contribution guidelines?

**Comment by martinpopel** [comment]
As usual on GitHub, you don't have write (push) access to this repo `tensorflow/tensor2tensor` and you don't need it.
Fork the repo and push to your fork, i.e. `nadavb/tensor2tensor`, preferably to a special branch, which will be used only for the pull request.

**Comment by nadavb** [comment]
Done. Thanks.
