### ISSUE TITLE
Kinetics dataset and I3C models integration

### ISSUE THREAD

**Issue by ReDeiPirati** [tensorflow/tensor2tensor#60]
I think that would be very cool and attractive adding the support for the [Kinetics Dataset](https://deepmind.com/research/open-source/open-source-datasets/kinetics/) and the last [Inflated 3D ConvNet(I3C)](https://arxiv.org/pdf/1705.07750.pdf) models to `tensor2tensor`.

**Comment by lukaszkaiser** [comment]
We welcome a contribution!

**Comment by rsepassi** [comment]
Closing as this is not an active issue. Please do feel free to reopen if you plan to work on this.
