### ISSUE TITLE
TypeError: %d format: a number is required, not method

### ISSUE THREAD

**Issue by leisurehippo** [tensorflow/tensor2tensor#618]
I run t2t-datagen --data_dir=$DATA_DIR --tmp_dir=$TMP_DIR --problem=$PROBLEM
and PROBLEM=summarize_cnn_dailymail32k
I occur error like this
TypeError: %d format: a number is required, not method
where did i wrong? Does it for the python version?
my python version is 3.5 and tensorflow version is 1.4.0

**Comment by martinpopel** [comment]
I believe this is already fixed by #600. Use the newest T2T from GitHub master or add the `@property` line.
BTW: When reporting an error it is helpful to add a relevant part of the stack trace.

**Comment by leisurehippo** [comment]
thank you. I add the @property line and it works

**Comment by stefan-it** [comment]
@leisurehippo I think you close that issue then :)
