### ISSUE TITLE
When will the code of paper "GENERATING WIKIPEDIA BY SUMMARIZING LONG SEQUENCES" release?

### ISSUE THREAD

**Issue by leisurehippo** [tensorflow/tensor2tensor#619]
I found https://gist.github.com/peterjliu/f0dc9152a630520dc604c783db963aa7 said the code will be soon released. I wonder is there any estimation to the code's releasing date? And Will the dataset or script to make the article -> citation, search results from common crawl be released with code?

**Comment by stefan-it** [comment]
With *1.6.1* this is now available in T2T :)

**Comment by rsepassi** [comment]
Yup, @stefan-it is right, now released! See #757 for the tracking bug for issues that have popped up.

**Comment by ihimanshub** [comment]
i am looking for the code for this paper. Cannot find it anywhere. Can you please provide the link for the same
