### ISSUE TITLE
compatibility TensorFlow 1.1.0

### ISSUE THREAD

**Issue by tonyw** [tensorflow/tensor2tensor#62]
TensorFlow version : 1.1.0
OS:CentOS : 7.0
tensor2tensor version : 1.0.7 from pip

I encounter an exception when I run 'Work Through'.
tensor2tensor/utils/trainer_utils.py use tf.contrib.learn.Estimator.Invoke Estimator constructor with session_config.But In tensorflow 1.1.0 ,tf.contrib.learn.Estimator constructor no session_config args.
So tensor2tensor not compatibility with TensorFlow 1.1.0?

**Comment by lukaszkaiser** [comment]
Sorry, we require TF 1.2.
