### ISSUE TITLE
OOM during eval when use "schedule=continuous_train_and_eval"

### ISSUE THREAD

**Issue by NO-0044** [tensorflow/tensor2tensor#627]
When use `schedule=train`, I can set `batch_size=4096` and the training does well. But when use the default `schedule=continuous_train_and_eval`, `batch_size` should be set to around 1024, otherwise it will raise OOM error during evaluation. I tried to set `eval_drop_long_sequences` and use 1/4 training batch_size in evaluation but doesn't work. 'continuous_train_and_eval' should have released the memory before evaluation starts, does anyone else run into this problem?

**Comment by rsepassi** [comment]
Seems that #581 has this same issue. Closing in favor of it.

**Comment by martinpopel** [comment]
I think this is a different issue. Here `schedule=continuous_train_and_eval` is used and I guess the OOM fail is immediately during the first evaluation.

#581 is about `schedule=train` and OOM after several days of training.

**Comment by NO-0044** [comment]
I choose to run training and evaluation separately at last. I guess when use `schedule=continuous_train_and_eval`, not all memory was released when switch between training and eval. Once the first evaluation starts ,OOM happens.
