### ISSUE TITLE
tensor2tensor lstm and transformer model batch size mismatch

### ISSUE THREAD

**Issue by sufengniu** [tensorflow/tensor2tensor#640]
Hello I have put this problem in [stackoverflow,](https://stackoverflow.com/questions/49119963/tensor2tensor-lstm-and-transformer-model-batch-size-mismatch) not sure if this problem comes from my side or the code. I try to add my customized model, but I found something is wrong on the batch_size, so I copy a original lstm model and transformer model to have a small test. I am using machine translation task (translate_ende_wmt32k). 

in the body function, the `inputs=features["inputs"]` is 4-dim tensor, and convert to a 3-dim tensor by following code:
`inputs = common_layers.flatten4d3d(inputs)`
according to tensor2tensor comments said, the inputs should sized as `[batch_size x max_time x size]`. however, my code keeps complaining the error, and I did a small testing, I change the above code to (I set hparams.batch_size as 512):
```
    # inputs is original 4-dim tensor from features["inputs"] [batch_size, max_time, 1, hidden_size]
     test = tf.ones([hparams.batch_size, tf.shape(inputs)[1], tf.shape(inputs)[2], 1])
    inputs = test*inputs
```
Then, when I run it, after session started, I saw the error:

> InvalidArgumentError (see above for traceback): Incompatible shapes:
> [512,57,1,1] vs. [6,57,1,128]

it turns out the inputs batch_size is 6 (not 512 set in hparams.batch_size), while test batch_size is 512. I found for both transformer and lstm model has such problems, and when the hparams.batch_size set as 1024, the inputs batch_size becomes 20. Is this designed by intention or this is the bug?

Thank you

**Comment by rsepassi** [comment]
`hparams.batch_size` typically specifies the number of tokens per batch (for problems with variable length inputs). Sequences of similar length are grouped together dynamically so that the real batch size times the length are approximately `hparams.batch_size`.

**Comment by sufengniu** [comment]
Thank you. My understanding is that the bucket is grouped by the sequence length, According to your description. do you mean that `hparams.batch_size` actually represents how many buckets per batch? and "the real batch size times the length are approximately `hparams.batch_size`" In my case, do you mean the real batch size is 512/6 ? Thanks

**Comment by rsepassi** [comment]
There are 3 terms to be clear on:
* `hparams.batch_size`: this number is the *approximate* number of tokens in a real batch (i.e. approximates batch size times sequence length). It is used to guide the bucketing.
* batch size: when I refer to this, it is the true batch size (i.e. the size of dim 0 of the Tensor) of an actual batch flowing through the model. It is variable. For buckets that have long sequences, the batch size will be smaller. For buckets that have shorter sequences, the batch size will be bigger. 
* sequence length: this is the true sequence length (i.e. the size of dim 1 of the Tensor) of an actual batch flowing through the model.

**Comment by rsepassi** [comment]
And apologies that the naming is so confusing.

**Comment by sufengniu** [comment]
Thank you for the clear answer. will close the issue
