### ISSUE TITLE
naive question: how can i use transformer without using estimator

### ISSUE THREAD

**Issue by facingfacing** [tensorflow/tensor2tensor#654]
maybe it's a question about tensorflow cuz i'm quite new in tf..
i would like to do some ensemble with transformer models which needs to do some single step decoding ...
i'm trying to load ckpt with saver , and reuse the model..
i wrote a function imitated decode_from_file , but it doesn't seem that the model params are reused successfully.. and the decode result is quite naive...
can anybody give me some help... thanks a lot...

the code is like belows:

def ensemble_from_file(model,
                     filename,
                     hparams,
                     decode_hp,
                     decode_to_file=None,
                     checkpoint_path=None):
  """Compute predictions on entries in filename and write them out."""
......"""the same with decode_from_file() in utils/decoding.py"""
  def input_fn():
    input_gen = _decode_batch_input_fn(
        problem_id, num_decode_batches, sorted_inputs, inputs_vocab,
        decode_hp.batch_size, decode_hp.max_input_size)
    gen_fn = make_input_fn_from_generator(input_gen)
    example = gen_fn()
    return _decode_input_tensor_to_features_dict(example, hparams)

  features = input_fn()

  config = tf.ConfigProto(allow_soft_placement=True)      
  saver = tf.train.import_meta_graph(checkpoint_path + ".meta")
  with tf.Session(config=config) as sess:

    with tf.variable_scope(tf.get_variable_scope()):
      model.set_mode(tf.estimator.ModeKeys.PREDICT)      
      fast_result = model._beam_decode(
        features,
        decode_length=50,
        beam_size=5,
        top_beams=1,
        alpha=0.6)
      sess.run(tf.global_variables_initializer())
      saver.restore(sess, checkpoint_path)
      fast_res = sess.run(fast_result)
        
......"""print the decode results"""

**Comment by facingfacing** [comment]
moving~~finally got it...

def input_fn():
    input_gen = _decode_batch_input_fn(
        problem_id, num_decode_batches, sorted_inputs, inputs_vocab,
        decode_hp.batch_size, decode_hp.max_input_size)
    gen_fn = make_input_fn_from_generator(input_gen)
    example = gen_fn()
    return _decode_input_tensor_to_features_dict(example, hparams)

  features = input_fn()

  config = tf.ConfigProto(allow_soft_placement=True)   
  with tf.Session(config=config) as sess:
      model.set_mode(tf.estimator.ModeKeys.PREDICT)
      fast_result = model._beam_decode(
        features,
        decode_length=50,
        beam_size=5,
        top_beams=1,
        alpha=0.6) 
      saver = tf.train.Saver(tf.global_variables())
      saver.restore(sess, checkpoint_path)
      fast_res = sess.run(fast_result)

works for me...

**Comment by facingfacing** [comment]
moving~~finally got it...

def input_fn():
    input_gen = _decode_batch_input_fn(
        problem_id, num_decode_batches, sorted_inputs, inputs_vocab,
        decode_hp.batch_size, decode_hp.max_input_size)
    gen_fn = make_input_fn_from_generator(input_gen)
    example = gen_fn()
    return _decode_input_tensor_to_features_dict(example, hparams)

  features = input_fn()

  config = tf.ConfigProto(allow_soft_placement=True)   
  with tf.Session(config=config) as sess:
      model.set_mode(tf.estimator.ModeKeys.PREDICT)
      fast_result = model._beam_decode(
        features,
        decode_length=50,
        beam_size=5,
        top_beams=1,
        alpha=0.6) 
      saver = tf.train.Saver(tf.global_variables())
      saver.restore(sess, checkpoint_path)
      fast_res = sess.run(fast_result)

works for me...

**Comment by tobyoup** [comment]
@facingfacing  Could you kindly share your ensemble codes when decoding? Thanks!
