### ISSUE TITLE
NMT for dummies

### ISSUE THREAD

**Issue by dinosaxon** [tensorflow/tensor2tensor#660]
Is there any NMT tutorial for dummies?

I would like to know if there is a step-by-step tutorial on how an NMT engine is trained and what each parameter means.

Thank you for your help!

**Comment by martinpopel** [comment]
A step-by-step guide is the ["Walkthrough"](https://github.com/tensorflow/tensor2tensor#walkthrough).
Tensor2tensor is a research project with SotA results and frequent changes in the source code, not a tutorial framework for dummies. Thus the best explanation of most parameters is in the source code (the [documentation](https://github.com/tensorflow/tensor2tensor/tree/master/docs) may be outdated and incomplete).
There are many other NMT frameworks which are more suitable (I think) for tutorials, e.g. [OpenNMT](http://opennmt.net/) and [Neural Monkey](https://github.com/ufal/neuralmonkey) (see its [NMT tutorial](http://neural-monkey.readthedocs.io/en/latest/machine_translation.html)) - but these don't achieve the SotA results ([yet](https://github.com/OpenNMT/Presentations/blob/master/ONMT-WorkshopParis2018/03-VincentNguyen-OpenNMT_Evaluation.pdf)).

**Comment by dinosaxon** [comment]
Thank you for your reply. I can understand that it's difficult to maintain a tutorial, but I was wondering if any users created something from their experience so far.

**Comment by martinpopel** [comment]
Oh yes, my experience is summarized in this [paper](http://ufallab.ms.mff.cuni.cz/~popel/training-tips-transformer.pdf).

**Comment by dinosaxon** [comment]
That's great! This is what I was looking for.

**Comment by vince62s** [comment]
@martinpopel FYI I replicated T2T EN-DE with both OpentNMT-TF AND OpenNMT-py
the TF one is already there for download.
the Pytorch one will be shortly.

**Comment by stefan-it** [comment]
@dinosaxon Another great nmt tutorial is the TensorFlow [nmt](https://github.com/tensorflow/nmt) project :) There are many useful explanations which really helps to understand sequence-to-sequence models.

**Comment by dinosaxon** [comment]
@stefan-it Thank you, Stefan! This is also great :)
