### ISSUE TITLE
Leave text as is or provide a translation

### ISSUE THREAD

**Issue by dinosaxon** [tensorflow/tensor2tensor#673]
Hi All

Is there any way to leave a specific text untranslated or to translate it with a specific translation?

For instance, in the sentence "This is a A1" I want to leave "A1" untranslated or to translate it as "B1".

Thanks a lot for your help.

**Comment by lukaszkaiser** [comment]
Unluckily, this is a bit harder with neural network translation (NMT) than with the old-fashioned methods. In general, the networks usually learn on their own which text to leave -- it's hard to force them though. The problem is simply that it's unclear which text to leave and which to translate.
