### ISSUE TITLE
How to choose eval metric. Changing over time in Transformer model.

### ISSUE THREAD

**Issue by gaceladri** [tensorflow/tensor2tensor#681]
*help*

### Description

> I am running the summarization problem with the transformer model as the examples that you have. I changed the hparams.batch_size = 1400 and hparams.num_hidden_layers = 8. The hparams is as the example --hparams_set=transformer_prepend and the question that I have is that each time that I run the model my eval metric changes. The first time that I ran it was top5 acc, then it crashed out of memory and now It is evaluating on negative log perplexity. I think that the best would be rouge 2. Is it influencing the model performance? So, if it is influencing the model, how could I define the metric on what I would like to train the model?

### *TensorFlow* and *tensor2tensor* versions

> tensor2tensor==1.5.5
tensorboard==1.6.0
tensorflow-gpu==1.7.0rc1

### "Problem"
metrics-summarize_cnn_dailymail32k/accuracy_top5 = 0.22541702
metrics-summarize_cnn_dailymail32k/neg_log_perplexity = -6.9920864

and if I don't change anything the metric is rouge 2.

Thanks!

Edit: maybe it can lead to a better generalization :smile:

**Comment by martinpopel** [comment]
I have never done summarization, so I may be wrong but in general: T2T reports *multiple* metrics (or loss functions) during training. The set of metrics can be configured for each problem, but I don't believe it depends on batch_size or other hparams. Are you sure that there was just one metric reported and it was different one each time?
Only one metric is used for computing the loss (and thus driving the training through backpropagation). Very often this is cross-entropy (neg-log-perplexity). You cannot simply use an arbitrary metric (BLEU, ROUGE, top5 acc,...) as the loss function, as not all metric allow computing derivative (well, you could use reinforcement learning, but that's a different story). So the set of metrics reported does not influence the learning itself, except for possible early stopping.

**Comment by gaceladri** [comment]
@martinpopel, Now, I just loaded the model again to keep training and it is evaluating on a bleu score at this moment.

metrics-summarize_cnn_dailymail32k/approx_bleu_score = 0.0062942887

> "So the set of metrics reported does not influence the learning itself, except for possible early stopping."

Ok, so I do not have any problem then when evaluating on different metrics I understand?

Thanks!

**Comment by martinpopel** [comment]
The training log is OK, it reports just loss (which is cross-entropy as in other Text2Text problems).
The eval log is really strange:
`SummarizeCnnDailymail32k` [inherits](https://github.com/tensorflow/tensor2tensor/blob/957b5cde/tensor2tensor/data_generators/cnn_dailymail.py#L207) from `Text2TextProblem` including the [eval_metrics](https://github.com/tensorflow/tensor2tensor/blob/957b5c/tensor2tensor/data_generators/text_problems.py#L298) method, which defines seven metrics: ACC, ACC_TOP5, ACC_PER_SEQ, NEG_LOG_PERPLEXITY, APPROX_BLEU, ROUGE_2_F, ROUGE_L_F.
All these 7 metrics should be reported during the evaluation. I have no idea why you get just one (probably randomly chosen) metric.

**Comment by gaceladri** [comment]
@martinpopel Yes, it seems this, that each time that it initialize choose a random metric, I am looking for the possible cause. I will try to reinstall the t2t pipeline and run again the saved model to check why it is just displaying one metric. Seems weird. Thanks for the support!!

**Comment by nimas62** [comment]
Your problem might be related to [this case](https://github.com/tensorflow/tensor2tensor/issues/650), where just 3 metrics are reported during training. I solved it for myself, and now I have all the five metrics in the log.

Beside it, could you read [this post](https://github.com/tensorflow/tensor2tensor/issues/680) of mine and tell me if you are getting good decoded results from the model? As I can not use transformer_prepend because it destroys all the outputs.

**Comment by gaceladri** [comment]
Fixed @martinpopel. I just copied and pasted the new t2t_model.py into my code and now it displays me all the metrics. :+1: What I am seeing now is that the eval step is being doing in CPU so, so slowly. I will continue with that but the issue is fixed!

Thanks for the support both @nimas62

**Comment by gaceladri** [comment]
@martinpopel Yes, it seems this, that each time that it initialize choose a random metric, I am looking for the possible cause. I will try to reinstall the t2t pipeline and run again the saved model to check why it is just displaying one metric. Seems weird. Thanks for the support!!
