### ISSUE TITLE
*help* Looking for the training inner loop for transformer model

### ISSUE THREAD

**Issue by mrzjy** [tensorflow/tensor2tensor#695]
This is more like a question because I'm not sure about how the training is implemented in the code. I thought that the [body](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py#L139) function in transformer.py was like a step function to me, which should be called each step during a generation of sequences.

While clearly there is the loop in [fast decode](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py#L489), I couldn't find the corresponding loop for training. Hence, I think that maybe there's already the whole generation process within this body function?

Can anyone shed light on this?

**Comment by benleetownsend** [comment]
The transformer model is trained with teacher forcing. Therefore, no such loop is present during training.
