### ISSUE TITLE
Decoding Error for the Default Translation Task

### ISSUE THREAD

**Issue by shantipriyap** [tensorflow/tensor2tensor#696]
While trying to decoding for the default problem (translate_ende_wmt32k) getting the below mentioned error. Please find the Tensorflow and Python version for reference and suggest if any dependency is with the versions I am using. The training was ok.

Plython and Tensorflow Version
-------------------------------------------
tensorboard==1.6.0
tensorflow==1.6.0
Python 3.5.4

Decoding Issue for the translation task
----------------------------------------------------
./t2t-decoder \
  --data_dir=...../tensor2tensor/t2t_data \
  --problems=translate_ende_wmt32k \
  --model=transformer \
  --hparams_set=transformer_base_single_gpu \
  --output_dir=.../tensor2tensor/t2t_train/base \
  --decode_hparams="beam_size=4,alpha=0.6" \
  --decode_from_file=..../tensor2tensor/t2t_data/decode_this.txt \
  --decode_to_file=..../tensor2tensor/t2t_data/translation.en

Error
********
tensor2tensor/layers/common_layers.py:496: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "./t2t-decoder", line 16, in <module>
    tf.app.run()
  File "/lnet/spec/work/people/parida/python-venv/py3.5.4-env/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run

----
----
    "Tensor._shape cannot be assigned, use Tensor.set_shape instead.")
ValueError: Tensor._shape cannot be assigned, use Tensor.set_shape instead.

**Comment by martinpopel** [comment]
You have not reported your tensor2tensor version, which is the most important piece of information in bug reports. I guess you are using T2T 1.4.2 which is the last version with TensorFlow 1.4 support. However, it does not support TF 1.6. If you want to continue using TF 1.6, update to newer T2T.

BTW: the most important from your error log are the last two lines, where you omitted the location in source code, where `_shape` is assigned.

**Comment by shantipriyap** [comment]
Hi Martin,

Sorry for the incomplete info(T2T version, error log) in the reported issue. Thanks for your prompt response. As per your suggestion, updated T2T to the latest version as below. Now the decoding is working fine for the sample. Closing the issue now.  

T2T and Tensorflow Version
********************************
tensor2tensor (1.5.6)
tensorboard (1.6.0)
tensorflow (1.6.0)

Decoding Result
*********************
[2018-04-10 13:33:05,299] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[2018-04-10 13:33:05,378] Done running local_init_op.
INFO:tensorflow:Inference results INPUT: Goodbye world
[2018-04-10 13:33:10,069] Inference results INPUT: Goodbye world
INFO:tensorflow:Inference results OUTPUT: Die Weltwelt welt
[2018-04-10 13:33:10,069] Inference results OUTPUT: Die Weltwelt welt
INFO:tensorflow:Inference results INPUT: Hello world
[2018-04-10 13:33:10,069] Inference results INPUT: Hello world
INFO:tensorflow:Inference results OUTPUT: Hallo Welt Welt
[2018-04-10 13:33:10,070] Inference results OUTPUT: Hallo Welt Welt

BLEU Score
**************
t2t_data/ref-translation.de
BLEU_uncased =  42.04
BLEU_cased =  37.99
