### ISSUE TITLE
*Help*How to get the results of word embeddings

### ISSUE THREAD

**Issue by xiangdouou** [tensorflow/tensor2tensor#709]
#
*help* 
### Description
Hi，I have trained the transformer model，
PROBLEM=translate_ende_wmt32k
MODEL=transformer
HPARAMS=transformer_base_single_gpu
But I want to get the word embedding result. Can you tell me how to get the result of word embedding(word to vector)? 
Thank you!
> …

### *TensorFlow* and *tensor2tensor* versions
TensorFlow-gpu==1.4.0 t2t==1.5.4

> …

### In case of bug report: Steps to reproduce the problem

> …

### In case of bug report: Error log

> …

**Comment by xiangdouou** [comment]
Hello,Can anyone help me?

**Comment by martinpopel** [comment]
The embeddings are stored in the checkpoint.

**Comment by xiangdouou** [comment]
Thank you very much!@martinpopel
I will look at the checkpoint.

**Comment by stefan-it** [comment]
@xiangdouou Does that hint solves the issue? If that is the case, please close that issue :)

**Comment by guotong1988** [comment]
May I know what word embedding can be got?
