### ISSUE TITLE
*help* How to draw customized BLEU graph using model checkpoints 

### ISSUE THREAD

**Issue by shantipriyap** [tensorflow/tensor2tensor#713]
### Description

How to draw a customized BLEU graph using the saved model checkpoints. i) Want to get the BLEU score for individual checkpoints, to plot the graph manually. ii) In this case how to mention the X-axis of the BLEU graph.

**Comment by martinpopel** [comment]
I used `t2t-translate-all` and `t2t-bleu` for this. If you don't like the TensorBoard screenshots, you can save each curve from TensorBoard to a csv file and then re-plot it with your favorite tool.

For example, I used `gnuplot < my.plt > my.tex` to create graphs for [my paper](https://arxiv.org/pdf/1804.00247.pdf), where `my.plt` looks like
```gnuplot
set term lua tikz latex createstyle size 13.6,4.5
set datafile separator ","
set key font ",8"
set key inside right bottom

set ylabel "BLEU" offset 0
set yrange [23.5:27.1]
set ytics autofreq 0, 1, 50

set xlabel "Training time (hours)" offset 0
set xrange [0:270]
set x2label "Training time (days)"
set x2range [0:11.25]
set xtics nomirror
set x2tics autofreq 1, 1, 50

#set style data linespoints
set style line 1 lt 1 lw 2 pt  5 ps 2 pi 250 lc rgb '#E41A1C' # red
set style line 2 lt 1 lw 2 pt  7 ps 2 pi 250 lc rgb '#377EB8' # blue

plot "plots/c57-8GPU-b15.csv"  using ($1 / 3600):3 w lp ls 1 title "58M training sentences", \
     "plots/c1-8GPU-b15.csv"   using ($1 / 3600):3 w lp ls 2 title "16M training sentences", \
```
