### ISSUE TITLE
*feature request* Add JFLEG Dataset

### ISSUE THREAD

**Issue by pynchmeister** [tensorflow/tensor2tensor#716]
### Description

I am creating a chatbot for the purpose of grammatical error correction(GEC). I want to use this John Hopkins University dataset: https://github.com/keisks/jfleg

Thank you!

**Comment by lukaszkaiser** [comment]
Please consider making a PR and add this dataset, it's really easy to do! Check out this tutorial:
https://cloud.google.com/blog/big-data/2018/02/cloud-poetry-training-and-hyperparameter-tuning-custom-text-models-on-cloud-ml-engine
