### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by onchiptech** [tensorflow/tensor2tensor#726]
I am getting the following error when I run t2t-trainer with --cloud_tpu option  
------------------------------------------
vm_info = list_vm_names_and_ips()
  File "/home/gmail/anaconda3/lib/python3.6/site-packages/tensor2tensor/utils/cloud_tpu.py", line 252, in list_vm_n
ames_and_ips
    lines = [l.split() for l in list_out.split("\n")[1:-1]]
TypeError: a bytes-like object is required, not 'str'
---------------------------------------------

**Comment by rsepassi** [comment]
I believe this has been fixed. Please try again with the latest version of tensor2tensor.
