### ISSUE TITLE
*help* Reshape a checkpoint with a new vocabulary size

### ISSUE THREAD

**Issue by davidecaroselli** [tensorflow/tensor2tensor#728]
### Description

I would like to transform a checkpoint of a Transformer model with `transformer_base` configuration, expanding its vocabulary. For example: I have a checkpoint with a vocabulary of 30718 symbols, and I would like to transform its variables in order to support a new vocabulary, extended to 31836.

*Note:* I am aware that subwords should be strong enough to represent even new words, but this is not the point of what I'm trying to do: I want to "normalize" the size of the network in the GPU RAM. :)

So for my understanding there are 3 groups of 16 variables each in the checkpoint that depends upon the vocabulary size:
```
transformer/symbol_modality_30718_512/shared/weights_0 [1920, 512]
transformer/symbol_modality_30718_512/shared/weights_1 [1920, 512]
[...]
transformer/symbol_modality_30718_512/shared/weights_15 [1919, 512]
```
```
training/transformer/symbol_modality_30718_512/shared/weights_0/Adam [1920, 512]
training/transformer/symbol_modality_30718_512/shared/weights_1/Adam [1920, 512]
[...]
training/transformer/symbol_modality_30718_512/shared/weights_15/Adam [1919, 512]
```
```
training/transformer/symbol_modality_30718_512/shared/weights_0/Adam_1 [1920, 512]
training/transformer/symbol_modality_30718_512/shared/weights_1/Adam_1 [1920, 512]
[...]
training/transformer/symbol_modality_30718_512/shared/weights_15/Adam_1 [1919, 512]
```

The sum of the first dimension is exactly 30718 (vocabulary size) for all 3 groups; this suggested to me that there is a correlation between the symbols and these tensors. I suppose that the i-th element of `transformer/symbol_modality_30718_512/shared/weights_0` is the tensor needed to embed symbol i-th of the vocabulary, while i-th element of `transformer/symbol_modality_30718_512/shared/weights_1` is the tensor needed to embed symbol (i + 1920)-th of the vocabulary.

So the idea is: if I "pad" somehow unused vocabulary positions with tensors of [512] zeros, the calculations made by the network should remain unchanged, in other words the network should be able to translate in the exact same way sentences made with words already known (with index less than 30718).

So I tried doing this:
1. "flattened" each one of the 3 groups in a single tensor of shape [30718, 512]
2. I added a padding of 1118 tensors created with `np.zeros(shape=[512])`, so the new flattened tensor has shape [31836, 512]
3. Re-group the flattened tensor in 16 groups of size 1990, 1990, 1990, 1990, 1990, 1990, 1990, 1990, 1990, 1990, 1990, 1990, 1989, 1989, 1989, 1989.

I then replaced the old variable with new ones:
`transformer/symbol_modality_30718_512/shared/weights_0 [1920, 512]` has become `transformer/symbol_modality_31836_512/shared/weights_0 [1990, 512]`, and so on.

Finally I tried loading the checkpoint and perform a translation: of course the result was not the one expected. The translation was absolutely rubbish.

Now I see two options: my code has a bug somewhere, or option 2 the process itself is not valid.
My question is: is this process correct?  Is is possible to do such transformation without altering previous translation results?

Thanks!

### *TensorFlow* and *tensor2tensor* versions
TensorFlow: 1.6
Tensor2Tensor: 1.5.5

**Comment by martinpopel** [comment]
I have no idea how the embeddings are stored, so just a suggestion:
You can train a new model with hparams with `symbol_modality_num_shards=1`, so there will be just one matrix instead of 16, so the process of expanding the matrix will be easier. Once it works here, you can try again the 16 shards case.

**Comment by davidecaroselli** [comment]
@martinpopel sounds like a very good idea! I will work on this in the meantime.

**Comment by davidecaroselli** [comment]
@martinpopel it works!

So with `symbol_modality_num_shards=1` I can expand the embeddings with zeros tensors with shape [512] and the translation remains unchanged.

That's great.
The question now seems to be: how embeddings are mapped when `symbol_modality_num_shards > 1` ? Do you know where I can find such info?

**Comment by martinpopel** [comment]
I had not know, I just know how to use [ack](https://beyondgrep.com/) and it says
https://github.com/tensorflow/tensor2tensor/blob/5ac81b4d2/tensor2tensor/layers/modalities.py#L74-L102

**Comment by davidecaroselli** [comment]
Hi @martinpopel 

finally the process works: the issues were related to a model compatibility issues.

Thanks a million for your help!
Davide
