### ISSUE TITLE
*bug* Fail to download training-parallel-corpora-common-crawl

### ISSUE THREAD

**Issue by DonPex** [tensorflow/tensor2tensor#735]
### Description
When I tried to run the example about the EN-DE translation, I obtained this error
`tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 'http' not implemented (file: 'http://www.statmt.org/wmt13/training-parallel-commoncrawl.tgz')`
> …

### *TensorFlow* and *tensor2tensor* versions
TF 1.7 T2T 1.5.7

> …

### In case of bug report: Steps to reproduce the problem

> …

### In case of bug report: Error log

> …

**Comment by vacat** [comment]
is this problem fixed? I encounter the same problem.
