### ISSUE TITLE
[Bug] 404 on Distributed Training Documentation

### ISSUE THREAD

**Issue by malomarrec** [tensorflow/tensor2tensor#748]
The main README.md has a link to Distributed training documentation (in the Trainer section).
It gives a 404:
https://github.com/tensorflow/tensor2tensor/tree/master/tensor2tensor/g3doc/distributed_training.md

**Comment by stefan-it** [comment]
Hm, I corrected that some while ago in #704... I will fill another PR to correct that, thanks for that hint :)

**Comment by stefan-it** [comment]
Could you point to the exact line? In the latest `master` version I cannot find the broken link.

**Comment by malomarrec** [comment]
Works now - got into https://github.com/tensorflow/tensor2tensor/blob/master/docs/distributed_training.md which works.
Thanks!
