### ISSUE TITLE
    print("HU-1: {0}; HU-2: {1}; HU-3: {2}; ==> Acc: {3}".format(rand_layer_1, rand_layer_2, rand_layer_3, "%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))) TypeError: 'History' object does not support indexing

### ISSUE THREAD

**Issue by dragz17** [tensorflow/tensor2tensor#793]
### Description
The error is like this
  model.add(Conv2D(32, 3,3,input_shape=img_data[0].shape))
2018-05-11 03:55:28.854923: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-05-11 03:55:29.005507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 3a1e:00:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-05-11 03:55:29.005553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 3a1e:00:00.0, compute capability: 3.7)
testMy11Mei.py:170: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3))`
  model.add(Conv2D(32, 3, 3))
Train on 505 samples, validate on 57 samples
Epoch 1/10
505/505 [==============================] - 2s 4ms/step - loss: 2.0744 - acc: 0.1149 - val_loss: 2.0566 - val_acc: 0.2456
Epoch 2/10
505/505 [==============================] - 1s 1ms/step - loss: 2.0183 - acc: 0.1426 - val_loss: 2.0199 - val_acc: 0.2105
Epoch 3/10
505/505 [==============================] - 1s 2ms/step - loss: 1.9581 - acc: 0.2178 - val_loss: 1.9725 - val_acc: 0.1930
Epoch 4/10
505/505 [==============================] - 1s 2ms/step - loss: 1.9469 - acc: 0.2178 - val_loss: 2.0092 - val_acc: 0.2807
Epoch 5/10
505/505 [==============================] - 1s 1ms/step - loss: 1.9050 - acc: 0.2337 - val_loss: 1.8988 - val_acc: 0.2456
Epoch 6/10
505/505 [==============================] - 1s 1ms/step - loss: 1.8782 - acc: 0.2455 - val_loss: 1.9080 - val_acc: 0.2807
Epoch 7/10
505/505 [==============================] - 1s 1ms/step - loss: 1.8533 - acc: 0.2396 - val_loss: 1.8726 - val_acc: 0.3158
Epoch 8/10
505/505 [==============================] - 1s 2ms/step - loss: 1.8383 - acc: 0.2535 - val_loss: 1.8417 - val_acc: 0.3509
Epoch 9/10
505/505 [==============================] - 1s 2ms/step - loss: 1.8334 - acc: 0.2614 - val_loss: 1.8387 - val_acc: 0.3333
Epoch 10/10
505/505 [==============================] - 1s 2ms/step - loss: 1.8080 - acc: 0.2832 - val_loss: 1.8298 - val_acc: 0.2632
Traceback (most recent call last):
  File "testMy11Mei.py", line 188, in <module>
    print("HU-1: {0}; HU-2: {1}; HU-3: {2}; ==> Acc: {3}".format(rand_layer_1, rand_layer_2, rand_layer_3, "%s: %.2f%%" % (model.metrics_names[1], scores[1]*100)))
TypeError: 'History' object does not support indexing

Can you fix it?

**Comment by lukaszkaiser** [comment]
This does not look like it has much to do with Tensor2Tensor, please stick to T2T bugs here and ask general TensorFlow questions on other forums.
