### ISSUE TITLE
help: Are there instructions for installing from source?

### ISSUE THREAD

**Issue by David-Levinthal** [tensorflow/tensor2tensor#800]
### Description
I install everything from source if at all possible due to requirements and access to prerelease sw.
After git clone  https://github.com/tensorflow/tensor2tensor.git
what should I do?
invoking cd tensor2tensor
and
sudo python setup.py install
I get enormous numbers of warnings
leaving me wondering if I have actually built this correctly
TF R1.8 (git checkout) built from source with cuda 9.1, cudnn7.0.4, nccl 2.1.2, bazel 0.13

> …

### *TensorFlow* and *tensor2tensor* versions

> …

### In case of bug report: Steps to reproduce the problem

> …

### In case of bug report: Error log

> …

**Comment by David-Levinthal** [comment]
sudo python setup.py install finishes with
In file included from /tmp/easy_install-pGtWzb/h5py-2.8.0rc1/h5py/defs.c:610:0:
/tmp/easy_install-pGtWzb/h5py-2.8.0rc1/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

so clearly it did not build correctly

**Comment by martinpopel** [comment]
Try `pip install -e .`.
It seems you don't have the dependency `h5py` correctly installed. If you wish to install even all [dependencies](https://github.com/tensorflow/tensor2tensor/blob/d5ace12a3580e09bcdc40ae90d1f862799e1f9a1/setup.py#L34-L47) (and their dependencies, etc.) from source,... well, I wish you good luck and a lot of patience. But you should report any problems with installing the dependencies at the respective projects, not here.

**Comment by David-Levinthal** [comment]
actually this was very quick
  163  git clone https://github.com/tensorflow/tensor2tensor.git
  164  sudo apt-get install flask bz2file gevent
  165  sudo pip install flask bz2file gevent
  166  sudo pip install google-api-python-client
  167  history
  168  sudo pip install gunicorn gym h5py
  169  sudo pip install numpy requests scipy sympy six
  171  cd tensor2tensor
  172  sudo pip install -e . > t2tbuild.log 2>&1

**Comment by martinpopel** [comment]
Yes, it was quick because `pip` [prefers](https://packaging.python.org/tutorials/installing-packages/#source-distributions-vs-wheels) pre-built wheels over source distributions (but you wrote "*everything* from source if at all possible" in your original post). BTW: `pip` takes care about the installing dependencies automatically, you just need to choose `tensorflow` vs `tensorflow-gpu`.

So if your problem is solved, please close this issue.

**Comment by David-Levinthal** [comment]
is there a way to force the build to be completely local?
d

**Comment by martinpopel** [comment]
After 10 seconds of googling, I found https://pip.pypa.io/en/stable/reference/pip_install/#install-no-binary
(Again, I think these issues should be for discussing Tensor2tensor related issues, not general Python questions.)

**Comment by lukaszkaiser** [comment]
I think building TensorFlow from source can be an adventure not always for the faint of heart, especially with all the GPU kernels ;). Closing this for now, but feel free to reopen please if you have any issues. And thanks for the help Martin!

**Comment by David-Levinthal** [comment]
Yeah..I have things kind of going..ran ende. 250K steps, great final bleu
score reported.I am a bit unclear on a few things like making my own
training data set,
tokenizing, bpe etc, creating a translated file of sentences to feed to
sacre-bleu
building TF from source is no problem..I do it at least 2 times a week :-)
