### ISSUE TITLE
*help* Efficiently move data from CPU to GPU (checkpoint restore)

### ISSUE THREAD

**Issue by davidecaroselli** [tensorflow/tensor2tensor#805]
### Description

I'm trying to implement a "multi-checkpoints" restorer. Basic idea is being able to "pre-load" checkpoints for the same network and be able to restore them quickly on-demand. I started investigating the default checkpoint restorer of TF, but I soon realized that it copies checkpoint data directly into the GPU for efficiency.

For my use case however this is not possibile (GPU cannot hold all checkpoints for RAM constraints). So I ended up implementing something similar to:
```python
assign_ops = [state_ops.assign(global_variable, placeholder) for ...every global_variable... ]
```
And then for every checkpoint I have a different feed_dict:
```python
chkp_A = {placeholder_1: var_1_A, placeholder_2: var_2_A, ...}
chkp_B = {placeholder_1: var_1_B, placeholder_2: var_2_B, ...}
```
It works all as expected, the problem is that it seems to me that the system perform an "hidden" additional step that cause a temporary RAM peek, and of course waste computational time.

For example, let's assume that my checkpoint is taking 1G of RAM and the model in GPU is 2G, where I run `session.run(assign_op, chkp_A)` I can see RAM quickly increase by ~2G and then drop to it's normal level. By this observation I assume that tensor2tensor/tensorflow is silently creating a copy of the model (or the checkpoint?) in RAM and then pushing the result to GPU.

My question is, can I prevent the framework to do such operation? Or, if this is not possible, can I transform the checkpoint (currently map tf.placeholder -> numpy array) to this intermediate data structure that can be easily pushed to GPU?

Thanks in advance for the help and please let me know if I was unclear in any part and I'll try to explain better!

Davide

### *TensorFlow* and *tensor2tensor* versions

Tensorflow: 1.8.0
Tensor2tensor: 1.6.2

**Comment by martinpopel** [comment]
I am not sure if this will help you (and maybe you know it), but if you just want to load all variables from a checkpoint to CPU memory (numpy arrays), you can use `tf.contrib.framework.list_variables` and `tf.contrib.framework.list_variables.get_tensor(name)`. See [avg_checkpoints.py](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/avg_checkpoints.py).
See also [my SO question](https://stackoverflow.com/questions/47760111/how-to-create-tensorflow-checkpoint-without-a-session).

**Comment by davidecaroselli** [comment]
Hi @martinpopel 
yes, that is exactly how I retrieve those `var_1_A `, `var_1_B` and so on, I looked very close to av_checkpoints.py :).

Still the problem is: even if I have all those tensors in CPU, how can I quickly load them in GPU RAM? What is that RAM-copy step that I observe (using `free -m`) that is consuming time and RAM?
