### ISSUE TITLE
*bug* checkpoints are incompatible wrt training/learning_rate

### ISSUE THREAD

**Issue by martinpopel** [tensorflow/tensor2tensor#809]
When training with `learning_rate_schedule=constant`, the checkpoints contain a key called `training/learning_rate`.
When training with `learning_rate_schedule=rsqrt_decay`, the checkpoints do not contain the key.
Thus one cannot continue training with a constant LR with a model pre-trained with rsqrt_decay, we get the `Key training/learning_rate not found in checkpoint` error.

Should the key be there and why?

tensor2tensor==1.6.0
tensorflow==1.6.0

**Comment by yanboliang** [comment]
@martinpopel I sent a [PR](#842) to fix this issue, wish it can help you. Thanks.

**Comment by lukaszkaiser** [comment]
After merging #842 this should be ok, right? Closing, but feel free to reopen if needed of course!
