### ISSUE TITLE
Large Batch Size

### ISSUE THREAD

**Issue by szhengac** [tensorflow/tensor2tensor#816]
I see a very large batch size (e.g., 4096) used in the code. Dose this mean 4096 sentences are processed at each iteration? This large batch size does not seem be able to fit into a single GPU.

**Comment by stefan-it** [comment]
Please have a look at @martinpopel 's excellent paper "Training Tips for the Transformer Model" [here](https://arxiv.org/abs/1804.00247). On page 4 the parameter `batch_size` is explained:

> Batch Size is the number of training examples used by one GPU in one training step. In sequence-to sequence models, batch size is usually specified as the number of sentence pairs. However, the parameter `batch_size` in T2T translation specifies the approximate number of tokens (subwords) in one batch. This allows to use a higher number of short sentences in one batch or a smaller number of long sentences.

**Comment by szhengac** [comment]
I see. Thank you.
