### ISSUE TITLE
*help* A simple question but I‘m confused for that phenomenon

### ISSUE THREAD

**Issue by zxqchat** [tensorflow/tensor2tensor#829]
### Description

> … 

when I try to print the tf.global_variables() ,and I found the variables  eg.
`
<tf.Variable 'transformer/encoder/layer_3/feed_forward/ffn_layer/input_layer/linear/matrix/Adam:0' shape=(512, 2048) dtype=float32_ref>
`
I konw it may be relative to the "Optimizer", but I am not quite sure ,I have try to find answers in baidu.com or tensorflow inner code but nothing.
### confused problem
when I want to restore the ckpt file to train new parameters,wherther I need to restore the variables with those “Adam” suffix  or just ignore them ?

#### tf version 1.4.0  tensor2tensor version v1.2

**Comment by rsepassi** [comment]
Yes, that variable looks like it has been created by the Adam optimizer. If you're continuing training, then yes, you'll want to restore those. If you're restoring just for prediction, then those can be ignored.
