### ISSUE TITLE
*feature request* Add .pylintrc to define formatting standards for PR's

### ISSUE THREAD

**Issue by cwbeitel** [tensorflow/tensor2tensor#832]
Propose adding a .pylintrc file to define formatting standards for PR's if that is an interest of core developers.

**Comment by martinpopel** [comment]
Yes. Or the other way round: provide a `.pylintrc` which silences all the warning which the core developers ignore anyway, so that users/contributors don't get a full screen of warnings. My own `.pylintrc` for T2T code follows, but I am not a core developer and I guess it is missing many parts.

```
[FORMAT]

#max-line-length=100
indent-string='  '


[MISCELLANEOUS]

# List of note tags to take in consideration, separated by a comma.
# Including TODO into the list of problems is a bad idea, I think.
notes=FIXME,XXX

[MESSAGES CONTROL]

# The purpose of locally disabling a warning is to disable it:-).
# If needed we can detect those places with `ack 'pylint: disable'`.
disable=locally-disabled,locally-enabled
```

**Comment by rsepassi** [comment]
Funny this came in today as I've just pushed out a pylintrc as well as adding pylint to the Travis tests which will auto-trigger for PRs.
