### ISSUE TITLE
Transformer parameters meaning

### ISSUE THREAD

**Issue by DonPex** [tensorflow/tensor2tensor#834]
### Description
>Hi, I can't understand what are the meanings of some parameters in the Transformer model.
In particular I would know what do "input_height", "hidden_dim", "hidden_size".
Thanks.

### *TensorFlow* and *tensor2tensor* versions

>TF: 1.8.0

**Comment by vergilus** [comment]
those are basically the same with conv-net kernel setting. the inputs are batches of matrices and the hidden layers due to multi-head attention has the size and dimension settings
