### ISSUE TITLE
Dependencies between different sentences and between different packed sentence

### ISSUE THREAD

**Issue by peppoS37** [tensorflow/tensor2tensor#843]
### Description

Hi, I can not understand how dependencies are maintained within the model. Given a sentence having its length, when the model sees the next sentence in the batch, is there anything that evaluates the context of the previous sentences? Also for phrases segmented into multiple sentences (Packed Problems), how does it work?
Thanks so much.
### Environment information

TF: 1.8.0

**Comment by martinpopel** [comment]
For all translation problems in the current T2T, each line is translated independently of other lines. It is up to you whether you put a single sentence or e.g. two sentences on one line, but there are several problems with long lines: both training and decoding (with self-attention models) is quadratically longer and you need more GPU memory and/or less lines in one batch (which may slower the convergence or make the training less stable).

I am not sure if Packed Problems work out of the box for translation (you would have to word-align the training data, so a corresponding parts of reference translation are included). Anyway, you could simulate this by manually merging and splitting sentences on lines, so each line has approximately the same length (in number of subwords). And again, each line is translated independently of other lines.

There is an increasing number of research on cross-sentence (document-level) coherence (e.g. [1711.09367](https://arxiv.org/pdf/1711.09367.pdf), [1704.04347](https://arxiv.org/pdf/1704.04347.pdf), [Cross-Sentence-NMT](https://github.com/longyuewangdcu/Cross-Sentence-NMT)), but I am not aware of anything ready to use in T2T.

**Comment by peppoS37** [comment]
Thanks!! A perfect answer ;)

**Comment by peppoS37** [comment]
Thansk! A perfect answer ;)
