### ISSUE TITLE
*bug*

### ISSUE THREAD

**Issue by nimaous** [tensorflow/tensor2tensor#847]
### Description
Creating datashards for a Classification problem, you get an error in the `to_example` method in `generator_utils.py.`
It is because, for a binary classification problem, the target is an `Int` but in `to_example()` method,  it expected a list for `v`. 
...

**Comment by rsepassi** [comment]
The generator to generator_utils needs to have all features be a list.

See `Text2ClassProblem` as an example of a classification problem definition: https://github.com/tensorflow/tensor2tensor/blob/8b312b55e47927d54860f88b26fb5f1c0727049b/tensor2tensor/data_generators/text_problems.py#L474
