### ISSUE TITLE
what's the meaning of hparam batch_size?

### ISSUE THREAD

**Issue by feiga** [tensorflow/tensor2tensor#85]
The batch size is so large(4096). It seems that it doesn't mean the number of training samples(sentences) in one training batch?

**Comment by jekbradbury** [comment]
It's the total number of tokens per batch, allowing either a small number of long sentences or a larger number of short sentences in order to maximize throughput and memory utilization.

**Comment by cshanbo** [comment]
See [#17](https://github.com/tensorflow/tensor2tensor/issues/17), where lukaszkaiser gave more detailed explanation.
