### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlretrieve'

### ISSUE THREAD

**Issue by selay01** [tensorflow/tensor2tensor#87]
ubuntu x86_64,
anaconda2-->env:python35 64bit

when runing:
"
PROBLEM=wmt_ende_tokens_32k
MODEL=transformer
HPARAMS=transformer_base

DATA_DIR=$HOME/t2t_data
TMP_DIR=/tmp/t2t_datagen
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

t2t-datagen \
  --data_dir=$DATA_DIR \
  --tmp_dir=$TMP_DIR \
  --num_shards=100 \
  --problem=$PROBLEM
"

error:
......
File "/home/prog/anaconda2/envs/tensorflow/lib/python3.5/site-packages/tensor2tensor/data_generators/generator_utils.py", line 160, in maybe_download
    inprogress_filepath, _ = urllib.urlretrieve(url, inprogress_filepath,
AttributeError: module 'urllib' has no attribute 'urlretrieve'

**Comment by selay01** [comment]
Does not T2T support Python3+?

**Comment by stefan-it** [comment]
You should try the latest version of `tensor2tensor` :)

**Comment by lukaszkaiser** [comment]
This is hopefully corrected in 1.0.11. please give it a try. I'm closing for now, please reopen if you still see the issue.

**Comment by liuzc188** [comment]
是Python版本的问题吗？
