### ISSUE TITLE
'NoneType' object has no attribute  'endswith' when train problem translate_enzh_wmt32k

### ISSUE THREAD

**Issue by skeletonli** [tensorflow/tensor2tensor#895]
### Description

I trained model with translate_enzh_wmt32k, but when I run the code below, it show
"if problem_name.endswith("_rev"):
AttributeError: 'NoneType' object has no attribute 'endswith'

The codes are here:
"
PROBLEM=translate_enzh_wmt32k
MODEL=transformer
HPARAMS=transformer_base_single_gpu

DATA_DIR=$HOME/t2t_data
TMP_DIR=/tmp/t2t_datagen
TRAIN_DIR=$HOME/t2t_train/$PROBLEM/$MODEL-$HPARAMS

mkdir -p $DATA_DIR $TMP_DIR $TRAIN_DIR

t2t-datagen
--data_dir=$DATA_DIR
--tmp_dir=$TMP_DIR
--problem=$PROBLEM

t2t-trainer
--data_dir=$DATA_DIR
--problems=$PROBLEM
--model=$MODEL
--hparams_set=$HPARAMS
--output_dir=$TRAIN_DIR
"

### Environment information

ubnuntu16.4
cuda9.0
tensorflow1.8

How can I solve this problem?
And I have run the example PROBLEM=translate_ende_wmt32k sucessfullybefore , and then handly deleted three folder $HOME/t2t_data,/tmp/t2t_datagen and $HOME/t2t_train. After that I run the PROBLEM=translate_enzh_wmt32k it shows the error.

**Comment by darthdeus** [comment]
@skeletonli Have you figured out what was causing the issue? I'm getting the same error.
