### ISSUE TITLE
Concurrent data generation and training

### ISSUE THREAD

**Issue by chiayewken** [tensorflow/tensor2tensor#914]
I understand that t2t-trainer has a generate data option. But as far as I know, it generates data then proceeds to training. Is there a way to concurrently generate data in batches and train on them concurrently to save time for large datasets?

**Comment by martinpopel** [comment]
You can use `t2t-datagen` for generating the training data. I think recently it got support for multi-thread processing (but I am not sure, maybe you need to switch it on with some option - I'm busy now to check). You can even parallelize datagen manually (e.g. on different machines) and then just concat the TFRecords files (they have no header), or just rename the files. What is tricky is your idea of starting training before all the data is ready. You can resume training (i.e. stop and start again from the last checkpoint but with a new dataset), but does not seem user-friendly to me. I usually run `t2t-datagen` on CPU-only machines and `t2t-trainer` on GPU machines.
