### ISSUE TITLE
Suggested model and hparams for SQuAD

### ISSUE THREAD

**Issue by JohannesTK** [tensorflow/tensor2tensor#916]
Any suggestions for replacing the question marks?

`t2t-trainer --problem=squad --data_dir=squad_data --output_dir=squad_train --model=? --hparams_set=?  --train_steps=?`

Meaning

* model
* hparams_set
* train_steps

**Comment by mehmedes** [comment]
Why not try ```transformer_base``` as a first step?
Moreover, I'd use ```--problem=squad_concat```. Hereby, question and context are concatenated together in inputs, which allows for applying seq2seq model.
