### ISSUE TITLE
Training model for translation on my own data set

### ISSUE THREAD

**Issue by Sugeeth95** [tensorflow/tensor2tensor#946]
I have trained the EN-DE translation on transformer network by using steps in walkthrough for 300k steps. Now I want to train my model from the last checkpoint with parallel data in present in my machine(seperate .en and .de files). I tried using https://github.com/tensorflow/tensor2tensor#adding-a-dataset but as far as I understand the data set has to be specified in a downloadable  format  with a link. Can I know how to train with data present in my machine and also if I want to train only on my dataset(present in my machine again) rather than training from a checkpoint and the data from walkthrough how can I proceed about?
Thanks in advance!!

**Comment by Sugeeth95** [comment]
Sorry @martinpopel  my bad I saw the issue before commenting but completely couldn't understand it so raised an issue. Should I place my files in the disk in t2t-data folder if yes then url column what url should I specify

**Comment by martinpopel** [comment]
What is unclear in https://github.com/tensorflow/tensor2tensor/issues/516#issuecomment-357465729 ?
If you want to reuse an existing vocab, then store your data wherever you want and just provide the proper `input_path` in `data_generators.wmt.token_generator(input_path + "en", input_path + "xy", vocab, EOS)`.
If you want to generate a new vocab from your data, the easiest way is to store your data in the tmp_dir and provide a dummy download url.
