### ISSUE TITLE
Poor performance of Transformer on Wikitext-2 LM 

### ISSUE THREAD

**Issue by AranKomat** [tensorflow/tensor2tensor#947]
For PTB, poor performance of Transformer was already discussed [#128](https://github.com/tensorflow/tensor2tensor/issues/128) [#108](https://github.com/tensorflow/tensor2tensor/issues/108). I've also observed similar phenomenon for Wikitext-2 without various hyperparameters and architectural modification. Since Transformer with full attention or DMCA performed much better on Wikipedia summarization than seq2seq w/ attention, I was tempted to assume it would work. With the hyperparameters and architectures I've attempted, including the ones in _Attention is All You Need_ and the aforementioned wikipedia summarization paper, I've observed that Transformer outperformed LSTM and its variants on a certain news dataset that is similar to 1 Billion Words Dataset. Like 1BLM, this dataset has only sentence-long dependency; however, its total token count is comparable to Wikitext-2. This result aligns with tensor2tensor's result on 1BLM. Have you guys found a way to resolve this problem?

**Comment by xfdywy** [comment]
Hi, I also observed the similar problems. Do you have any comments or suggestions on this issue?
