### ISSUE TITLE
Bug - one mistaken line in next_frame.py

### ISSUE THREAD

**Issue by theJiangYu** [tensorflow/tensor2tensor#953]
### Description
There is a bug of one newly added extra line: 
from tensorflow_models.slim.nets.cyclegan import cyclegan_upsample
in
tensor2tensor/models/research/next_frame.py

...

### Environment information

```
OS: <your answer here>

$ pip freeze | grep tensor
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs
from tensorflow_models.slim.nets.cyclegan import cyclegan_upsample
ModuleNotFoundError: No module named 'tensorflow_models'
It causes experiments whichever has dependency of next_frame.py fail. 
```
# Steps to reproduce:
Run any experiment that has dependency of the file
tensor2tensor/models/research/next_frame.py
...
```

```
# Error logs:
ModuleNotFoundError: No module named 'tensorflow_models'
...
```

**Comment by jiangyu6** [comment]
Fixed in
https://github.com/tensorflow/tensor2tensor/pull/954

**Comment by jiangyu6** [comment]
Opps waiting for https://github.com/tensorflow/tensor2tensor/pull/954  to be merged.

**Comment by theJiangYu** [comment]
I am closing this issue because it has been fix in the commit: 
https://github.com/tensorflow/tensor2tensor/commit/4a5db4ac52f89dc237eced8722a059fa2ab06d70
Jiang
