### ISSUE TITLE
Minor Typo (tf.logging.info)

### ISSUE THREAD

**Issue by repoloper** [tensorflow/tensor2tensor#968]
May be not worth a ticket, but just wanted to bring it to attention. I guess it must be tf.logging.info as opposed to "into". 

https://github.com/tensorflow/tensor2tensor/blob/6a7ef7f79f56fdcb1b16ae76d7e61cb09033dc4f/tensor2tensor/utils/get_rouge.py#L49

**Comment by afrozenator** [comment]
Thanks @repoloper -- would you like to contribute by sending a pull request :) 👍

**Comment by repoloper** [comment]
Sure. Will do!

**Comment by afrozenator** [comment]
Thanks @repoloper -- looking forward to it!

**Comment by afrozenator** [comment]
Thanks @repoloper ! Marking as closed now.
