### ISSUE TITLE
GPU usage with the Transformer model

### ISSUE THREAD

**Issue by mabergerx** [tensorflow/tensor2tensor#997]
### Description
I've created a custom translation Problem following the example of 

https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/translate_enmk.py

Everything from data generation on my own data to interactive decoding went fine and I'm very happy with the results! However, while reviewing TensorBoard I noticed that I've got quite low global_step/sec ratio (around 0.26 global_step/sec). My setup is a double GTX 1080 Ti with CUDA and cuDNN. I'm using around 3 million training examples. 

```nvidia-smi``` reports low GPU usage in both memory usage as the GPU-Util. In fact, while continuing a training session my nvida-smi reports 0% GPU usage.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:17:00.0 Off |                  N/A |
| 12%   45C    P8    19W / 260W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:65:00.0  On |                  N/A |
| 19%   47C    P8    14W / 260W |    254MiB / 11175MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    1      1267      G   /usr/lib/xorg/Xorg                            16MiB |
|    1      1322      G   /usr/bin/gnome-shell                          49MiB |
|    1      2063      G   /usr/lib/xorg/Xorg                            86MiB |
|    1      2208      G   /usr/bin/gnome-shell                          99MiB |
+-----------------------------------------------------------------------------+
```

The only hook I've got is that while supplying --worker_gpu=2 to the trainer I do see
```INFO:tensorflow:schedule=continuous_train_and_eval
      INFO:tensorflow:worker_gpu=2
      INFO:tensorflow:sync=False
      INFO:tensorflow:datashard_devices: ['gpu:0', 'gpu:1']
      INFO:tensorflow:caching_devices: None
      INFO:tensorflow:ps_devices: ['gpu:0', 'gpu:1']
```

What is going on here?

P.S. In #390 someone suggested looking at the pcie mode and look at GT/s. I've run
```sudo lspci -vv | grep -P "[0-9a-f]{2}:[0-9a-f]{2}.[0-9a-f]|LnkSta:```

and saw the following GPU settings, suggesting they do not use the x16 mode? Sorry If this is wrong, I'm not an expert in GPU configs:
```
65:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1) (prog-if 00 [VGA controller])
		LnkSta:	Speed 2.5GT/s, Width x16, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
65:00.1 Audio device: NVIDIA Corporation GP102 HDMI Audio Controller (rev a1)
		LnkSta:	Speed 2.5GT/s, Width x16, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
```

Excuse me for a lot of info and thank you very much for the amazing tensor2tensor lib!

### Training commando

```
t2t-trainer     --data_dir=$DATA_DIR     --t2t_usr_dir=$CUSTOM_DIR     --problem=$CUSTOM_PROBLEM    --model=transformer    --hparams_set=transformer_base_single_gpu     --output_dir=$TRAIN_DIR   --train_steps=20000     --worker_gpu=2
```

### Environment information

```
OS: Ubuntu 17.10

$ pip freeze | grep tensor
tensor2tensor==1.7.0
tensorboard==1.10.0
tensorflow==1.10.0
tensorflow-gpu==1.5.0
tensorflow-tensorboard==1.5.1

$ python -V
Python 3.6.4 :: Anaconda, Inc.
```

**Comment by colmantse** [comment]
you may want to delete tensorflow? or put tensorflow and tensorflow-gpu into 2 virtual-env. 
I suppose the system is using tensorflow cpu instead of tensorflow-gpu.

**Comment by mabergerx** [comment]
@colmantse Thank you! You pointed me in the right direction: as mentioned in 

https://github.com/tensorflow/tensorflow/issues/12388

I needed to uninstall tensorflow and tensorflow-gpu and downgrade it to 1.8.0. Now both GPU's are used intensively and the step/sec drastically decreased! 
The issue with my old configuration (tf version 1.10.0 and tf-gpu 1.5.0) stays, however. Maybe it's a CUDA issue but I'm not exactly sure.

**Comment by colmantse** [comment]
i find for linux, the best way to install tensorflow gpu is from source, it is extremely easy and guarantee always better performance than with pip.
